    .rom_head 0x08000000 : {
        asm/rom.o(.rodata)
    } > ROM
    .rom_sub_0802B8BC 0x0802B8BC : {
        asm/matchings/sub_0802B8BC.o(.text)
    } > ROM
    .rom_gap_000 0x0802B8D0 : {
        asm/rom_gap_000.o(.rodata)
    } > ROM
    .rom_sub_0802B90C 0x0802B90C : {
        asm/matchings/sub_0802B90C.o(.text)
    } > ROM
    .rom_gap_001 0x0802B918 : {
        asm/rom_gap_001.o(.rodata)
    } > ROM
    .rom_sub_0802D598 0x0802D598 : {
        asm/matchings/sub_0802D598.o(.text)
    } > ROM
    .rom_gap_002 0x0802D5B4 : {
        asm/rom_gap_002.o(.rodata)
    } > ROM
    .rom_sub_0802D8C4 0x0802D8C4 : {
        asm/matchings/sub_0802D8C4.o(.text)
    } > ROM
    .rom_gap_003 0x0802D8DC : {
        asm/rom_gap_003.o(.rodata)
    } > ROM
    .rom_sub_0802E1EC 0x0802E1EC : {
        asm/matchings/sub_0802E1EC.o(.text)
    } > ROM
    .rom_gap_004 0x0802E210 : {
        asm/rom_gap_004.o(.rodata)
    } > ROM
    .rom_sub_08031294 0x08031294 : {
        asm/matchings/sub_08031294.o(.text)
    } > ROM
    .rom_gap_005 0x080312B0 : {
        asm/rom_gap_005.o(.rodata)
    } > ROM
    .rom_sub_080312D8 0x080312D8 : {
        asm/matchings/sub_080312D8.o(.text)
    } > ROM
    .rom_sub_080312EC 0x080312EC : {
        asm/matchings/sub_080312EC.o(.text)
    } > ROM
    .rom_gap_006 0x08031300 : {
        asm/rom_gap_006.o(.rodata)
    } > ROM
    .rom_sub_080314FC 0x080314FC : {
        asm/matchings/sub_080314FC.o(.text)
    } > ROM
    .rom_gap_007 0x08031510 : {
        asm/rom_gap_007.o(.rodata)
    } > ROM
    .rom_sub_08032DB8 0x08032DB8 : {
        asm/matchings/sub_08032DB8.o(.text)
    } > ROM
    .rom_gap_008 0x08032DC4 : {
        asm/rom_gap_008.o(.rodata)
    } > ROM
    .rom_sub_080338E4 0x080338E4 : {
        asm/matchings/sub_080338E4.o(.text)
    } > ROM
    .rom_gap_009 0x080338EE : {
        asm/rom_gap_009.o(.rodata)
    } > ROM
    .rom_sub_08033958 0x08033958 : {
        asm/matchings/sub_08033958.o(.text)
    } > ROM
    .rom_gap_010 0x0803396C : {
        asm/rom_gap_010.o(.rodata)
    } > ROM
    .rom_sub_08033A94 0x08033A94 : {
        asm/matchings/sub_08033A94.o(.text)
    } > ROM
    .rom_gap_011 0x08033A98 : {
        asm/rom_gap_011.o(.rodata)
    } > ROM
    .rom_sub_08033C1C 0x08033C1C : {
        asm/matchings/sub_08033C1C.o(.text)
    } > ROM
    .rom_gap_012 0x08033C3C : {
        asm/rom_gap_012.o(.rodata)
    } > ROM
    .rom_sub_08033E3C 0x08033E3C : {
        asm/matchings/sub_08033E3C.o(.text)
    } > ROM
    .rom_gap_013 0x08033E5A : {
        asm/rom_gap_013.o(.rodata)
    } > ROM
    .rom_sub_08033F24 0x08033F24 : {
        asm/matchings/sub_08033F24.o(.text)
    } > ROM
    .rom_gap_014 0x08033F2E : {
        asm/rom_gap_014.o(.rodata)
    } > ROM
    .rom_sub_08033F30 0x08033F30 : {
        asm/matchings/sub_08033F30.o(.text)
    } > ROM
    .rom_gap_015 0x08033F48 : {
        asm/rom_gap_015.o(.rodata)
    } > ROM
    .rom_sub_08034414 0x08034414 : {
        asm/matchings/sub_08034414.o(.text)
    } > ROM
    .rom_gap_016 0x0803441E : {
        asm/rom_gap_016.o(.rodata)
    } > ROM
    .rom_sub_080346A8 0x080346A8 : {
        asm/matchings/sub_080346A8.o(.text)
    } > ROM
    .rom_gap_017 0x080346B2 : {
        asm/rom_gap_017.o(.rodata)
    } > ROM
    .rom_sub_080346C0 0x080346C0 : {
        asm/matchings/sub_080346C0.o(.text)
    } > ROM
    .rom_gap_018 0x080346DA : {
        asm/rom_gap_018.o(.rodata)
    } > ROM
    .rom_sub_0803484C 0x0803484C : {
        asm/matchings/sub_0803484C.o(.text)
    } > ROM
    .rom_gap_019 0x08034868 : {
        asm/rom_gap_019.o(.rodata)
    } > ROM
    .rom_sub_08034FDC 0x08034FDC : {
        asm/matchings/sub_08034FDC.o(.text)
    } > ROM
    .rom_sub_08034FF8 0x08034FF8 : {
        asm/matchings/sub_08034FF8.o(.text)
    } > ROM
    .rom_gap_020 0x08035014 : {
        asm/rom_gap_020.o(.rodata)
    } > ROM
    .rom_sub_08035878 0x08035878 : {
        asm/matchings/sub_08035878.o(.text)
    } > ROM
    .rom_gap_021 0x08035884 : {
        asm/rom_gap_021.o(.rodata)
    } > ROM
    .rom_sub_080358CC 0x080358CC : {
        asm/matchings/sub_080358CC.o(.text)
    } > ROM
    .rom_gap_022 0x080358D6 : {
        asm/rom_gap_022.o(.rodata)
    } > ROM
    .rom_sub_08036190 0x08036190 : {
        asm/matchings/sub_08036190.o(.text)
    } > ROM
    .rom_sub_080361A8 0x080361A8 : {
        asm/matchings/sub_080361A8.o(.text)
    } > ROM
    .rom_gap_023 0x080361CC : {
        asm/rom_gap_023.o(.rodata)
    } > ROM
    .rom_sub_0803DD60 0x0803DD60 : {
        asm/matchings/sub_0803DD60.o(.text)
    } > ROM
    .rom_sub_0803DD88 0x0803DD88 : {
        asm/matchings/sub_0803DD88.o(.text)
    } > ROM
    .rom_sub_0803DDB0 0x0803DDB0 : {
        asm/matchings/sub_0803DDB0.o(.text)
    } > ROM
    .rom_sub_0803DDD8 0x0803DDD8 : {
        asm/matchings/sub_0803DDD8.o(.text)
    } > ROM
    .rom_gap_024 0x0803DE00 : {
        asm/rom_gap_024.o(.rodata)
    } > ROM
    .rom_sub_0803EBB0 0x0803EBB0 : {
        asm/matchings/sub_0803EBB0.o(.text)
    } > ROM
    .rom_gap_025 0x0803EBD8 : {
        asm/rom_gap_025.o(.rodata)
    } > ROM
    .rom_sub_0803EC34 0x0803EC34 : {
        asm/matchings/sub_0803EC34.o(.text)
    } > ROM
    .rom_gap_026 0x0803EC5C : {
        asm/rom_gap_026.o(.rodata)
    } > ROM
    .rom_sub_0803ECB8 0x0803ECB8 : {
        asm/matchings/sub_0803ECB8.o(.text)
    } > ROM
    .rom_gap_027 0x0803ECE0 : {
        asm/rom_gap_027.o(.rodata)
    } > ROM
    .rom_sub_0803EDC8 0x0803EDC8 : {
        asm/matchings/sub_0803EDC8.o(.text)
    } > ROM
    .rom_gap_028 0x0803EDDC : {
        asm/rom_gap_028.o(.rodata)
    } > ROM
    .rom_sub_0803EDF0 0x0803EDF0 : {
        asm/matchings/sub_0803EDF0.o(.text)
    } > ROM
    .rom_gap_029 0x0803EE04 : {
        asm/rom_gap_029.o(.rodata)
    } > ROM
    .rom_sub_080400C0 0x080400C0 : {
        asm/matchings/sub_080400C0.o(.text)
    } > ROM
    .rom_gap_030 0x080400D4 : {
        asm/rom_gap_030.o(.rodata)
    } > ROM
    .rom_sub_08040530 0x08040530 : {
        asm/matchings/sub_08040530.o(.text)
    } > ROM
    .rom_gap_031 0x0804054C : {
        asm/rom_gap_031.o(.rodata)
    } > ROM
    .rom_sub_080428C4 0x080428C4 : {
        asm/matchings/sub_080428C4.o(.text)
    } > ROM
    .rom_gap_032 0x080428F0 : {
        asm/rom_gap_032.o(.rodata)
    } > ROM
    .rom_sub_080429C0 0x080429C0 : {
        asm/matchings/sub_080429C0.o(.text)
    } > ROM
    .rom_gap_033 0x080429CC : {
        asm/rom_gap_033.o(.rodata)
    } > ROM
    .rom_sub_08042B00 0x08042B00 : {
        asm/matchings/sub_08042B00.o(.text)
    } > ROM
    .rom_gap_034 0x08042B28 : {
        asm/rom_gap_034.o(.rodata)
    } > ROM
    .rom_sub_08042E78 0x08042E78 : {
        asm/matchings/sub_08042E78.o(.text)
    } > ROM
    .rom_gap_035 0x08042E94 : {
        asm/rom_gap_035.o(.rodata)
    } > ROM
    .rom_sub_080433F4 0x080433F4 : {
        asm/matchings/sub_080433F4.o(.text)
    } > ROM
    .rom_gap_036 0x08043420 : {
        asm/rom_gap_036.o(.rodata)
    } > ROM
    .rom_sub_08043974 0x08043974 : {
        asm/matchings/sub_08043974.o(.text)
    } > ROM
    .rom_gap_037 0x08043980 : {
        asm/rom_gap_037.o(.rodata)
    } > ROM
    .rom_sub_080447B4 0x080447B4 : {
        asm/matchings/sub_080447B4.o(.text)
    } > ROM
    .rom_gap_038 0x080447CA : {
        asm/rom_gap_038.o(.rodata)
    } > ROM
    .rom_sub_08044D8C 0x08044D8C : {
        asm/matchings/sub_08044D8C.o(.text)
    } > ROM
    .rom_gap_039 0x08044DAA : {
        asm/rom_gap_039.o(.rodata)
    } > ROM
    .rom_sub_080473E4 0x080473E4 : {
        asm/matchings/sub_080473E4.o(.text)
    } > ROM
    .rom_gap_040 0x080473F8 : {
        asm/rom_gap_040.o(.rodata)
    } > ROM
    .rom_sub_080475C4 0x080475C4 : {
        asm/matchings/sub_080475C4.o(.text)
    } > ROM
    .rom_sub_080475F4 0x080475F4 : {
        asm/matchings/sub_080475F4.o(.text)
    } > ROM
    .rom_gap_041 0x08047624 : {
        asm/rom_gap_041.o(.rodata)
    } > ROM
    .rom_sub_08060254 0x08060254 : {
        asm/matchings/sub_08060254.o(.text)
    } > ROM
    .rom_gap_042 0x0806026C : {
        asm/rom_gap_042.o(.rodata)
    } > ROM
    .rom_sub_080602C0 0x080602C0 : {
        asm/matchings/sub_080602C0.o(.text)
    } > ROM
    .rom_gap_043 0x080602CE : {
        asm/rom_gap_043.o(.rodata)
    } > ROM
    .rom_sub_08060394 0x08060394 : {
        asm/matchings/sub_08060394.o(.text)
    } > ROM
    .rom_gap_044 0x080603A2 : {
        asm/rom_gap_044.o(.rodata)
    } > ROM
    .rom_sub_08060428 0x08060428 : {
        asm/matchings/sub_08060428.o(.text)
    } > ROM
    .rom_gap_045 0x08060436 : {
        asm/rom_gap_045.o(.rodata)
    } > ROM
    .rom_sub_08060438 0x08060438 : {
        asm/matchings/sub_08060438.o(.text)
    } > ROM
    .rom_gap_046 0x08060446 : {
        asm/rom_gap_046.o(.rodata)
    } > ROM
    .rom_sub_08060448 0x08060448 : {
        asm/matchings/sub_08060448.o(.text)
    } > ROM
    .rom_gap_047 0x08060456 : {
        asm/rom_gap_047.o(.rodata)
    } > ROM
    .rom_sub_08060458 0x08060458 : {
        asm/matchings/sub_08060458.o(.text)
    } > ROM
    .rom_gap_048 0x08060466 : {
        asm/rom_gap_048.o(.rodata)
    } > ROM
    .rom_sub_080604A4 0x080604A4 : {
        asm/matchings/sub_080604A4.o(.text)
    } > ROM
    .rom_gap_049 0x080604C8 : {
        asm/rom_gap_049.o(.rodata)
    } > ROM
    .rom_sub_08060798 0x08060798 : {
        asm/matchings/sub_08060798.o(.text)
    } > ROM
    .rom_gap_050 0x080607BC : {
        asm/rom_gap_050.o(.rodata)
    } > ROM
    .rom_sub_080608D4 0x080608D4 : {
        asm/matchings/sub_080608D4.o(.text)
    } > ROM
    .rom_gap_051 0x080608F4 : {
        asm/rom_gap_051.o(.rodata)
    } > ROM
    .rom_sub_080615EC 0x080615EC : {
        asm/matchings/sub_080615EC.o(.text)
    } > ROM
    .rom_sub_08061610 0x08061610 : {
        asm/matchings/sub_08061610.o(.text)
    } > ROM
    .rom_gap_052 0x08061628 : {
        asm/rom_gap_052.o(.rodata)
    } > ROM
    .rom_sub_08061784 0x08061784 : {
        asm/matchings/sub_08061784.o(.text)
    } > ROM
    .rom_gap_053 0x08061794 : {
        asm/rom_gap_053.o(.rodata)
    } > ROM
    .rom_sub_080617B4 0x080617B4 : {
        asm/matchings/sub_080617B4.o(.text)
    } > ROM
    .rom_gap_054 0x080617C4 : {
        asm/rom_gap_054.o(.rodata)
    } > ROM
    .rom_sub_08061A98 0x08061A98 : {
        asm/matchings/sub_08061A98.o(.text)
    } > ROM
    .rom_sub_08061AA8 0x08061AA8 : {
        asm/matchings/sub_08061AA8.o(.text)
    } > ROM
    .rom_gap_055 0x08061AB8 : {
        asm/rom_gap_055.o(.rodata)
    } > ROM
    .rom_sub_08061BDC 0x08061BDC : {
        asm/matchings/sub_08061BDC.o(.text)
    } > ROM
    .rom_gap_056 0x08061BE8 : {
        asm/rom_gap_056.o(.rodata)
    } > ROM
    .rom_sub_08061E40 0x08061E40 : {
        asm/matchings/sub_08061E40.o(.text)
    } > ROM
    .rom_gap_057 0x08061E54 : {
        asm/rom_gap_057.o(.rodata)
    } > ROM
    .rom_sub_08062098 0x08062098 : {
        asm/matchings/sub_08062098.o(.text)
    } > ROM
    .rom_gap_058 0x0806209C : {
        asm/rom_gap_058.o(.rodata)
    } > ROM
    .rom_sub_08062634 0x08062634 : {
        asm/matchings/sub_08062634.o(.text)
    } > ROM
    .rom_gap_059 0x08062640 : {
        asm/rom_gap_059.o(.rodata)
    } > ROM
    .rom_sub_08062684 0x08062684 : {
        asm/matchings/sub_08062684.o(.text)
    } > ROM
    .rom_gap_060 0x08062698 : {
        asm/rom_gap_060.o(.rodata)
    } > ROM
    .rom_sub_08062728 0x08062728 : {
        asm/matchings/sub_08062728.o(.text)
    } > ROM
    .rom_gap_061 0x0806273A : {
        asm/rom_gap_061.o(.rodata)
    } > ROM
    .rom_sub_080628E4 0x080628E4 : {
        asm/matchings/sub_080628E4.o(.text)
    } > ROM
    .rom_gap_062 0x080628F8 : {
        asm/rom_gap_062.o(.rodata)
    } > ROM
    .rom_sub_08062A14 0x08062A14 : {
        asm/matchings/sub_08062A14.o(.text)
    } > ROM
    .rom_sub_08062A1C 0x08062A1C : {
        asm/matchings/sub_08062A1C.o(.text)
    } > ROM
    .rom_gap_063 0x08062A2C : {
        asm/rom_gap_063.o(.rodata)
    } > ROM
    .rom_sub_08066390 0x08066390 : {
        asm/matchings/sub_08066390.o(.text)
    } > ROM
    .rom_sub_0806639C 0x0806639C : {
        asm/matchings/sub_0806639C.o(.text)
    } > ROM
    .rom_gap_064 0x080663B8 : {
        asm/rom_gap_064.o(.rodata)
    } > ROM
    .rom_sub_08066434 0x08066434 : {
        asm/matchings/sub_08066434.o(.text)
    } > ROM
    .rom_sub_08066440 0x08066440 : {
        asm/matchings/sub_08066440.o(.text)
    } > ROM
    .rom_sub_0806644C 0x0806644C : {
        asm/matchings/sub_0806644C.o(.text)
    } > ROM
    .rom_gap_065 0x0806645C : {
        asm/rom_gap_065.o(.rodata)
    } > ROM
    .rom_sub_080674A0 0x080674A0 : {
        asm/matchings/sub_080674A0.o(.text)
    } > ROM
    .rom_sub_080674A4 0x080674A4 : {
        asm/matchings/sub_080674A4.o(.text)
    } > ROM
    .rom_gap_066 0x080674AA : {
        asm/rom_gap_066.o(.rodata)
    } > ROM
    .rom_sub_080674AC 0x080674AC : {
        asm/matchings/sub_080674AC.o(.text)
    } > ROM
    .rom_sub_080674B0 0x080674B0 : {
        asm/matchings/sub_080674B0.o(.text)
    } > ROM
    .rom_sub_080674B4 0x080674B4 : {
        asm/matchings/sub_080674B4.o(.text)
    } > ROM
    .rom_gap_067 0x080674BA : {
        asm/rom_gap_067.o(.rodata)
    } > ROM
    .rom_sub_08067634 0x08067634 : {
        asm/matchings/sub_08067634.o(.text)
    } > ROM
    .rom_gap_068 0x08067648 : {
        asm/rom_gap_068.o(.rodata)
    } > ROM
    .rom_sub_08067890 0x08067890 : {
        asm/matchings/sub_08067890.o(.text)
    } > ROM
    .rom_gap_069 0x080678A4 : {
        asm/rom_gap_069.o(.rodata)
    } > ROM
    .rom_sub_080679A4 0x080679A4 : {
        asm/matchings/sub_080679A4.o(.text)
    } > ROM
    .rom_sub_080679C0 0x080679C0 : {
        asm/matchings/sub_080679C0.o(.text)
    } > ROM
    .rom_gap_070 0x080679DC : {
        asm/rom_gap_070.o(.rodata)
    } > ROM
    .rom_sub_08067A9C 0x08067A9C : {
        asm/matchings/sub_08067A9C.o(.text)
    } > ROM
    .rom_gap_071 0x08067A9E : {
        asm/rom_gap_071.o(.rodata)
    } > ROM
    .rom_sub_08067B98 0x08067B98 : {
        asm/matchings/sub_08067B98.o(.text)
    } > ROM
    .rom_gap_072 0x08067B9E : {
        asm/rom_gap_072.o(.rodata)
    } > ROM
    .rom_sub_08068014 0x08068014 : {
        asm/matchings/sub_08068014.o(.text)
    } > ROM
    .rom_gap_073 0x0806801E : {
        asm/rom_gap_073.o(.rodata)
    } > ROM
    .rom_sub_08068558 0x08068558 : {
        asm/matchings/sub_08068558.o(.text)
    } > ROM
    .rom_sub_08068574 0x08068574 : {
        asm/matchings/sub_08068574.o(.text)
    } > ROM
    .rom_sub_08068584 0x08068584 : {
        asm/matchings/sub_08068584.o(.text)
    } > ROM
    .rom_gap_074 0x08068590 : {
        asm/rom_gap_074.o(.rodata)
    } > ROM
    .rom_sub_080686D8 0x080686D8 : {
        asm/matchings/sub_080686D8.o(.text)
    } > ROM
    .rom_gap_075 0x080686E4 : {
        asm/rom_gap_075.o(.rodata)
    } > ROM
    .rom_sub_08068884 0x08068884 : {
        asm/matchings/sub_08068884.o(.text)
    } > ROM
    .rom_gap_076 0x0806889C : {
        asm/rom_gap_076.o(.rodata)
    } > ROM
    .rom_sub_08069C14 0x08069C14 : {
        asm/matchings/sub_08069C14.o(.text)
    } > ROM
    .rom_gap_077 0x08069C28 : {
        asm/rom_gap_077.o(.rodata)
    } > ROM
    .rom_sub_08069F00 0x08069F00 : {
        asm/matchings/sub_08069F00.o(.text)
    } > ROM
    .rom_gap_078 0x08069F18 : {
        asm/rom_gap_078.o(.rodata)
    } > ROM
    .rom_sub_0806A954 0x0806A954 : {
        asm/matchings/sub_0806A954.o(.text)
    } > ROM
    .rom_gap_079 0x0806A970 : {
        asm/rom_gap_079.o(.rodata)
    } > ROM
    .rom_sub_0806AC68 0x0806AC68 : {
        asm/matchings/sub_0806AC68.o(.text)
    } > ROM
    .rom_gap_080 0x0806AC7E : {
        asm/rom_gap_080.o(.rodata)
    } > ROM
    .rom_sub_0806B5B8 0x0806B5B8 : {
        asm/matchings/sub_0806B5B8.o(.text)
    } > ROM
    .rom_gap_081 0x0806B5C8 : {
        asm/rom_gap_081.o(.rodata)
    } > ROM
    .rom_sub_0806BB38 0x0806BB38 : {
        asm/matchings/sub_0806BB38.o(.text)
    } > ROM
    .rom_gap_082 0x0806BB48 : {
        asm/rom_gap_082.o(.rodata)
    } > ROM
    .rom_sub_0806BDA8 0x0806BDA8 : {
        asm/matchings/sub_0806BDA8.o(.text)
    } > ROM
    .rom_gap_083 0x0806BDC2 : {
        asm/rom_gap_083.o(.rodata)
    } > ROM
    .rom_sub_0806BE08 0x0806BE08 : {
        asm/matchings/sub_0806BE08.o(.text)
    } > ROM
    .rom_gap_084 0x0806BE20 : {
        asm/rom_gap_084.o(.rodata)
    } > ROM
    .rom_sub_0806DEF4 0x0806DEF4 : {
        asm/matchings/sub_0806DEF4.o(.text)
    } > ROM
    .rom_gap_085 0x0806DF08 : {
        asm/rom_gap_085.o(.rodata)
    } > ROM
    .rom_sub_0806EE24 0x0806EE24 : {
        asm/matchings/sub_0806EE24.o(.text)
    } > ROM
    .rom_gap_086 0x0806EE48 : {
        asm/rom_gap_086.o(.rodata)
    } > ROM
    .rom_sub_0806EEC4 0x0806EEC4 : {
        asm/matchings/sub_0806EEC4.o(.text)
    } > ROM
    .rom_gap_087 0x0806EEC6 : {
        asm/rom_gap_087.o(.rodata)
    } > ROM
    .rom_sub_0806FDB4 0x0806FDB4 : {
        asm/matchings/sub_0806FDB4.o(.text)
    } > ROM
    .rom_gap_088 0x0806FDD0 : {
        asm/rom_gap_088.o(.rodata)
    } > ROM
    .rom_sub_080705A4 0x080705A4 : {
        asm/matchings/sub_080705A4.o(.text)
    } > ROM
    .rom_gap_089 0x080705C0 : {
        asm/rom_gap_089.o(.rodata)
    } > ROM
    .rom_sub_080705CC 0x080705CC : {
        asm/matchings/sub_080705CC.o(.text)
    } > ROM
    .rom_gap_090 0x080705D2 : {
        asm/rom_gap_090.o(.rodata)
    } > ROM
    .rom_sub_080705D4 0x080705D4 : {
        asm/matchings/sub_080705D4.o(.text)
    } > ROM
    .rom_gap_091 0x080705DA : {
        asm/rom_gap_091.o(.rodata)
    } > ROM
    .rom_sub_080705DC 0x080705DC : {
        asm/matchings/sub_080705DC.o(.text)
    } > ROM
    .rom_gap_092 0x080705F8 : {
        asm/rom_gap_092.o(.rodata)
    } > ROM
    .rom_sub_0807069C 0x0807069C : {
        asm/matchings/sub_0807069C.o(.text)
    } > ROM
    .rom_gap_093 0x080706B0 : {
        asm/rom_gap_093.o(.rodata)
    } > ROM
    .rom_sub_080717F0 0x080717F0 : {
        asm/matchings/sub_080717F0.o(.text)
    } > ROM
    .rom_sub_08071808 0x08071808 : {
        asm/matchings/sub_08071808.o(.text)
    } > ROM
    .rom_gap_094 0x08071814 : {
        asm/rom_gap_094.o(.rodata)
    } > ROM
    .rom_sub_08071F84 0x08071F84 : {
        asm/matchings/sub_08071F84.o(.text)
    } > ROM
    .rom_sub_08071F98 0x08071F98 : {
        asm/matchings/sub_08071F98.o(.text)
    } > ROM
    .rom_sub_08071FAC 0x08071FAC : {
        asm/matchings/sub_08071FAC.o(.text)
    } > ROM
    .rom_gap_095 0x08071FC6 : {
        asm/rom_gap_095.o(.rodata)
    } > ROM
    .rom_sub_08072CC0 0x08072CC0 : {
        asm/matchings/sub_08072CC0.o(.text)
    } > ROM
    .rom_gap_096 0x08072CD8 : {
        asm/rom_gap_096.o(.rodata)
    } > ROM
    .rom_sub_08072F94 0x08072F94 : {
        asm/matchings/sub_08072F94.o(.text)
    } > ROM
    .rom_gap_097 0x08072FA8 : {
        asm/rom_gap_097.o(.rodata)
    } > ROM
    .rom_sub_08074144 0x08074144 : {
        asm/matchings/sub_08074144.o(.text)
    } > ROM
    .rom_tail 0x08074146 : {
        asm/rom_tail.o(.rodata)
    } > ROM
