    .rom_head 0x08000000 : {
        asm/rom.o(.rodata)
    } > ROM
    .rom_sub_0802B8BC 0x0802B8BC : {
        asm/matchings/sub_0802B8BC.o(.text)
    } > ROM
    .rom_gap_000 0x0802B8D0 : {
        asm/rom_gap_000.o(.rodata)
    } > ROM
    .rom_sub_0802B90C 0x0802B90C : {
        asm/matchings/sub_0802B90C.o(.text)
    } > ROM
    .rom_gap_001 0x0802B918 : {
        asm/rom_gap_001.o(.rodata)
    } > ROM
    .rom_sub_080338E4 0x080338E4 : {
        asm/matchings/sub_080338E4.o(.text)
    } > ROM
    .rom_gap_002 0x080338EE : {
        asm/rom_gap_002.o(.rodata)
    } > ROM
    .rom_sub_08033A94 0x08033A94 : {
        asm/matchings/sub_08033A94.o(.text)
    } > ROM
    .rom_gap_003 0x08033A98 : {
        asm/rom_gap_003.o(.rodata)
    } > ROM
    .rom_sub_080346A8 0x080346A8 : {
        asm/matchings/sub_080346A8.o(.text)
    } > ROM
    .rom_gap_004 0x080346B2 : {
        asm/rom_gap_004.o(.rodata)
    } > ROM
    .rom_sub_08035878 0x08035878 : {
        asm/matchings/sub_08035878.o(.text)
    } > ROM
    .rom_gap_005 0x08035884 : {
        asm/rom_gap_005.o(.rodata)
    } > ROM
    .rom_sub_080358CC 0x080358CC : {
        asm/matchings/sub_080358CC.o(.text)
    } > ROM
    .rom_gap_006 0x080358D6 : {
        asm/rom_gap_006.o(.rodata)
    } > ROM
    .rom_sub_0803EDC8 0x0803EDC8 : {
        asm/matchings/sub_0803EDC8.o(.text)
    } > ROM
    .rom_gap_007 0x0803EDDC : {
        asm/rom_gap_007.o(.rodata)
    } > ROM
    .rom_sub_080400C0 0x080400C0 : {
        asm/matchings/sub_080400C0.o(.text)
    } > ROM
    .rom_gap_008 0x080400D4 : {
        asm/rom_gap_008.o(.rodata)
    } > ROM
    .rom_sub_080429C0 0x080429C0 : {
        asm/matchings/sub_080429C0.o(.text)
    } > ROM
    .rom_gap_009 0x080429CC : {
        asm/rom_gap_009.o(.rodata)
    } > ROM
    .rom_sub_08043974 0x08043974 : {
        asm/matchings/sub_08043974.o(.text)
    } > ROM
    .rom_gap_010 0x08043980 : {
        asm/rom_gap_010.o(.rodata)
    } > ROM
    .rom_sub_080473E4 0x080473E4 : {
        asm/matchings/sub_080473E4.o(.text)
    } > ROM
    .rom_gap_011 0x080473F8 : {
        asm/rom_gap_011.o(.rodata)
    } > ROM
    .rom_sub_08061784 0x08061784 : {
        asm/matchings/sub_08061784.o(.text)
    } > ROM
    .rom_gap_012 0x08061794 : {
        asm/rom_gap_012.o(.rodata)
    } > ROM
    .rom_sub_080617B4 0x080617B4 : {
        asm/matchings/sub_080617B4.o(.text)
    } > ROM
    .rom_gap_013 0x080617C4 : {
        asm/rom_gap_013.o(.rodata)
    } > ROM
    .rom_sub_08061A98 0x08061A98 : {
        asm/matchings/sub_08061A98.o(.text)
    } > ROM
    .rom_sub_08061AA8 0x08061AA8 : {
        asm/matchings/sub_08061AA8.o(.text)
    } > ROM
    .rom_gap_014 0x08061AB8 : {
        asm/rom_gap_014.o(.rodata)
    } > ROM
    .rom_sub_08061BDC 0x08061BDC : {
        asm/matchings/sub_08061BDC.o(.text)
    } > ROM
    .rom_gap_015 0x08061BE8 : {
        asm/rom_gap_015.o(.rodata)
    } > ROM
    .rom_sub_08062098 0x08062098 : {
        asm/matchings/sub_08062098.o(.text)
    } > ROM
    .rom_gap_016 0x0806209C : {
        asm/rom_gap_016.o(.rodata)
    } > ROM
    .rom_sub_08062634 0x08062634 : {
        asm/matchings/sub_08062634.o(.text)
    } > ROM
    .rom_gap_017 0x08062640 : {
        asm/rom_gap_017.o(.rodata)
    } > ROM
    .rom_sub_08062A14 0x08062A14 : {
        asm/matchings/sub_08062A14.o(.text)
    } > ROM
    .rom_sub_08062A1C 0x08062A1C : {
        asm/matchings/sub_08062A1C.o(.text)
    } > ROM
    .rom_gap_018 0x08062A2C : {
        asm/rom_gap_018.o(.rodata)
    } > ROM
    .rom_sub_08066390 0x08066390 : {
        asm/matchings/sub_08066390.o(.text)
    } > ROM
    .rom_gap_019 0x0806639C : {
        asm/rom_gap_019.o(.rodata)
    } > ROM
    .rom_sub_08066434 0x08066434 : {
        asm/matchings/sub_08066434.o(.text)
    } > ROM
    .rom_sub_08066440 0x08066440 : {
        asm/matchings/sub_08066440.o(.text)
    } > ROM
    .rom_sub_0806644C 0x0806644C : {
        asm/matchings/sub_0806644C.o(.text)
    } > ROM
    .rom_gap_020 0x0806645C : {
        asm/rom_gap_020.o(.rodata)
    } > ROM
    .rom_sub_080674A0 0x080674A0 : {
        asm/matchings/sub_080674A0.o(.text)
    } > ROM
    .rom_sub_080674A4 0x080674A4 : {
        asm/matchings/sub_080674A4.o(.text)
    } > ROM
    .rom_gap_021 0x080674AA : {
        asm/rom_gap_021.o(.rodata)
    } > ROM
    .rom_sub_080674AC 0x080674AC : {
        asm/matchings/sub_080674AC.o(.text)
    } > ROM
    .rom_sub_080674B0 0x080674B0 : {
        asm/matchings/sub_080674B0.o(.text)
    } > ROM
    .rom_sub_080674B4 0x080674B4 : {
        asm/matchings/sub_080674B4.o(.text)
    } > ROM
    .rom_gap_022 0x080674BA : {
        asm/rom_gap_022.o(.rodata)
    } > ROM
    .rom_sub_08067A9C 0x08067A9C : {
        asm/matchings/sub_08067A9C.o(.text)
    } > ROM
    .rom_gap_023 0x08067A9E : {
        asm/rom_gap_023.o(.rodata)
    } > ROM
    .rom_sub_08067B98 0x08067B98 : {
        asm/matchings/sub_08067B98.o(.text)
    } > ROM
    .rom_gap_024 0x08067B9E : {
        asm/rom_gap_024.o(.rodata)
    } > ROM
    .rom_sub_08068014 0x08068014 : {
        asm/matchings/sub_08068014.o(.text)
    } > ROM
    .rom_gap_025 0x0806801E : {
        asm/rom_gap_025.o(.rodata)
    } > ROM
    .rom_sub_08068584 0x08068584 : {
        asm/matchings/sub_08068584.o(.text)
    } > ROM
    .rom_gap_026 0x08068590 : {
        asm/rom_gap_026.o(.rodata)
    } > ROM
    .rom_sub_0806B5B8 0x0806B5B8 : {
        asm/matchings/sub_0806B5B8.o(.text)
    } > ROM
    .rom_gap_027 0x0806B5C8 : {
        asm/rom_gap_027.o(.rodata)
    } > ROM
    .rom_sub_0806EEC4 0x0806EEC4 : {
        asm/matchings/sub_0806EEC4.o(.text)
    } > ROM
    .rom_gap_028 0x0806EEC6 : {
        asm/rom_gap_028.o(.rodata)
    } > ROM
    .rom_sub_080705CC 0x080705CC : {
        asm/matchings/sub_080705CC.o(.text)
    } > ROM
    .rom_gap_029 0x080705D2 : {
        asm/rom_gap_029.o(.rodata)
    } > ROM
    .rom_sub_080705D4 0x080705D4 : {
        asm/matchings/sub_080705D4.o(.text)
    } > ROM
    .rom_gap_030 0x080705DA : {
        asm/rom_gap_030.o(.rodata)
    } > ROM
    .rom_sub_08071808 0x08071808 : {
        asm/matchings/sub_08071808.o(.text)
    } > ROM
    .rom_gap_031 0x08071814 : {
        asm/rom_gap_031.o(.rodata)
    } > ROM
    .rom_sub_08072F94 0x08072F94 : {
        asm/matchings/sub_08072F94.o(.text)
    } > ROM
    .rom_gap_032 0x08072FA8 : {
        asm/rom_gap_032.o(.rodata)
    } > ROM
    .rom_sub_08074144 0x08074144 : {
        asm/matchings/sub_08074144.o(.text)
    } > ROM
    .rom_tail 0x08074146 : {
        asm/rom_tail.o(.rodata)
    } > ROM
