    .rom_head 0x08000000 : {
        asm/rom.o(.rodata)
    } > ROM
    .rom_sub_0802B8BC 0x0802B8BC : {
        asm/matchings/sub_0802B8BC.o(.text)
    } > ROM
    .rom_gap_002B8D0 0x0802B8D0 : {
        asm/rom_gap_002B8D0.o(.rodata)
    } > ROM
    .rom_sub_0802B90C 0x0802B90C : {
        asm/matchings/sub_0802B90C.o(.text)
    } > ROM
    .rom_gap_002B918 0x0802B918 : {
        asm/rom_gap_002B918.o(.rodata)
    } > ROM
    .rom_sub_0802B930 0x0802B930 : {
        asm/matchings/sub_0802B930.o(.text)
    } > ROM
    .rom_gap_002B95A 0x0802B95A : {
        asm/rom_gap_002B95A.o(.rodata)
    } > ROM
    .rom_sub_0802B95C 0x0802B95C : {
        asm/matchings/sub_0802B95C.o(.text)
    } > ROM
    .rom_sub_0802B994 0x0802B994 : {
        asm/matchings/sub_0802B994.o(.text)
    } > ROM
    .rom_gap_002B9CE 0x0802B9CE : {
        asm/rom_gap_002B9CE.o(.rodata)
    } > ROM
    .rom_sub_0802BA4C 0x0802BA4C : {
        asm/matchings/sub_0802BA4C.o(.text)
    } > ROM
    .rom_gap_002BA7C 0x0802BA7C : {
        asm/rom_gap_002BA7C.o(.rodata)
    } > ROM
    .rom_sub_0802BAD4 0x0802BAD4 : {
        asm/matchings/sub_0802BAD4.o(.text)
    } > ROM
    .rom_sub_0802BC14 0x0802BC14 : {
        asm/matchings/sub_0802BC14.o(.text)
    } > ROM
    .rom_gap_002BC84 0x0802BC84 : {
        asm/rom_gap_002BC84.o(.rodata)
    } > ROM
    .rom_sub_0802BF04 0x0802BF04 : {
        asm/matchings/sub_0802BF04.o(.text)
    } > ROM
    .rom_gap_002BF90 0x0802BF90 : {
        asm/rom_gap_002BF90.o(.rodata)
    } > ROM
    .rom_sub_0802C2B0 0x0802C2B0 : {
        asm/matchings/sub_0802C2B0.o(.text)
    } > ROM
    .rom_sub_0802C314 0x0802C314 : {
        asm/matchings/sub_0802C314.o(.text)
    } > ROM
    .rom_gap_002C3DA 0x0802C3DA : {
        asm/rom_gap_002C3DA.o(.rodata)
    } > ROM
    .rom_sub_0802C3DC 0x0802C3DC : {
        asm/matchings/sub_0802C3DC.o(.text)
    } > ROM
    .rom_gap_002C4A2 0x0802C4A2 : {
        asm/rom_gap_002C4A2.o(.rodata)
    } > ROM
    .rom_sub_0802C4A4 0x0802C4A4 : {
        asm/matchings/sub_0802C4A4.o(.text)
    } > ROM
    .rom_gap_002C55A 0x0802C55A : {
        asm/rom_gap_002C55A.o(.rodata)
    } > ROM
    .rom_sub_0802C55C 0x0802C55C : {
        asm/matchings/sub_0802C55C.o(.text)
    } > ROM
    .rom_sub_0802C5DC 0x0802C5DC : {
        asm/matchings/sub_0802C5DC.o(.text)
    } > ROM
    .rom_gap_002C62A 0x0802C62A : {
        asm/rom_gap_002C62A.o(.rodata)
    } > ROM
    .rom_sub_0802C62C 0x0802C62C : {
        asm/matchings/sub_0802C62C.o(.text)
    } > ROM
    .rom_gap_002C66C 0x0802C66C : {
        asm/rom_gap_002C66C.o(.rodata)
    } > ROM
    .rom_sub_0802C6AC 0x0802C6AC : {
        asm/matchings/sub_0802C6AC.o(.text)
    } > ROM
    .rom_gap_002C70C 0x0802C70C : {
        asm/rom_gap_002C70C.o(.rodata)
    } > ROM
    .rom_sub_0802D2C0 0x0802D2C0 : {
        asm/matchings/sub_0802D2C0.o(.text)
    } > ROM
    .rom_gap_002D32C 0x0802D32C : {
        asm/rom_gap_002D32C.o(.rodata)
    } > ROM
    .rom_sub_0802D3F0 0x0802D3F0 : {
        asm/matchings/sub_0802D3F0.o(.text)
    } > ROM
    .rom_sub_0802D52C 0x0802D52C : {
        asm/matchings/sub_0802D52C.o(.text)
    } > ROM
    .rom_sub_0802D598 0x0802D598 : {
        asm/matchings/sub_0802D598.o(.text)
    } > ROM
    .rom_gap_002D5B4 0x0802D5B4 : {
        asm/rom_gap_002D5B4.o(.rodata)
    } > ROM
    .rom_sub_0802D6D4 0x0802D6D4 : {
        asm/matchings/sub_0802D6D4.o(.text)
    } > ROM
    .rom_sub_0802D898 0x0802D898 : {
        asm/matchings/sub_0802D898.o(.text)
    } > ROM
    .rom_sub_0802D8C4 0x0802D8C4 : {
        asm/matchings/sub_0802D8C4.o(.text)
    } > ROM
    .rom_sub_0802D8DC 0x0802D8DC : {
        asm/matchings/sub_0802D8DC.o(.text)
    } > ROM
    .rom_gap_002D9A8 0x0802D9A8 : {
        asm/rom_gap_002D9A8.o(.rodata)
    } > ROM
    .rom_sub_0802DCDC 0x0802DCDC : {
        asm/matchings/sub_0802DCDC.o(.text)
    } > ROM
    .rom_sub_0802DEA0 0x0802DEA0 : {
        asm/matchings/sub_0802DEA0.o(.text)
    } > ROM
    .rom_sub_0802E048 0x0802E048 : {
        asm/matchings/sub_0802E048.o(.text)
    } > ROM
    .rom_gap_002E12C 0x0802E12C : {
        asm/rom_gap_002E12C.o(.rodata)
    } > ROM
    .rom_sub_0802E18C 0x0802E18C : {
        asm/matchings/sub_0802E18C.o(.text)
    } > ROM
    .rom_gap_002E1B2 0x0802E1B2 : {
        asm/rom_gap_002E1B2.o(.rodata)
    } > ROM
    .rom_sub_0802E1B4 0x0802E1B4 : {
        asm/matchings/sub_0802E1B4.o(.text)
    } > ROM
    .rom_sub_0802E1EC 0x0802E1EC : {
        asm/matchings/sub_0802E1EC.o(.text)
    } > ROM
    .rom_sub_0802E210 0x0802E210 : {
        asm/matchings/sub_0802E210.o(.text)
    } > ROM
    .rom_gap_002E234 0x0802E234 : {
        asm/rom_gap_002E234.o(.rodata)
    } > ROM
    .rom_sub_0802E2F8 0x0802E2F8 : {
        asm/matchings/sub_0802E2F8.o(.text)
    } > ROM
    .rom_gap_002E366 0x0802E366 : {
        asm/rom_gap_002E366.o(.rodata)
    } > ROM
    .rom_sub_0802ECD8 0x0802ECD8 : {
        asm/matchings/sub_0802ECD8.o(.text)
    } > ROM
    .rom_gap_002EECA 0x0802EECA : {
        asm/rom_gap_002EECA.o(.rodata)
    } > ROM
    .rom_sub_0802EECC 0x0802EECC : {
        asm/matchings/sub_0802EECC.o(.text)
    } > ROM
    .rom_gap_002EEEC 0x0802EEEC : {
        asm/rom_gap_002EEEC.o(.rodata)
    } > ROM
    .rom_sub_0802F520 0x0802F520 : {
        asm/matchings/sub_0802F520.o(.text)
    } > ROM
    .rom_gap_002F57C 0x0802F57C : {
        asm/rom_gap_002F57C.o(.rodata)
    } > ROM
    .rom_sub_0802FA94 0x0802FA94 : {
        asm/matchings/sub_0802FA94.o(.text)
    } > ROM
    .rom_sub_0802FD80 0x0802FD80 : {
        asm/matchings/sub_0802FD80.o(.text)
    } > ROM
    .rom_gap_002FDA0 0x0802FDA0 : {
        asm/rom_gap_002FDA0.o(.rodata)
    } > ROM
    .rom_sub_0803019C 0x0803019C : {
        asm/matchings/sub_0803019C.o(.text)
    } > ROM
    .rom_sub_080302A8 0x080302A8 : {
        asm/matchings/sub_080302A8.o(.text)
    } > ROM
    .rom_gap_00302DE 0x080302DE : {
        asm/rom_gap_00302DE.o(.rodata)
    } > ROM
    .rom_sub_080302E0 0x080302E0 : {
        asm/matchings/sub_080302E0.o(.text)
    } > ROM
    .rom_gap_0030388 0x08030388 : {
        asm/rom_gap_0030388.o(.rodata)
    } > ROM
    .rom_sub_08030638 0x08030638 : {
        asm/matchings/sub_08030638.o(.text)
    } > ROM
    .rom_gap_0030744 0x08030744 : {
        asm/rom_gap_0030744.o(.rodata)
    } > ROM
    .rom_sub_08030938 0x08030938 : {
        asm/matchings/sub_08030938.o(.text)
    } > ROM
    .rom_gap_0030986 0x08030986 : {
        asm/rom_gap_0030986.o(.rodata)
    } > ROM
    .rom_sub_08030D4C 0x08030D4C : {
        asm/matchings/sub_08030D4C.o(.text)
    } > ROM
    .rom_sub_08030F00 0x08030F00 : {
        asm/matchings/sub_08030F00.o(.text)
    } > ROM
    .rom_sub_08030F38 0x08030F38 : {
        asm/matchings/sub_08030F38.o(.text)
    } > ROM
    .rom_sub_08031094 0x08031094 : {
        asm/matchings/sub_08031094.o(.text)
    } > ROM
    .rom_sub_080310F0 0x080310F0 : {
        asm/matchings/sub_080310F0.o(.text)
    } > ROM
    .rom_sub_08031124 0x08031124 : {
        asm/matchings/sub_08031124.o(.text)
    } > ROM
    .rom_gap_003114A 0x0803114A : {
        asm/rom_gap_003114A.o(.rodata)
    } > ROM
    .rom_sub_0803114C 0x0803114C : {
        asm/matchings/sub_0803114C.o(.text)
    } > ROM
    .rom_sub_08031204 0x08031204 : {
        asm/matchings/sub_08031204.o(.text)
    } > ROM
    .rom_sub_08031294 0x08031294 : {
        asm/matchings/sub_08031294.o(.text)
    } > ROM
    .rom_sub_080312B0 0x080312B0 : {
        asm/matchings/sub_080312B0.o(.text)
    } > ROM
    .rom_sub_080312D8 0x080312D8 : {
        asm/matchings/sub_080312D8.o(.text)
    } > ROM
    .rom_sub_080312EC 0x080312EC : {
        asm/matchings/sub_080312EC.o(.text)
    } > ROM
    .rom_sub_08031300 0x08031300 : {
        asm/matchings/sub_08031300.o(.text)
    } > ROM
    .rom_gap_003134E 0x0803134E : {
        asm/rom_gap_003134E.o(.rodata)
    } > ROM
    .rom_sub_08031368 0x08031368 : {
        asm/matchings/sub_08031368.o(.text)
    } > ROM
    .rom_gap_003139A 0x0803139A : {
        asm/rom_gap_003139A.o(.rodata)
    } > ROM
    .rom_sub_0803139C 0x0803139C : {
        asm/matchings/sub_0803139C.o(.text)
    } > ROM
    .rom_gap_00314FA 0x080314FA : {
        asm/rom_gap_00314FA.o(.rodata)
    } > ROM
    .rom_sub_080314FC 0x080314FC : {
        asm/matchings/sub_080314FC.o(.text)
    } > ROM
    .rom_gap_0031510 0x08031510 : {
        asm/rom_gap_0031510.o(.rodata)
    } > ROM
    .rom_sub_08031C98 0x08031C98 : {
        asm/matchings/sub_08031C98.o(.text)
    } > ROM
    .rom_gap_0031D2E 0x08031D2E : {
        asm/rom_gap_0031D2E.o(.rodata)
    } > ROM
    .rom_sub_080320CC 0x080320CC : {
        asm/matchings/sub_080320CC.o(.text)
    } > ROM
    .rom_gap_0032100 0x08032100 : {
        asm/rom_gap_0032100.o(.rodata)
    } > ROM
    .rom_sub_08032604 0x08032604 : {
        asm/matchings/sub_08032604.o(.text)
    } > ROM
    .rom_gap_00326C8 0x080326C8 : {
        asm/rom_gap_00326C8.o(.rodata)
    } > ROM
    .rom_sub_08032908 0x08032908 : {
        asm/matchings/sub_08032908.o(.text)
    } > ROM
    .rom_gap_0032A88 0x08032A88 : {
        asm/rom_gap_0032A88.o(.rodata)
    } > ROM
    .rom_sub_08032D5C 0x08032D5C : {
        asm/matchings/sub_08032D5C.o(.text)
    } > ROM
    .rom_gap_0032DB6 0x08032DB6 : {
        asm/rom_gap_0032DB6.o(.rodata)
    } > ROM
    .rom_sub_08032DB8 0x08032DB8 : {
        asm/matchings/sub_08032DB8.o(.text)
    } > ROM
    .rom_sub_08032DC4 0x08032DC4 : {
        asm/matchings/sub_08032DC4.o(.text)
    } > ROM
    .rom_gap_0033058 0x08033058 : {
        asm/rom_gap_0033058.o(.rodata)
    } > ROM
    .rom_sub_08033084 0x08033084 : {
        asm/matchings/sub_08033084.o(.text)
    } > ROM
    .rom_gap_00330E8 0x080330E8 : {
        asm/rom_gap_00330E8.o(.rodata)
    } > ROM
    .rom_sub_080330F4 0x080330F4 : {
        asm/matchings/sub_080330F4.o(.text)
    } > ROM
    .rom_gap_003313C 0x0803313C : {
        asm/rom_gap_003313C.o(.rodata)
    } > ROM
    .rom_sub_08033158 0x08033158 : {
        asm/matchings/sub_08033158.o(.text)
    } > ROM
    .rom_gap_0033186 0x08033186 : {
        asm/rom_gap_0033186.o(.rodata)
    } > ROM
    .rom_sub_08033188 0x08033188 : {
        asm/matchings/sub_08033188.o(.text)
    } > ROM
    .rom_sub_080333E4 0x080333E4 : {
        asm/matchings/sub_080333E4.o(.text)
    } > ROM
    .rom_gap_00334F4 0x080334F4 : {
        asm/rom_gap_00334F4.o(.rodata)
    } > ROM
    .rom_sub_08033530 0x08033530 : {
        asm/matchings/sub_08033530.o(.text)
    } > ROM
    .rom_sub_08033574 0x08033574 : {
        asm/matchings/sub_08033574.o(.text)
    } > ROM
    .rom_gap_00335C4 0x080335C4 : {
        asm/rom_gap_00335C4.o(.rodata)
    } > ROM
    .rom_sub_0803370C 0x0803370C : {
        asm/matchings/sub_0803370C.o(.text)
    } > ROM
    .rom_gap_0033876 0x08033876 : {
        asm/rom_gap_0033876.o(.rodata)
    } > ROM
    .rom_sub_08033878 0x08033878 : {
        asm/matchings/sub_08033878.o(.text)
    } > ROM
    .rom_sub_080338E4 0x080338E4 : {
        asm/matchings/sub_080338E4.o(.text)
    } > ROM
    .rom_gap_00338EE 0x080338EE : {
        asm/rom_gap_00338EE.o(.rodata)
    } > ROM
    .rom_sub_080338F0 0x080338F0 : {
        asm/matchings/sub_080338F0.o(.text)
    } > ROM
    .rom_sub_08033958 0x08033958 : {
        asm/matchings/sub_08033958.o(.text)
    } > ROM
    .rom_gap_003396C 0x0803396C : {
        asm/rom_gap_003396C.o(.rodata)
    } > ROM
    .rom_sub_08033978 0x08033978 : {
        asm/matchings/sub_08033978.o(.text)
    } > ROM
    .rom_gap_0033A2C 0x08033A2C : {
        asm/rom_gap_0033A2C.o(.rodata)
    } > ROM
    .rom_sub_08033A5C 0x08033A5C : {
        asm/matchings/sub_08033A5C.o(.text)
    } > ROM
    .rom_sub_08033A94 0x08033A94 : {
        asm/matchings/sub_08033A94.o(.text)
    } > ROM
    .rom_gap_0033A98 0x08033A98 : {
        asm/rom_gap_0033A98.o(.rodata)
    } > ROM
    .rom_sub_08033C1C 0x08033C1C : {
        asm/matchings/sub_08033C1C.o(.text)
    } > ROM
    .rom_gap_0033C3C 0x08033C3C : {
        asm/rom_gap_0033C3C.o(.rodata)
    } > ROM
    .rom_sub_08033D90 0x08033D90 : {
        asm/matchings/sub_08033D90.o(.text)
    } > ROM
    .rom_gap_0033DD2 0x08033DD2 : {
        asm/rom_gap_0033DD2.o(.rodata)
    } > ROM
    .rom_sub_08033DD4 0x08033DD4 : {
        asm/matchings/sub_08033DD4.o(.text)
    } > ROM
    .rom_sub_08033E3C 0x08033E3C : {
        asm/matchings/sub_08033E3C.o(.text)
    } > ROM
    .rom_gap_0033E5A 0x08033E5A : {
        asm/rom_gap_0033E5A.o(.rodata)
    } > ROM
    .rom_sub_08033EA4 0x08033EA4 : {
        asm/matchings/sub_08033EA4.o(.text)
    } > ROM
    .rom_gap_0033EE2 0x08033EE2 : {
        asm/rom_gap_0033EE2.o(.rodata)
    } > ROM
    .rom_sub_08033F24 0x08033F24 : {
        asm/matchings/sub_08033F24.o(.text)
    } > ROM
    .rom_gap_0033F2E 0x08033F2E : {
        asm/rom_gap_0033F2E.o(.rodata)
    } > ROM
    .rom_sub_08033F30 0x08033F30 : {
        asm/matchings/sub_08033F30.o(.text)
    } > ROM
    .rom_sub_08033F48 0x08033F48 : {
        asm/matchings/sub_08033F48.o(.text)
    } > ROM
    .rom_gap_0033F7E 0x08033F7E : {
        asm/rom_gap_0033F7E.o(.rodata)
    } > ROM
    .rom_sub_0803403C 0x0803403C : {
        asm/matchings/sub_0803403C.o(.text)
    } > ROM
    .rom_gap_0034074 0x08034074 : {
        asm/rom_gap_0034074.o(.rodata)
    } > ROM
    .rom_sub_0803413C 0x0803413C : {
        asm/matchings/sub_0803413C.o(.text)
    } > ROM
    .rom_gap_003417C 0x0803417C : {
        asm/rom_gap_003417C.o(.rodata)
    } > ROM
    .rom_sub_08034360 0x08034360 : {
        asm/matchings/sub_08034360.o(.text)
    } > ROM
    .rom_gap_003437E 0x0803437E : {
        asm/rom_gap_003437E.o(.rodata)
    } > ROM
    .rom_sub_08034414 0x08034414 : {
        asm/matchings/sub_08034414.o(.text)
    } > ROM
    .rom_gap_003441E 0x0803441E : {
        asm/rom_gap_003441E.o(.rodata)
    } > ROM
    .rom_sub_08034420 0x08034420 : {
        asm/matchings/sub_08034420.o(.text)
    } > ROM
    .rom_sub_08034568 0x08034568 : {
        asm/matchings/sub_08034568.o(.text)
    } > ROM
    .rom_sub_08034618 0x08034618 : {
        asm/matchings/sub_08034618.o(.text)
    } > ROM
    .rom_gap_00346A6 0x080346A6 : {
        asm/rom_gap_00346A6.o(.rodata)
    } > ROM
    .rom_sub_080346A8 0x080346A8 : {
        asm/matchings/sub_080346A8.o(.text)
    } > ROM
    .rom_gap_00346B2 0x080346B2 : {
        asm/rom_gap_00346B2.o(.rodata)
    } > ROM
    .rom_sub_080346C0 0x080346C0 : {
        asm/matchings/sub_080346C0.o(.text)
    } > ROM
    .rom_gap_00346DA 0x080346DA : {
        asm/rom_gap_00346DA.o(.rodata)
    } > ROM
    .rom_sub_08034788 0x08034788 : {
        asm/matchings/sub_08034788.o(.text)
    } > ROM
    .rom_gap_00347B4 0x080347B4 : {
        asm/rom_gap_00347B4.o(.rodata)
    } > ROM
    .rom_sub_080347E4 0x080347E4 : {
        asm/matchings/sub_080347E4.o(.text)
    } > ROM
    .rom_sub_08034810 0x08034810 : {
        asm/matchings/sub_08034810.o(.text)
    } > ROM
    .rom_sub_0803484C 0x0803484C : {
        asm/matchings/sub_0803484C.o(.text)
    } > ROM
    .rom_gap_0034868 0x08034868 : {
        asm/rom_gap_0034868.o(.rodata)
    } > ROM
    .rom_sub_08034894 0x08034894 : {
        asm/matchings/sub_08034894.o(.text)
    } > ROM
    .rom_sub_080348E8 0x080348E8 : {
        asm/matchings/sub_080348E8.o(.text)
    } > ROM
    .rom_sub_08034A68 0x08034A68 : {
        asm/matchings/sub_08034A68.o(.text)
    } > ROM
    .rom_gap_0034AD8 0x08034AD8 : {
        asm/rom_gap_0034AD8.o(.rodata)
    } > ROM
    .rom_sub_08034FBC 0x08034FBC : {
        asm/matchings/sub_08034FBC.o(.text)
    } > ROM
    .rom_gap_0034FDA 0x08034FDA : {
        asm/rom_gap_0034FDA.o(.rodata)
    } > ROM
    .rom_sub_08034FDC 0x08034FDC : {
        asm/matchings/sub_08034FDC.o(.text)
    } > ROM
    .rom_sub_08034FF8 0x08034FF8 : {
        asm/matchings/sub_08034FF8.o(.text)
    } > ROM
    .rom_gap_0035014 0x08035014 : {
        asm/rom_gap_0035014.o(.rodata)
    } > ROM
    .rom_sub_08035020 0x08035020 : {
        asm/matchings/sub_08035020.o(.text)
    } > ROM
    .rom_sub_08035054 0x08035054 : {
        asm/matchings/sub_08035054.o(.text)
    } > ROM
    .rom_sub_08035204 0x08035204 : {
        asm/matchings/sub_08035204.o(.text)
    } > ROM
    .rom_gap_0035236 0x08035236 : {
        asm/rom_gap_0035236.o(.rodata)
    } > ROM
    .rom_sub_08035238 0x08035238 : {
        asm/matchings/sub_08035238.o(.text)
    } > ROM
    .rom_sub_08035258 0x08035258 : {
        asm/matchings/sub_08035258.o(.text)
    } > ROM
    .rom_sub_0803531C 0x0803531C : {
        asm/matchings/sub_0803531C.o(.text)
    } > ROM
    .rom_sub_080353A0 0x080353A0 : {
        asm/matchings/sub_080353A0.o(.text)
    } > ROM
    .rom_sub_08035468 0x08035468 : {
        asm/matchings/sub_08035468.o(.text)
    } > ROM
    .rom_sub_0803559C 0x0803559C : {
        asm/matchings/sub_0803559C.o(.text)
    } > ROM
    .rom_gap_0035608 0x08035608 : {
        asm/rom_gap_0035608.o(.rodata)
    } > ROM
    .rom_sub_08035624 0x08035624 : {
        asm/matchings/sub_08035624.o(.text)
    } > ROM
    .rom_gap_0035696 0x08035696 : {
        asm/rom_gap_0035696.o(.rodata)
    } > ROM
    .rom_sub_08035878 0x08035878 : {
        asm/matchings/sub_08035878.o(.text)
    } > ROM
    .rom_sub_08035884 0x08035884 : {
        asm/matchings/sub_08035884.o(.text)
    } > ROM
    .rom_sub_080358CC 0x080358CC : {
        asm/matchings/sub_080358CC.o(.text)
    } > ROM
    .rom_gap_00358D6 0x080358D6 : {
        asm/rom_gap_00358D6.o(.rodata)
    } > ROM
    .rom_sub_08035908 0x08035908 : {
        asm/matchings/sub_08035908.o(.text)
    } > ROM
    .rom_gap_003592C 0x0803592C : {
        asm/rom_gap_003592C.o(.rodata)
    } > ROM
    .rom_sub_0803593C 0x0803593C : {
        asm/matchings/sub_0803593C.o(.text)
    } > ROM
    .rom_sub_08035984 0x08035984 : {
        asm/matchings/sub_08035984.o(.text)
    } > ROM
    .rom_sub_08035AE0 0x08035AE0 : {
        asm/matchings/sub_08035AE0.o(.text)
    } > ROM
    .rom_sub_08035C64 0x08035C64 : {
        asm/matchings/sub_08035C64.o(.text)
    } > ROM
    .rom_gap_0035D1A 0x08035D1A : {
        asm/rom_gap_0035D1A.o(.rodata)
    } > ROM
    .rom_sub_08035D1C 0x08035D1C : {
        asm/matchings/sub_08035D1C.o(.text)
    } > ROM
    .rom_sub_08035D68 0x08035D68 : {
        asm/matchings/sub_08035D68.o(.text)
    } > ROM
    .rom_gap_0035E2C 0x08035E2C : {
        asm/rom_gap_0035E2C.o(.rodata)
    } > ROM
    .rom_sub_080360BC 0x080360BC : {
        asm/matchings/sub_080360BC.o(.text)
    } > ROM
    .rom_gap_0036124 0x08036124 : {
        asm/rom_gap_0036124.o(.rodata)
    } > ROM
    .rom_sub_08036190 0x08036190 : {
        asm/matchings/sub_08036190.o(.text)
    } > ROM
    .rom_sub_080361A8 0x080361A8 : {
        asm/matchings/sub_080361A8.o(.text)
    } > ROM
    .rom_sub_080361CC 0x080361CC : {
        asm/matchings/sub_080361CC.o(.text)
    } > ROM
    .rom_gap_00361F8 0x080361F8 : {
        asm/rom_gap_00361F8.o(.rodata)
    } > ROM
    .rom_sub_08036264 0x08036264 : {
        asm/matchings/sub_08036264.o(.text)
    } > ROM
    .rom_gap_00362D4 0x080362D4 : {
        asm/rom_gap_00362D4.o(.rodata)
    } > ROM
    .rom_sub_08036A68 0x08036A68 : {
        asm/matchings/sub_08036A68.o(.text)
    } > ROM
    .rom_gap_0036B58 0x08036B58 : {
        asm/rom_gap_0036B58.o(.rodata)
    } > ROM
    .rom_sub_0803715C 0x0803715C : {
        asm/matchings/sub_0803715C.o(.text)
    } > ROM
    .rom_sub_08037318 0x08037318 : {
        asm/matchings/sub_08037318.o(.text)
    } > ROM
    .rom_gap_003737C 0x0803737C : {
        asm/rom_gap_003737C.o(.rodata)
    } > ROM
    .rom_sub_08037430 0x08037430 : {
        asm/matchings/sub_08037430.o(.text)
    } > ROM
    .rom_sub_08037508 0x08037508 : {
        asm/matchings/sub_08037508.o(.text)
    } > ROM
    .rom_gap_00376CC 0x080376CC : {
        asm/rom_gap_00376CC.o(.rodata)
    } > ROM
    .rom_sub_08038314 0x08038314 : {
        asm/matchings/sub_08038314.o(.text)
    } > ROM
    .rom_gap_0038380 0x08038380 : {
        asm/rom_gap_0038380.o(.rodata)
    } > ROM
    .rom_sub_08038438 0x08038438 : {
        asm/matchings/sub_08038438.o(.text)
    } > ROM
    .rom_gap_0038528 0x08038528 : {
        asm/rom_gap_0038528.o(.rodata)
    } > ROM
    .rom_sub_08038580 0x08038580 : {
        asm/matchings/sub_08038580.o(.text)
    } > ROM
    .rom_sub_080385DC 0x080385DC : {
        asm/matchings/sub_080385DC.o(.text)
    } > ROM
    .rom_gap_003862C 0x0803862C : {
        asm/rom_gap_003862C.o(.rodata)
    } > ROM
    .rom_sub_08038638 0x08038638 : {
        asm/matchings/sub_08038638.o(.text)
    } > ROM
    .rom_gap_0038678 0x08038678 : {
        asm/rom_gap_0038678.o(.rodata)
    } > ROM
    .rom_sub_08038D10 0x08038D10 : {
        asm/matchings/sub_08038D10.o(.text)
    } > ROM
    .rom_gap_0038D66 0x08038D66 : {
        asm/rom_gap_0038D66.o(.rodata)
    } > ROM
    .rom_sub_08038D68 0x08038D68 : {
        asm/matchings/sub_08038D68.o(.text)
    } > ROM
    .rom_gap_0038DD8 0x08038DD8 : {
        asm/rom_gap_0038DD8.o(.rodata)
    } > ROM
    .rom_sub_08038F30 0x08038F30 : {
        asm/matchings/sub_08038F30.o(.text)
    } > ROM
    .rom_gap_003906C 0x0803906C : {
        asm/rom_gap_003906C.o(.rodata)
    } > ROM
    .rom_sub_080392D0 0x080392D0 : {
        asm/matchings/sub_080392D0.o(.text)
    } > ROM
    .rom_gap_0039344 0x08039344 : {
        asm/rom_gap_0039344.o(.rodata)
    } > ROM
    .rom_sub_08039BD4 0x08039BD4 : {
        asm/matchings/sub_08039BD4.o(.text)
    } > ROM
    .rom_sub_0803A1E4 0x0803A1E4 : {
        asm/matchings/sub_0803A1E4.o(.text)
    } > ROM
    .rom_gap_003A20C 0x0803A20C : {
        asm/rom_gap_003A20C.o(.rodata)
    } > ROM
    .rom_sub_0803B078 0x0803B078 : {
        asm/matchings/sub_0803B078.o(.text)
    } > ROM
    .rom_gap_003B144 0x0803B144 : {
        asm/rom_gap_003B144.o(.rodata)
    } > ROM
    .rom_sub_0803C500 0x0803C500 : {
        asm/matchings/sub_0803C500.o(.text)
    } > ROM
    .rom_sub_0803C5DC 0x0803C5DC : {
        asm/matchings/sub_0803C5DC.o(.text)
    } > ROM
    .rom_sub_0803C6B8 0x0803C6B8 : {
        asm/matchings/sub_0803C6B8.o(.text)
    } > ROM
    .rom_gap_003C6E4 0x0803C6E4 : {
        asm/rom_gap_003C6E4.o(.rodata)
    } > ROM
    .rom_sub_0803D284 0x0803D284 : {
        asm/matchings/sub_0803D284.o(.text)
    } > ROM
    .rom_gap_003D3AE 0x0803D3AE : {
        asm/rom_gap_003D3AE.o(.rodata)
    } > ROM
    .rom_sub_0803D4C4 0x0803D4C4 : {
        asm/matchings/sub_0803D4C4.o(.text)
    } > ROM
    .rom_sub_0803D51C 0x0803D51C : {
        asm/matchings/sub_0803D51C.o(.text)
    } > ROM
    .rom_gap_003D64C 0x0803D64C : {
        asm/rom_gap_003D64C.o(.rodata)
    } > ROM
    .rom_sub_0803DBD0 0x0803DBD0 : {
        asm/matchings/sub_0803DBD0.o(.text)
    } > ROM
    .rom_gap_003DC20 0x0803DC20 : {
        asm/rom_gap_003DC20.o(.rodata)
    } > ROM
    .rom_sub_0803DCFC 0x0803DCFC : {
        asm/matchings/sub_0803DCFC.o(.text)
    } > ROM
    .rom_gap_003DD2C 0x0803DD2C : {
        asm/rom_gap_003DD2C.o(.rodata)
    } > ROM
    .rom_sub_0803DD60 0x0803DD60 : {
        asm/matchings/sub_0803DD60.o(.text)
    } > ROM
    .rom_sub_0803DD88 0x0803DD88 : {
        asm/matchings/sub_0803DD88.o(.text)
    } > ROM
    .rom_sub_0803DDB0 0x0803DDB0 : {
        asm/matchings/sub_0803DDB0.o(.text)
    } > ROM
    .rom_sub_0803DDD8 0x0803DDD8 : {
        asm/matchings/sub_0803DDD8.o(.text)
    } > ROM
    .rom_gap_003DE00 0x0803DE00 : {
        asm/rom_gap_003DE00.o(.rodata)
    } > ROM
    .rom_sub_0803DEC8 0x0803DEC8 : {
        asm/matchings/sub_0803DEC8.o(.text)
    } > ROM
    .rom_gap_003E0CA 0x0803E0CA : {
        asm/rom_gap_003E0CA.o(.rodata)
    } > ROM
    .rom_sub_0803E0CC 0x0803E0CC : {
        asm/matchings/sub_0803E0CC.o(.text)
    } > ROM
    .rom_sub_0803E1F4 0x0803E1F4 : {
        asm/matchings/sub_0803E1F4.o(.text)
    } > ROM
    .rom_gap_003E256 0x0803E256 : {
        asm/rom_gap_003E256.o(.rodata)
    } > ROM
    .rom_sub_0803E258 0x0803E258 : {
        asm/matchings/sub_0803E258.o(.text)
    } > ROM
    .rom_gap_003E2AA 0x0803E2AA : {
        asm/rom_gap_003E2AA.o(.rodata)
    } > ROM
    .rom_sub_0803E2AC 0x0803E2AC : {
        asm/matchings/sub_0803E2AC.o(.text)
    } > ROM
    .rom_sub_0803E328 0x0803E328 : {
        asm/matchings/sub_0803E328.o(.text)
    } > ROM
    .rom_sub_0803E374 0x0803E374 : {
        asm/matchings/sub_0803E374.o(.text)
    } > ROM
    .rom_sub_0803E3C0 0x0803E3C0 : {
        asm/matchings/sub_0803E3C0.o(.text)
    } > ROM
    .rom_gap_003E40C 0x0803E40C : {
        asm/rom_gap_003E40C.o(.rodata)
    } > ROM
    .rom_sub_0803E440 0x0803E440 : {
        asm/matchings/sub_0803E440.o(.text)
    } > ROM
    .rom_gap_003E474 0x0803E474 : {
        asm/rom_gap_003E474.o(.rodata)
    } > ROM
    .rom_sub_0803E848 0x0803E848 : {
        asm/matchings/sub_0803E848.o(.text)
    } > ROM
    .rom_gap_003E8E8 0x0803E8E8 : {
        asm/rom_gap_003E8E8.o(.rodata)
    } > ROM
    .rom_sub_0803E934 0x0803E934 : {
        asm/matchings/sub_0803E934.o(.text)
    } > ROM
    .rom_gap_003E9A4 0x0803E9A4 : {
        asm/rom_gap_003E9A4.o(.rodata)
    } > ROM
    .rom_sub_0803EBB0 0x0803EBB0 : {
        asm/matchings/sub_0803EBB0.o(.text)
    } > ROM
    .rom_gap_003EBD8 0x0803EBD8 : {
        asm/rom_gap_003EBD8.o(.rodata)
    } > ROM
    .rom_sub_0803EC34 0x0803EC34 : {
        asm/matchings/sub_0803EC34.o(.text)
    } > ROM
    .rom_gap_003EC5C 0x0803EC5C : {
        asm/rom_gap_003EC5C.o(.rodata)
    } > ROM
    .rom_sub_0803ECB8 0x0803ECB8 : {
        asm/matchings/sub_0803ECB8.o(.text)
    } > ROM
    .rom_gap_003ECE0 0x0803ECE0 : {
        asm/rom_gap_003ECE0.o(.rodata)
    } > ROM
    .rom_sub_0803EDC8 0x0803EDC8 : {
        asm/matchings/sub_0803EDC8.o(.text)
    } > ROM
    .rom_gap_003EDDC 0x0803EDDC : {
        asm/rom_gap_003EDDC.o(.rodata)
    } > ROM
    .rom_sub_0803EDF0 0x0803EDF0 : {
        asm/matchings/sub_0803EDF0.o(.text)
    } > ROM
    .rom_gap_003EE04 0x0803EE04 : {
        asm/rom_gap_003EE04.o(.rodata)
    } > ROM
    .rom_sub_0803FDD0 0x0803FDD0 : {
        asm/matchings/sub_0803FDD0.o(.text)
    } > ROM
    .rom_gap_003FE10 0x0803FE10 : {
        asm/rom_gap_003FE10.o(.rodata)
    } > ROM
    .rom_sub_0803FFB0 0x0803FFB0 : {
        asm/matchings/sub_0803FFB0.o(.text)
    } > ROM
    .rom_sub_08040088 0x08040088 : {
        asm/matchings/sub_08040088.o(.text)
    } > ROM
    .rom_sub_080400C0 0x080400C0 : {
        asm/matchings/sub_080400C0.o(.text)
    } > ROM
    .rom_sub_080400D4 0x080400D4 : {
        asm/matchings/sub_080400D4.o(.text)
    } > ROM
    .rom_gap_00400F2 0x080400F2 : {
        asm/rom_gap_00400F2.o(.rodata)
    } > ROM
    .rom_sub_08040530 0x08040530 : {
        asm/matchings/sub_08040530.o(.text)
    } > ROM
    .rom_gap_004054C 0x0804054C : {
        asm/rom_gap_004054C.o(.rodata)
    } > ROM
    .rom_sub_080405A8 0x080405A8 : {
        asm/matchings/sub_080405A8.o(.text)
    } > ROM
    .rom_sub_080405E8 0x080405E8 : {
        asm/matchings/sub_080405E8.o(.text)
    } > ROM
    .rom_sub_08040618 0x08040618 : {
        asm/matchings/sub_08040618.o(.text)
    } > ROM
    .rom_gap_0040648 0x08040648 : {
        asm/rom_gap_0040648.o(.rodata)
    } > ROM
    .rom_sub_08040680 0x08040680 : {
        asm/matchings/sub_08040680.o(.text)
    } > ROM
    .rom_gap_00407B4 0x080407B4 : {
        asm/rom_gap_00407B4.o(.rodata)
    } > ROM
    .rom_sub_080408C4 0x080408C4 : {
        asm/matchings/sub_080408C4.o(.text)
    } > ROM
    .rom_gap_00408E4 0x080408E4 : {
        asm/rom_gap_00408E4.o(.rodata)
    } > ROM
    .rom_sub_08040EF4 0x08040EF4 : {
        asm/matchings/sub_08040EF4.o(.text)
    } > ROM
    .rom_sub_08040F4C 0x08040F4C : {
        asm/matchings/sub_08040F4C.o(.text)
    } > ROM
    .rom_sub_0804109C 0x0804109C : {
        asm/matchings/sub_0804109C.o(.text)
    } > ROM
    .rom_sub_080411EC 0x080411EC : {
        asm/matchings/sub_080411EC.o(.text)
    } > ROM
    .rom_gap_0041346 0x08041346 : {
        asm/rom_gap_0041346.o(.rodata)
    } > ROM
    .rom_sub_08041348 0x08041348 : {
        asm/matchings/sub_08041348.o(.text)
    } > ROM
    .rom_sub_08041394 0x08041394 : {
        asm/matchings/sub_08041394.o(.text)
    } > ROM
    .rom_gap_00413BA 0x080413BA : {
        asm/rom_gap_00413BA.o(.rodata)
    } > ROM
    .rom_sub_080415FC 0x080415FC : {
        asm/matchings/sub_080415FC.o(.text)
    } > ROM
    .rom_sub_080416C4 0x080416C4 : {
        asm/matchings/sub_080416C4.o(.text)
    } > ROM
    .rom_sub_08041774 0x08041774 : {
        asm/matchings/sub_08041774.o(.text)
    } > ROM
    .rom_gap_0041808 0x08041808 : {
        asm/rom_gap_0041808.o(.rodata)
    } > ROM
    .rom_sub_08041858 0x08041858 : {
        asm/matchings/sub_08041858.o(.text)
    } > ROM
    .rom_sub_0804188C 0x0804188C : {
        asm/matchings/sub_0804188C.o(.text)
    } > ROM
    .rom_sub_08041980 0x08041980 : {
        asm/matchings/sub_08041980.o(.text)
    } > ROM
    .rom_sub_080419B0 0x080419B0 : {
        asm/matchings/sub_080419B0.o(.text)
    } > ROM
    .rom_gap_0041A5C 0x08041A5C : {
        asm/rom_gap_0041A5C.o(.rodata)
    } > ROM
    .rom_sub_08041B74 0x08041B74 : {
        asm/matchings/sub_08041B74.o(.text)
    } > ROM
    .rom_gap_0041C16 0x08041C16 : {
        asm/rom_gap_0041C16.o(.rodata)
    } > ROM
    .rom_sub_08041C8C 0x08041C8C : {
        asm/matchings/sub_08041C8C.o(.text)
    } > ROM
    .rom_gap_0041D1A 0x08041D1A : {
        asm/rom_gap_0041D1A.o(.rodata)
    } > ROM
    .rom_sub_08041DB4 0x08041DB4 : {
        asm/matchings/sub_08041DB4.o(.text)
    } > ROM
    .rom_gap_0041E12 0x08041E12 : {
        asm/rom_gap_0041E12.o(.rodata)
    } > ROM
    .rom_sub_08041E14 0x08041E14 : {
        asm/matchings/sub_08041E14.o(.text)
    } > ROM
    .rom_gap_0041E86 0x08041E86 : {
        asm/rom_gap_0041E86.o(.rodata)
    } > ROM
    .rom_sub_08041F88 0x08041F88 : {
        asm/matchings/sub_08041F88.o(.text)
    } > ROM
    .rom_gap_0041FDC 0x08041FDC : {
        asm/rom_gap_0041FDC.o(.rodata)
    } > ROM
    .rom_sub_08042390 0x08042390 : {
        asm/matchings/sub_08042390.o(.text)
    } > ROM
    .rom_gap_00423F2 0x080423F2 : {
        asm/rom_gap_00423F2.o(.rodata)
    } > ROM
    .rom_sub_0804245C 0x0804245C : {
        asm/matchings/sub_0804245C.o(.text)
    } > ROM
    .rom_sub_080424E8 0x080424E8 : {
        asm/matchings/sub_080424E8.o(.text)
    } > ROM
    .rom_sub_08042540 0x08042540 : {
        asm/matchings/sub_08042540.o(.text)
    } > ROM
    .rom_sub_080425B8 0x080425B8 : {
        asm/matchings/sub_080425B8.o(.text)
    } > ROM
    .rom_sub_08042630 0x08042630 : {
        asm/matchings/sub_08042630.o(.text)
    } > ROM
    .rom_sub_080426A4 0x080426A4 : {
        asm/matchings/sub_080426A4.o(.text)
    } > ROM
    .rom_sub_08042718 0x08042718 : {
        asm/matchings/sub_08042718.o(.text)
    } > ROM
    .rom_sub_08042784 0x08042784 : {
        asm/matchings/sub_08042784.o(.text)
    } > ROM
    .rom_sub_080427E8 0x080427E8 : {
        asm/matchings/sub_080427E8.o(.text)
    } > ROM
    .rom_sub_080428C4 0x080428C4 : {
        asm/matchings/sub_080428C4.o(.text)
    } > ROM
    .rom_sub_080428F0 0x080428F0 : {
        asm/matchings/sub_080428F0.o(.text)
    } > ROM
    .rom_gap_0042990 0x08042990 : {
        asm/rom_gap_0042990.o(.rodata)
    } > ROM
    .rom_sub_080429C0 0x080429C0 : {
        asm/matchings/sub_080429C0.o(.text)
    } > ROM
    .rom_sub_080429CC 0x080429CC : {
        asm/matchings/sub_080429CC.o(.text)
    } > ROM
    .rom_sub_08042B00 0x08042B00 : {
        asm/matchings/sub_08042B00.o(.text)
    } > ROM
    .rom_sub_08042B28 0x08042B28 : {
        asm/matchings/sub_08042B28.o(.text)
    } > ROM
    .rom_sub_08042B50 0x08042B50 : {
        asm/matchings/sub_08042B50.o(.text)
    } > ROM
    .rom_sub_08042B78 0x08042B78 : {
        asm/matchings/sub_08042B78.o(.text)
    } > ROM
    .rom_sub_08042BB0 0x08042BB0 : {
        asm/matchings/sub_08042BB0.o(.text)
    } > ROM
    .rom_sub_08042BE8 0x08042BE8 : {
        asm/matchings/sub_08042BE8.o(.text)
    } > ROM
    .rom_gap_0042C3A 0x08042C3A : {
        asm/rom_gap_0042C3A.o(.rodata)
    } > ROM
    .rom_sub_08042C3C 0x08042C3C : {
        asm/matchings/sub_08042C3C.o(.text)
    } > ROM
    .rom_gap_0042C74 0x08042C74 : {
        asm/rom_gap_0042C74.o(.rodata)
    } > ROM
    .rom_sub_08042E78 0x08042E78 : {
        asm/matchings/sub_08042E78.o(.text)
    } > ROM
    .rom_gap_0042E94 0x08042E94 : {
        asm/rom_gap_0042E94.o(.rodata)
    } > ROM
    .rom_sub_08042F4C 0x08042F4C : {
        asm/matchings/sub_08042F4C.o(.text)
    } > ROM
    .rom_gap_0042F9C 0x08042F9C : {
        asm/rom_gap_0042F9C.o(.rodata)
    } > ROM
    .rom_sub_080433F4 0x080433F4 : {
        asm/matchings/sub_080433F4.o(.text)
    } > ROM
    .rom_sub_08043420 0x08043420 : {
        asm/matchings/sub_08043420.o(.text)
    } > ROM
    .rom_gap_00435D6 0x080435D6 : {
        asm/rom_gap_00435D6.o(.rodata)
    } > ROM
    .rom_sub_080435D8 0x080435D8 : {
        asm/matchings/sub_080435D8.o(.text)
    } > ROM
    .rom_sub_08043638 0x08043638 : {
        asm/matchings/sub_08043638.o(.text)
    } > ROM
    .rom_sub_080436B0 0x080436B0 : {
        asm/matchings/sub_080436B0.o(.text)
    } > ROM
    .rom_gap_0043942 0x08043942 : {
        asm/rom_gap_0043942.o(.rodata)
    } > ROM
    .rom_sub_08043944 0x08043944 : {
        asm/matchings/sub_08043944.o(.text)
    } > ROM
    .rom_sub_08043974 0x08043974 : {
        asm/matchings/sub_08043974.o(.text)
    } > ROM
    .rom_gap_0043980 0x08043980 : {
        asm/rom_gap_0043980.o(.rodata)
    } > ROM
    .rom_sub_08043ADC 0x08043ADC : {
        asm/matchings/sub_08043ADC.o(.text)
    } > ROM
    .rom_gap_0043B20 0x08043B20 : {
        asm/rom_gap_0043B20.o(.rodata)
    } > ROM
    .rom_sub_08043B58 0x08043B58 : {
        asm/matchings/sub_08043B58.o(.text)
    } > ROM
    .rom_gap_0043B8E 0x08043B8E : {
        asm/rom_gap_0043B8E.o(.rodata)
    } > ROM
    .rom_sub_08043B90 0x08043B90 : {
        asm/matchings/sub_08043B90.o(.text)
    } > ROM
    .rom_sub_08043BDC 0x08043BDC : {
        asm/matchings/sub_08043BDC.o(.text)
    } > ROM
    .rom_sub_08043C28 0x08043C28 : {
        asm/matchings/sub_08043C28.o(.text)
    } > ROM
    .rom_sub_08043C70 0x08043C70 : {
        asm/matchings/sub_08043C70.o(.text)
    } > ROM
    .rom_sub_08043DB4 0x08043DB4 : {
        asm/matchings/sub_08043DB4.o(.text)
    } > ROM
    .rom_sub_080442FC 0x080442FC : {
        asm/matchings/sub_080442FC.o(.text)
    } > ROM
    .rom_sub_0804438C 0x0804438C : {
        asm/matchings/sub_0804438C.o(.text)
    } > ROM
    .rom_sub_080444BC 0x080444BC : {
        asm/matchings/sub_080444BC.o(.text)
    } > ROM
    .rom_sub_08044648 0x08044648 : {
        asm/matchings/sub_08044648.o(.text)
    } > ROM
    .rom_sub_080447B4 0x080447B4 : {
        asm/matchings/sub_080447B4.o(.text)
    } > ROM
    .rom_gap_00447CA 0x080447CA : {
        asm/rom_gap_00447CA.o(.rodata)
    } > ROM
    .rom_sub_080447CC 0x080447CC : {
        asm/matchings/sub_080447CC.o(.text)
    } > ROM
    .rom_gap_00447E6 0x080447E6 : {
        asm/rom_gap_00447E6.o(.rodata)
    } > ROM
    .rom_sub_080447E8 0x080447E8 : {
        asm/matchings/sub_080447E8.o(.text)
    } > ROM
    .rom_sub_0804495C 0x0804495C : {
        asm/matchings/sub_0804495C.o(.text)
    } > ROM
    .rom_gap_0044998 0x08044998 : {
        asm/rom_gap_0044998.o(.rodata)
    } > ROM
    .rom_sub_080449C4 0x080449C4 : {
        asm/matchings/sub_080449C4.o(.text)
    } > ROM
    .rom_sub_08044A20 0x08044A20 : {
        asm/matchings/sub_08044A20.o(.text)
    } > ROM
    .rom_gap_0044A84 0x08044A84 : {
        asm/rom_gap_0044A84.o(.rodata)
    } > ROM
    .rom_sub_08044A8C 0x08044A8C : {
        asm/matchings/sub_08044A8C.o(.text)
    } > ROM
    .rom_gap_0044D2C 0x08044D2C : {
        asm/rom_gap_0044D2C.o(.rodata)
    } > ROM
    .rom_sub_08044D8C 0x08044D8C : {
        asm/matchings/sub_08044D8C.o(.text)
    } > ROM
    .rom_gap_0044DAA 0x08044DAA : {
        asm/rom_gap_0044DAA.o(.rodata)
    } > ROM
    .rom_sub_08044EE8 0x08044EE8 : {
        asm/matchings/sub_08044EE8.o(.text)
    } > ROM
    .rom_gap_0044F14 0x08044F14 : {
        asm/rom_gap_0044F14.o(.rodata)
    } > ROM
    .rom_sub_08044F64 0x08044F64 : {
        asm/matchings/sub_08044F64.o(.text)
    } > ROM
    .rom_gap_0044FAE 0x08044FAE : {
        asm/rom_gap_0044FAE.o(.rodata)
    } > ROM
    .rom_sub_08044FB0 0x08044FB0 : {
        asm/matchings/sub_08044FB0.o(.text)
    } > ROM
    .rom_gap_004504C 0x0804504C : {
        asm/rom_gap_004504C.o(.rodata)
    } > ROM
    .rom_sub_08045128 0x08045128 : {
        asm/matchings/sub_08045128.o(.text)
    } > ROM
    .rom_gap_0045178 0x08045178 : {
        asm/rom_gap_0045178.o(.rodata)
    } > ROM
    .rom_sub_08045198 0x08045198 : {
        asm/matchings/sub_08045198.o(.text)
    } > ROM
    .rom_sub_08045590 0x08045590 : {
        asm/matchings/sub_08045590.o(.text)
    } > ROM
    .rom_gap_0045A78 0x08045A78 : {
        asm/rom_gap_0045A78.o(.rodata)
    } > ROM
    .rom_sub_08045A84 0x08045A84 : {
        asm/matchings/sub_08045A84.o(.text)
    } > ROM
    .rom_gap_0045AA6 0x08045AA6 : {
        asm/rom_gap_0045AA6.o(.rodata)
    } > ROM
    .rom_sub_08045AA8 0x08045AA8 : {
        asm/matchings/sub_08045AA8.o(.text)
    } > ROM
    .rom_gap_0045AD8 0x08045AD8 : {
        asm/rom_gap_0045AD8.o(.rodata)
    } > ROM
    .rom_sub_08045C5C 0x08045C5C : {
        asm/matchings/sub_08045C5C.o(.text)
    } > ROM
    .rom_gap_0045CE4 0x08045CE4 : {
        asm/rom_gap_0045CE4.o(.rodata)
    } > ROM
    .rom_sub_08045D3C 0x08045D3C : {
        asm/matchings/sub_08045D3C.o(.text)
    } > ROM
    .rom_sub_08045EF0 0x08045EF0 : {
        asm/matchings/sub_08045EF0.o(.text)
    } > ROM
    .rom_gap_0046114 0x08046114 : {
        asm/rom_gap_0046114.o(.rodata)
    } > ROM
    .rom_sub_08046230 0x08046230 : {
        asm/matchings/sub_08046230.o(.text)
    } > ROM
    .rom_sub_08046278 0x08046278 : {
        asm/matchings/sub_08046278.o(.text)
    } > ROM
    .rom_sub_080462D4 0x080462D4 : {
        asm/matchings/sub_080462D4.o(.text)
    } > ROM
    .rom_gap_0046356 0x08046356 : {
        asm/rom_gap_0046356.o(.rodata)
    } > ROM
    .rom_sub_08046E7C 0x08046E7C : {
        asm/matchings/sub_08046E7C.o(.text)
    } > ROM
    .rom_gap_00471E4 0x080471E4 : {
        asm/rom_gap_00471E4.o(.rodata)
    } > ROM
    .rom_sub_0804737C 0x0804737C : {
        asm/matchings/sub_0804737C.o(.text)
    } > ROM
    .rom_sub_080473E4 0x080473E4 : {
        asm/matchings/sub_080473E4.o(.text)
    } > ROM
    .rom_sub_080473F8 0x080473F8 : {
        asm/matchings/sub_080473F8.o(.text)
    } > ROM
    .rom_sub_0804745C 0x0804745C : {
        asm/matchings/sub_0804745C.o(.text)
    } > ROM
    .rom_sub_080474AC 0x080474AC : {
        asm/matchings/sub_080474AC.o(.text)
    } > ROM
    .rom_sub_08047594 0x08047594 : {
        asm/matchings/sub_08047594.o(.text)
    } > ROM
    .rom_sub_080475C4 0x080475C4 : {
        asm/matchings/sub_080475C4.o(.text)
    } > ROM
    .rom_sub_080475F4 0x080475F4 : {
        asm/matchings/sub_080475F4.o(.text)
    } > ROM
    .rom_sub_08047624 0x08047624 : {
        asm/matchings/sub_08047624.o(.text)
    } > ROM
    .rom_gap_00476D2 0x080476D2 : {
        asm/rom_gap_00476D2.o(.rodata)
    } > ROM
    .rom_sub_08047A94 0x08047A94 : {
        asm/matchings/sub_08047A94.o(.text)
    } > ROM
    .rom_gap_0047B3C 0x08047B3C : {
        asm/rom_gap_0047B3C.o(.rodata)
    } > ROM
    .rom_sub_08048168 0x08048168 : {
        asm/matchings/sub_08048168.o(.text)
    } > ROM
    .rom_gap_00481DC 0x080481DC : {
        asm/rom_gap_00481DC.o(.rodata)
    } > ROM
    .rom_sub_08048D0C 0x08048D0C : {
        asm/matchings/sub_08048D0C.o(.text)
    } > ROM
    .rom_gap_0048D24 0x08048D24 : {
        asm/rom_gap_0048D24.o(.rodata)
    } > ROM
    .rom_sub_08048DB8 0x08048DB8 : {
        asm/matchings/sub_08048DB8.o(.text)
    } > ROM
    .rom_gap_0048F70 0x08048F70 : {
        asm/rom_gap_0048F70.o(.rodata)
    } > ROM
    .rom_sub_08049F98 0x08049F98 : {
        asm/matchings/sub_08049F98.o(.text)
    } > ROM
    .rom_sub_0804A028 0x0804A028 : {
        asm/matchings/sub_0804A028.o(.text)
    } > ROM
    .rom_gap_004A0D6 0x0804A0D6 : {
        asm/rom_gap_004A0D6.o(.rodata)
    } > ROM
    .rom_sub_0804A438 0x0804A438 : {
        asm/matchings/sub_0804A438.o(.text)
    } > ROM
    .rom_sub_0804A4E0 0x0804A4E0 : {
        asm/matchings/sub_0804A4E0.o(.text)
    } > ROM
    .rom_gap_004A54C 0x0804A54C : {
        asm/rom_gap_004A54C.o(.rodata)
    } > ROM
    .rom_sub_0804AAF0 0x0804AAF0 : {
        asm/matchings/sub_0804AAF0.o(.text)
    } > ROM
    .rom_sub_0804AC3C 0x0804AC3C : {
        asm/matchings/sub_0804AC3C.o(.text)
    } > ROM
    .rom_gap_004ACA4 0x0804ACA4 : {
        asm/rom_gap_004ACA4.o(.rodata)
    } > ROM
    .rom_sub_0804AE94 0x0804AE94 : {
        asm/matchings/sub_0804AE94.o(.text)
    } > ROM
    .rom_gap_004AFC0 0x0804AFC0 : {
        asm/rom_gap_004AFC0.o(.rodata)
    } > ROM
    .rom_sub_0804B40C 0x0804B40C : {
        asm/matchings/sub_0804B40C.o(.text)
    } > ROM
    .rom_sub_0804B4B4 0x0804B4B4 : {
        asm/matchings/sub_0804B4B4.o(.text)
    } > ROM
    .rom_gap_004B51C 0x0804B51C : {
        asm/rom_gap_004B51C.o(.rodata)
    } > ROM
    .rom_sub_0804BD38 0x0804BD38 : {
        asm/matchings/sub_0804BD38.o(.text)
    } > ROM
    .rom_sub_0804BE80 0x0804BE80 : {
        asm/matchings/sub_0804BE80.o(.text)
    } > ROM
    .rom_gap_004BEA4 0x0804BEA4 : {
        asm/rom_gap_004BEA4.o(.rodata)
    } > ROM
    .rom_sub_0804C27C 0x0804C27C : {
        asm/matchings/sub_0804C27C.o(.text)
    } > ROM
    .rom_sub_0804C324 0x0804C324 : {
        asm/matchings/sub_0804C324.o(.text)
    } > ROM
    .rom_gap_004C38C 0x0804C38C : {
        asm/rom_gap_004C38C.o(.rodata)
    } > ROM
    .rom_sub_0804C8BC 0x0804C8BC : {
        asm/matchings/sub_0804C8BC.o(.text)
    } > ROM
    .rom_sub_0804CA30 0x0804CA30 : {
        asm/matchings/sub_0804CA30.o(.text)
    } > ROM
    .rom_gap_004CA54 0x0804CA54 : {
        asm/rom_gap_004CA54.o(.rodata)
    } > ROM
    .rom_sub_0804CE2C 0x0804CE2C : {
        asm/matchings/sub_0804CE2C.o(.text)
    } > ROM
    .rom_sub_0804CED4 0x0804CED4 : {
        asm/matchings/sub_0804CED4.o(.text)
    } > ROM
    .rom_gap_004CF3C 0x0804CF3C : {
        asm/rom_gap_004CF3C.o(.rodata)
    } > ROM
    .rom_sub_0804D420 0x0804D420 : {
        asm/matchings/sub_0804D420.o(.text)
    } > ROM
    .rom_gap_004D58A 0x0804D58A : {
        asm/rom_gap_004D58A.o(.rodata)
    } > ROM
    .rom_sub_0804D58C 0x0804D58C : {
        asm/matchings/sub_0804D58C.o(.text)
    } > ROM
    .rom_gap_004D5B0 0x0804D5B0 : {
        asm/rom_gap_004D5B0.o(.rodata)
    } > ROM
    .rom_sub_0804DB28 0x0804DB28 : {
        asm/matchings/sub_0804DB28.o(.text)
    } > ROM
    .rom_gap_004DEAC 0x0804DEAC : {
        asm/rom_gap_004DEAC.o(.rodata)
    } > ROM
    .rom_sub_0804E17C 0x0804E17C : {
        asm/matchings/sub_0804E17C.o(.text)
    } > ROM
    .rom_sub_0804E20C 0x0804E20C : {
        asm/matchings/sub_0804E20C.o(.text)
    } > ROM
    .rom_gap_004E2B0 0x0804E2B0 : {
        asm/rom_gap_004E2B0.o(.rodata)
    } > ROM
    .rom_sub_0804E4F4 0x0804E4F4 : {
        asm/matchings/sub_0804E4F4.o(.text)
    } > ROM
    .rom_gap_004E59C 0x0804E59C : {
        asm/rom_gap_004E59C.o(.rodata)
    } > ROM
    .rom_sub_0804EBF0 0x0804EBF0 : {
        asm/matchings/sub_0804EBF0.o(.text)
    } > ROM
    .rom_gap_004ECBA 0x0804ECBA : {
        asm/rom_gap_004ECBA.o(.rodata)
    } > ROM
    .rom_sub_0804ED90 0x0804ED90 : {
        asm/matchings/sub_0804ED90.o(.text)
    } > ROM
    .rom_gap_004EEA4 0x0804EEA4 : {
        asm/rom_gap_004EEA4.o(.rodata)
    } > ROM
    .rom_sub_0804FFCC 0x0804FFCC : {
        asm/matchings/sub_0804FFCC.o(.text)
    } > ROM
    .rom_gap_00505AC 0x080505AC : {
        asm/rom_gap_00505AC.o(.rodata)
    } > ROM
    .rom_sub_080507B8 0x080507B8 : {
        asm/matchings/sub_080507B8.o(.text)
    } > ROM
    .rom_sub_08050864 0x08050864 : {
        asm/matchings/sub_08050864.o(.text)
    } > ROM
    .rom_gap_005087C 0x0805087C : {
        asm/rom_gap_005087C.o(.rodata)
    } > ROM
    .rom_sub_08051444 0x08051444 : {
        asm/matchings/sub_08051444.o(.text)
    } > ROM
    .rom_sub_08051504 0x08051504 : {
        asm/matchings/sub_08051504.o(.text)
    } > ROM
    .rom_sub_08051578 0x08051578 : {
        asm/matchings/sub_08051578.o(.text)
    } > ROM
    .rom_gap_0051608 0x08051608 : {
        asm/rom_gap_0051608.o(.rodata)
    } > ROM
    .rom_sub_08051BBC 0x08051BBC : {
        asm/matchings/sub_08051BBC.o(.text)
    } > ROM
    .rom_gap_0051C38 0x08051C38 : {
        asm/rom_gap_0051C38.o(.rodata)
    } > ROM
    .rom_sub_080523A4 0x080523A4 : {
        asm/matchings/sub_080523A4.o(.text)
    } > ROM
    .rom_gap_0052414 0x08052414 : {
        asm/rom_gap_0052414.o(.rodata)
    } > ROM
    .rom_sub_0805264C 0x0805264C : {
        asm/matchings/sub_0805264C.o(.text)
    } > ROM
    .rom_gap_00526AC 0x080526AC : {
        asm/rom_gap_00526AC.o(.rodata)
    } > ROM
    .rom_sub_08052934 0x08052934 : {
        asm/matchings/sub_08052934.o(.text)
    } > ROM
    .rom_gap_0052988 0x08052988 : {
        asm/rom_gap_0052988.o(.rodata)
    } > ROM
    .rom_sub_08052F0C 0x08052F0C : {
        asm/matchings/sub_08052F0C.o(.text)
    } > ROM
    .rom_sub_08052FC8 0x08052FC8 : {
        asm/matchings/sub_08052FC8.o(.text)
    } > ROM
    .rom_gap_0053010 0x08053010 : {
        asm/rom_gap_0053010.o(.rodata)
    } > ROM
    .rom_sub_08053218 0x08053218 : {
        asm/matchings/sub_08053218.o(.text)
    } > ROM
    .rom_gap_00532A8 0x080532A8 : {
        asm/rom_gap_00532A8.o(.rodata)
    } > ROM
    .rom_sub_08053690 0x08053690 : {
        asm/matchings/sub_08053690.o(.text)
    } > ROM
    .rom_sub_080538A0 0x080538A0 : {
        asm/matchings/sub_080538A0.o(.text)
    } > ROM
    .rom_gap_00538B8 0x080538B8 : {
        asm/rom_gap_00538B8.o(.rodata)
    } > ROM
    .rom_sub_08054108 0x08054108 : {
        asm/matchings/sub_08054108.o(.text)
    } > ROM
    .rom_sub_08054120 0x08054120 : {
        asm/matchings/sub_08054120.o(.text)
    } > ROM
    .rom_gap_0054372 0x08054372 : {
        asm/rom_gap_0054372.o(.rodata)
    } > ROM
    .rom_sub_08054454 0x08054454 : {
        asm/matchings/sub_08054454.o(.text)
    } > ROM
    .rom_sub_08054494 0x08054494 : {
        asm/matchings/sub_08054494.o(.text)
    } > ROM
    .rom_sub_08054558 0x08054558 : {
        asm/matchings/sub_08054558.o(.text)
    } > ROM
    .rom_gap_0054582 0x08054582 : {
        asm/rom_gap_0054582.o(.rodata)
    } > ROM
    .rom_sub_08054CF4 0x08054CF4 : {
        asm/matchings/sub_08054CF4.o(.text)
    } > ROM
    .rom_gap_0054DA8 0x08054DA8 : {
        asm/rom_gap_0054DA8.o(.rodata)
    } > ROM
    .rom_sub_080553B8 0x080553B8 : {
        asm/matchings/sub_080553B8.o(.text)
    } > ROM
    .rom_gap_005546C 0x0805546C : {
        asm/rom_gap_005546C.o(.rodata)
    } > ROM
    .rom_sub_08056250 0x08056250 : {
        asm/matchings/sub_08056250.o(.text)
    } > ROM
    .rom_gap_005637E 0x0805637E : {
        asm/rom_gap_005637E.o(.rodata)
    } > ROM
    .rom_sub_08056380 0x08056380 : {
        asm/matchings/sub_08056380.o(.text)
    } > ROM
    .rom_gap_0056398 0x08056398 : {
        asm/rom_gap_0056398.o(.rodata)
    } > ROM
    .rom_sub_08056AF0 0x08056AF0 : {
        asm/matchings/sub_08056AF0.o(.text)
    } > ROM
    .rom_gap_0056B08 0x08056B08 : {
        asm/rom_gap_0056B08.o(.rodata)
    } > ROM
    .rom_sub_08056BA4 0x08056BA4 : {
        asm/matchings/sub_08056BA4.o(.text)
    } > ROM
    .rom_gap_0056D66 0x08056D66 : {
        asm/rom_gap_0056D66.o(.rodata)
    } > ROM
    .rom_sub_08056D68 0x08056D68 : {
        asm/matchings/sub_08056D68.o(.text)
    } > ROM
    .rom_sub_08056F84 0x08056F84 : {
        asm/matchings/sub_08056F84.o(.text)
    } > ROM
    .rom_gap_005702C 0x0805702C : {
        asm/rom_gap_005702C.o(.rodata)
    } > ROM
    .rom_sub_08057234 0x08057234 : {
        asm/matchings/sub_08057234.o(.text)
    } > ROM
    .rom_gap_0057272 0x08057272 : {
        asm/rom_gap_0057272.o(.rodata)
    } > ROM
    .rom_sub_08057274 0x08057274 : {
        asm/matchings/sub_08057274.o(.text)
    } > ROM
    .rom_gap_0057344 0x08057344 : {
        asm/rom_gap_0057344.o(.rodata)
    } > ROM
    .rom_sub_080593A4 0x080593A4 : {
        asm/matchings/sub_080593A4.o(.text)
    } > ROM
    .rom_gap_00594A4 0x080594A4 : {
        asm/rom_gap_00594A4.o(.rodata)
    } > ROM
    .rom_sub_08059AE0 0x08059AE0 : {
        asm/matchings/sub_08059AE0.o(.text)
    } > ROM
    .rom_gap_0059B48 0x08059B48 : {
        asm/rom_gap_0059B48.o(.rodata)
    } > ROM
    .rom_sub_08059B74 0x08059B74 : {
        asm/matchings/sub_08059B74.o(.text)
    } > ROM
    .rom_gap_0059BD6 0x08059BD6 : {
        asm/rom_gap_0059BD6.o(.rodata)
    } > ROM
    .rom_sub_08059BD8 0x08059BD8 : {
        asm/matchings/sub_08059BD8.o(.text)
    } > ROM
    .rom_sub_08059C6C 0x08059C6C : {
        asm/matchings/sub_08059C6C.o(.text)
    } > ROM
    .rom_sub_08059C98 0x08059C98 : {
        asm/matchings/sub_08059C98.o(.text)
    } > ROM
    .rom_sub_08059D08 0x08059D08 : {
        asm/matchings/sub_08059D08.o(.text)
    } > ROM
    .rom_gap_0059D36 0x08059D36 : {
        asm/rom_gap_0059D36.o(.rodata)
    } > ROM
    .rom_sub_08059DC8 0x08059DC8 : {
        asm/matchings/sub_08059DC8.o(.text)
    } > ROM
    .rom_gap_0059E10 0x08059E10 : {
        asm/rom_gap_0059E10.o(.rodata)
    } > ROM
    .rom_sub_0805D1AC 0x0805D1AC : {
        asm/matchings/sub_0805D1AC.o(.text)
    } > ROM
    .rom_gap_005D1DC 0x0805D1DC : {
        asm/rom_gap_005D1DC.o(.rodata)
    } > ROM
    .rom_sub_0805D99C 0x0805D99C : {
        asm/matchings/sub_0805D99C.o(.text)
    } > ROM
    .rom_gap_005D9F0 0x0805D9F0 : {
        asm/rom_gap_005D9F0.o(.rodata)
    } > ROM
    .rom_sub_0805DA70 0x0805DA70 : {
        asm/matchings/sub_0805DA70.o(.text)
    } > ROM
    .rom_gap_005DAA8 0x0805DAA8 : {
        asm/rom_gap_005DAA8.o(.rodata)
    } > ROM
    .rom_sub_0805E044 0x0805E044 : {
        asm/matchings/sub_0805E044.o(.text)
    } > ROM
    .rom_gap_005E128 0x0805E128 : {
        asm/rom_gap_005E128.o(.rodata)
    } > ROM
    .rom_sub_0806013C 0x0806013C : {
        asm/matchings/sub_0806013C.o(.text)
    } > ROM
    .rom_gap_0060174 0x08060174 : {
        asm/rom_gap_0060174.o(.rodata)
    } > ROM
    .rom_sub_080601C4 0x080601C4 : {
        asm/matchings/sub_080601C4.o(.text)
    } > ROM
    .rom_sub_08060220 0x08060220 : {
        asm/matchings/sub_08060220.o(.text)
    } > ROM
    .rom_sub_08060254 0x08060254 : {
        asm/matchings/sub_08060254.o(.text)
    } > ROM
    .rom_gap_006026C 0x0806026C : {
        asm/rom_gap_006026C.o(.rodata)
    } > ROM
    .rom_sub_080602C0 0x080602C0 : {
        asm/matchings/sub_080602C0.o(.text)
    } > ROM
    .rom_gap_00602CE 0x080602CE : {
        asm/rom_gap_00602CE.o(.rodata)
    } > ROM
    .rom_sub_08060394 0x08060394 : {
        asm/matchings/sub_08060394.o(.text)
    } > ROM
    .rom_gap_00603A2 0x080603A2 : {
        asm/rom_gap_00603A2.o(.rodata)
    } > ROM
    .rom_sub_080603A4 0x080603A4 : {
        asm/matchings/sub_080603A4.o(.text)
    } > ROM
    .rom_sub_080603E0 0x080603E0 : {
        asm/matchings/sub_080603E0.o(.text)
    } > ROM
    .rom_sub_08060428 0x08060428 : {
        asm/matchings/sub_08060428.o(.text)
    } > ROM
    .rom_gap_0060436 0x08060436 : {
        asm/rom_gap_0060436.o(.rodata)
    } > ROM
    .rom_sub_08060438 0x08060438 : {
        asm/matchings/sub_08060438.o(.text)
    } > ROM
    .rom_gap_0060446 0x08060446 : {
        asm/rom_gap_0060446.o(.rodata)
    } > ROM
    .rom_sub_08060448 0x08060448 : {
        asm/matchings/sub_08060448.o(.text)
    } > ROM
    .rom_gap_0060456 0x08060456 : {
        asm/rom_gap_0060456.o(.rodata)
    } > ROM
    .rom_sub_08060458 0x08060458 : {
        asm/matchings/sub_08060458.o(.text)
    } > ROM
    .rom_gap_0060466 0x08060466 : {
        asm/rom_gap_0060466.o(.rodata)
    } > ROM
    .rom_sub_08060468 0x08060468 : {
        asm/matchings/sub_08060468.o(.text)
    } > ROM
    .rom_sub_080604A4 0x080604A4 : {
        asm/matchings/sub_080604A4.o(.text)
    } > ROM
    .rom_sub_080604C8 0x080604C8 : {
        asm/matchings/sub_080604C8.o(.text)
    } > ROM
    .rom_gap_0060538 0x08060538 : {
        asm/rom_gap_0060538.o(.rodata)
    } > ROM
    .rom_sub_08060758 0x08060758 : {
        asm/matchings/sub_08060758.o(.text)
    } > ROM
    .rom_sub_08060798 0x08060798 : {
        asm/matchings/sub_08060798.o(.text)
    } > ROM
    .rom_sub_080607BC 0x080607BC : {
        asm/matchings/sub_080607BC.o(.text)
    } > ROM
    .rom_gap_006083C 0x0806083C : {
        asm/rom_gap_006083C.o(.rodata)
    } > ROM
    .rom_sub_080608D4 0x080608D4 : {
        asm/matchings/sub_080608D4.o(.text)
    } > ROM
    .rom_gap_00608F4 0x080608F4 : {
        asm/rom_gap_00608F4.o(.rodata)
    } > ROM
    .rom_sub_08060C30 0x08060C30 : {
        asm/matchings/sub_08060C30.o(.text)
    } > ROM
    .rom_sub_08060D28 0x08060D28 : {
        asm/matchings/sub_08060D28.o(.text)
    } > ROM
    .rom_sub_08060D58 0x08060D58 : {
        asm/matchings/sub_08060D58.o(.text)
    } > ROM
    .rom_sub_08060E48 0x08060E48 : {
        asm/matchings/sub_08060E48.o(.text)
    } > ROM
    .rom_sub_0806105C 0x0806105C : {
        asm/matchings/sub_0806105C.o(.text)
    } > ROM
    .rom_gap_0061088 0x08061088 : {
        asm/rom_gap_0061088.o(.rodata)
    } > ROM
    .rom_sub_080610A8 0x080610A8 : {
        asm/matchings/sub_080610A8.o(.text)
    } > ROM
    .rom_gap_006110A 0x0806110A : {
        asm/rom_gap_006110A.o(.rodata)
    } > ROM
    .rom_sub_0806114C 0x0806114C : {
        asm/matchings/sub_0806114C.o(.text)
    } > ROM
    .rom_sub_080611A4 0x080611A4 : {
        asm/matchings/sub_080611A4.o(.text)
    } > ROM
    .rom_gap_00611EE 0x080611EE : {
        asm/rom_gap_00611EE.o(.rodata)
    } > ROM
    .rom_sub_080611F0 0x080611F0 : {
        asm/matchings/sub_080611F0.o(.text)
    } > ROM
    .rom_sub_0806121C 0x0806121C : {
        asm/matchings/sub_0806121C.o(.text)
    } > ROM
    .rom_sub_08061308 0x08061308 : {
        asm/matchings/sub_08061308.o(.text)
    } > ROM
    .rom_gap_0061338 0x08061338 : {
        asm/rom_gap_0061338.o(.rodata)
    } > ROM
    .rom_sub_08061564 0x08061564 : {
        asm/matchings/sub_08061564.o(.text)
    } > ROM
    .rom_sub_080615EC 0x080615EC : {
        asm/matchings/sub_080615EC.o(.text)
    } > ROM
    .rom_sub_08061610 0x08061610 : {
        asm/matchings/sub_08061610.o(.text)
    } > ROM
    .rom_sub_08061628 0x08061628 : {
        asm/matchings/sub_08061628.o(.text)
    } > ROM
    .rom_sub_0806171C 0x0806171C : {
        asm/matchings/sub_0806171C.o(.text)
    } > ROM
    .rom_sub_08061784 0x08061784 : {
        asm/matchings/sub_08061784.o(.text)
    } > ROM
    .rom_gap_0061794 0x08061794 : {
        asm/rom_gap_0061794.o(.rodata)
    } > ROM
    .rom_sub_080617B4 0x080617B4 : {
        asm/matchings/sub_080617B4.o(.text)
    } > ROM
    .rom_sub_080617C4 0x080617C4 : {
        asm/matchings/sub_080617C4.o(.text)
    } > ROM
    .rom_sub_08061800 0x08061800 : {
        asm/matchings/sub_08061800.o(.text)
    } > ROM
    .rom_sub_0806184C 0x0806184C : {
        asm/matchings/sub_0806184C.o(.text)
    } > ROM
    .rom_sub_080618A8 0x080618A8 : {
        asm/matchings/sub_080618A8.o(.text)
    } > ROM
    .rom_gap_00618EA 0x080618EA : {
        asm/rom_gap_00618EA.o(.rodata)
    } > ROM
    .rom_sub_080618EC 0x080618EC : {
        asm/matchings/sub_080618EC.o(.text)
    } > ROM
    .rom_sub_08061A98 0x08061A98 : {
        asm/matchings/sub_08061A98.o(.text)
    } > ROM
    .rom_sub_08061AA8 0x08061AA8 : {
        asm/matchings/sub_08061AA8.o(.text)
    } > ROM
    .rom_sub_08061AB8 0x08061AB8 : {
        asm/matchings/sub_08061AB8.o(.text)
    } > ROM
    .rom_gap_0061B30 0x08061B30 : {
        asm/rom_gap_0061B30.o(.rodata)
    } > ROM
    .rom_sub_08061BAC 0x08061BAC : {
        asm/matchings/sub_08061BAC.o(.text)
    } > ROM
    .rom_sub_08061BDC 0x08061BDC : {
        asm/matchings/sub_08061BDC.o(.text)
    } > ROM
    .rom_sub_08061BE8 0x08061BE8 : {
        asm/matchings/sub_08061BE8.o(.text)
    } > ROM
    .rom_sub_08061C48 0x08061C48 : {
        asm/matchings/sub_08061C48.o(.text)
    } > ROM
    .rom_gap_0061C80 0x08061C80 : {
        asm/rom_gap_0061C80.o(.rodata)
    } > ROM
    .rom_sub_08061D00 0x08061D00 : {
        asm/matchings/sub_08061D00.o(.text)
    } > ROM
    .rom_sub_08061D68 0x08061D68 : {
        asm/matchings/sub_08061D68.o(.text)
    } > ROM
    .rom_sub_08061DC0 0x08061DC0 : {
        asm/matchings/sub_08061DC0.o(.text)
    } > ROM
    .rom_gap_0061E08 0x08061E08 : {
        asm/rom_gap_0061E08.o(.rodata)
    } > ROM
    .rom_sub_08061E40 0x08061E40 : {
        asm/matchings/sub_08061E40.o(.text)
    } > ROM
    .rom_gap_0061E54 0x08061E54 : {
        asm/rom_gap_0061E54.o(.rodata)
    } > ROM
    .rom_sub_08061E8C 0x08061E8C : {
        asm/matchings/sub_08061E8C.o(.text)
    } > ROM
    .rom_sub_08061EF8 0x08061EF8 : {
        asm/matchings/sub_08061EF8.o(.text)
    } > ROM
    .rom_sub_08062044 0x08062044 : {
        asm/matchings/sub_08062044.o(.text)
    } > ROM
    .rom_sub_08062068 0x08062068 : {
        asm/matchings/sub_08062068.o(.text)
    } > ROM
    .rom_sub_08062098 0x08062098 : {
        asm/matchings/sub_08062098.o(.text)
    } > ROM
    .rom_sub_0806209C 0x0806209C : {
        asm/matchings/sub_0806209C.o(.text)
    } > ROM
    .rom_sub_080620D4 0x080620D4 : {
        asm/matchings/sub_080620D4.o(.text)
    } > ROM
    .rom_sub_0806211C 0x0806211C : {
        asm/matchings/sub_0806211C.o(.text)
    } > ROM
    .rom_sub_08062238 0x08062238 : {
        asm/matchings/sub_08062238.o(.text)
    } > ROM
    .rom_gap_006225A 0x0806225A : {
        asm/rom_gap_006225A.o(.rodata)
    } > ROM
    .rom_sub_0806225C 0x0806225C : {
        asm/matchings/sub_0806225C.o(.text)
    } > ROM
    .rom_gap_0062318 0x08062318 : {
        asm/rom_gap_0062318.o(.rodata)
    } > ROM
    .rom_sub_08062358 0x08062358 : {
        asm/matchings/sub_08062358.o(.text)
    } > ROM
    .rom_gap_0062418 0x08062418 : {
        asm/rom_gap_0062418.o(.rodata)
    } > ROM
    .rom_sub_08062634 0x08062634 : {
        asm/matchings/sub_08062634.o(.text)
    } > ROM
    .rom_sub_08062640 0x08062640 : {
        asm/matchings/sub_08062640.o(.text)
    } > ROM
    .rom_sub_08062684 0x08062684 : {
        asm/matchings/sub_08062684.o(.text)
    } > ROM
    .rom_gap_0062698 0x08062698 : {
        asm/rom_gap_0062698.o(.rodata)
    } > ROM
    .rom_sub_080626B8 0x080626B8 : {
        asm/matchings/sub_080626B8.o(.text)
    } > ROM
    .rom_gap_00626DC 0x080626DC : {
        asm/rom_gap_00626DC.o(.rodata)
    } > ROM
    .rom_sub_08062728 0x08062728 : {
        asm/matchings/sub_08062728.o(.text)
    } > ROM
    .rom_gap_006273A 0x0806273A : {
        asm/rom_gap_006273A.o(.rodata)
    } > ROM
    .rom_sub_08062758 0x08062758 : {
        asm/matchings/sub_08062758.o(.text)
    } > ROM
    .rom_gap_006278E 0x0806278E : {
        asm/rom_gap_006278E.o(.rodata)
    } > ROM
    .rom_sub_08062790 0x08062790 : {
        asm/matchings/sub_08062790.o(.text)
    } > ROM
    .rom_gap_006287C 0x0806287C : {
        asm/rom_gap_006287C.o(.rodata)
    } > ROM
    .rom_sub_080628B4 0x080628B4 : {
        asm/matchings/sub_080628B4.o(.text)
    } > ROM
    .rom_sub_080628E4 0x080628E4 : {
        asm/matchings/sub_080628E4.o(.text)
    } > ROM
    .rom_gap_00628F8 0x080628F8 : {
        asm/rom_gap_00628F8.o(.rodata)
    } > ROM
    .rom_sub_08062960 0x08062960 : {
        asm/matchings/sub_08062960.o(.text)
    } > ROM
    .rom_sub_08062988 0x08062988 : {
        asm/matchings/sub_08062988.o(.text)
    } > ROM
    .rom_sub_08062A14 0x08062A14 : {
        asm/matchings/sub_08062A14.o(.text)
    } > ROM
    .rom_sub_08062A1C 0x08062A1C : {
        asm/matchings/sub_08062A1C.o(.text)
    } > ROM
    .rom_gap_0062A2C 0x08062A2C : {
        asm/rom_gap_0062A2C.o(.rodata)
    } > ROM
    .rom_sub_08062A74 0x08062A74 : {
        asm/matchings/sub_08062A74.o(.text)
    } > ROM
    .rom_sub_08062AC0 0x08062AC0 : {
        asm/matchings/sub_08062AC0.o(.text)
    } > ROM
    .rom_sub_08062AF8 0x08062AF8 : {
        asm/matchings/sub_08062AF8.o(.text)
    } > ROM
    .rom_gap_0062B9A 0x08062B9A : {
        asm/rom_gap_0062B9A.o(.rodata)
    } > ROM
    .rom_sub_08062B9C 0x08062B9C : {
        asm/matchings/sub_08062B9C.o(.text)
    } > ROM
    .rom_gap_0062BE8 0x08062BE8 : {
        asm/rom_gap_0062BE8.o(.rodata)
    } > ROM
    .rom_sub_08062BF0 0x08062BF0 : {
        asm/matchings/sub_08062BF0.o(.text)
    } > ROM
    .rom_sub_08062C38 0x08062C38 : {
        asm/matchings/sub_08062C38.o(.text)
    } > ROM
    .rom_sub_08062C80 0x08062C80 : {
        asm/matchings/sub_08062C80.o(.text)
    } > ROM
    .rom_sub_08062CC8 0x08062CC8 : {
        asm/matchings/sub_08062CC8.o(.text)
    } > ROM
    .rom_sub_08062CF4 0x08062CF4 : {
        asm/matchings/sub_08062CF4.o(.text)
    } > ROM
    .rom_sub_08062D24 0x08062D24 : {
        asm/matchings/sub_08062D24.o(.text)
    } > ROM
    .rom_gap_0062D4E 0x08062D4E : {
        asm/rom_gap_0062D4E.o(.rodata)
    } > ROM
    .rom_sub_08062D50 0x08062D50 : {
        asm/matchings/sub_08062D50.o(.text)
    } > ROM
    .rom_gap_0062D7E 0x08062D7E : {
        asm/rom_gap_0062D7E.o(.rodata)
    } > ROM
    .rom_sub_08062D80 0x08062D80 : {
        asm/matchings/sub_08062D80.o(.text)
    } > ROM
    .rom_sub_08062E88 0x08062E88 : {
        asm/matchings/sub_08062E88.o(.text)
    } > ROM
    .rom_sub_08062F90 0x08062F90 : {
        asm/matchings/sub_08062F90.o(.text)
    } > ROM
    .rom_gap_0063024 0x08063024 : {
        asm/rom_gap_0063024.o(.rodata)
    } > ROM
    .rom_sub_0806306C 0x0806306C : {
        asm/matchings/sub_0806306C.o(.text)
    } > ROM
    .rom_sub_08063104 0x08063104 : {
        asm/matchings/sub_08063104.o(.text)
    } > ROM
    .rom_sub_0806314C 0x0806314C : {
        asm/matchings/sub_0806314C.o(.text)
    } > ROM
    .rom_gap_00632E0 0x080632E0 : {
        asm/rom_gap_00632E0.o(.rodata)
    } > ROM
    .rom_sub_080632F8 0x080632F8 : {
        asm/matchings/sub_080632F8.o(.text)
    } > ROM
    .rom_gap_00633B0 0x080633B0 : {
        asm/rom_gap_00633B0.o(.rodata)
    } > ROM
    .rom_sub_08063D68 0x08063D68 : {
        asm/matchings/sub_08063D68.o(.text)
    } > ROM
    .rom_gap_0063E40 0x08063E40 : {
        asm/rom_gap_0063E40.o(.rodata)
    } > ROM
    .rom_sub_08065560 0x08065560 : {
        asm/matchings/sub_08065560.o(.text)
    } > ROM
    .rom_gap_00655D8 0x080655D8 : {
        asm/rom_gap_00655D8.o(.rodata)
    } > ROM
    .rom_sub_08065CD0 0x08065CD0 : {
        asm/matchings/sub_08065CD0.o(.text)
    } > ROM
    .rom_sub_08065E0C 0x08065E0C : {
        asm/matchings/sub_08065E0C.o(.text)
    } > ROM
    .rom_gap_0065E68 0x08065E68 : {
        asm/rom_gap_0065E68.o(.rodata)
    } > ROM
    .rom_sub_08066224 0x08066224 : {
        asm/matchings/sub_08066224.o(.text)
    } > ROM
    .rom_gap_0066294 0x08066294 : {
        asm/rom_gap_0066294.o(.rodata)
    } > ROM
    .rom_sub_08066390 0x08066390 : {
        asm/matchings/sub_08066390.o(.text)
    } > ROM
    .rom_sub_0806639C 0x0806639C : {
        asm/matchings/sub_0806639C.o(.text)
    } > ROM
    .rom_gap_00663B8 0x080663B8 : {
        asm/rom_gap_00663B8.o(.rodata)
    } > ROM
    .rom_sub_08066434 0x08066434 : {
        asm/matchings/sub_08066434.o(.text)
    } > ROM
    .rom_sub_08066440 0x08066440 : {
        asm/matchings/sub_08066440.o(.text)
    } > ROM
    .rom_sub_0806644C 0x0806644C : {
        asm/matchings/sub_0806644C.o(.text)
    } > ROM
    .rom_gap_006645C 0x0806645C : {
        asm/rom_gap_006645C.o(.rodata)
    } > ROM
    .rom_sub_08066AD4 0x08066AD4 : {
        asm/matchings/sub_08066AD4.o(.text)
    } > ROM
    .rom_sub_08066B10 0x08066B10 : {
        asm/matchings/sub_08066B10.o(.text)
    } > ROM
    .rom_sub_08066BC4 0x08066BC4 : {
        asm/matchings/sub_08066BC4.o(.text)
    } > ROM
    .rom_sub_08066BF0 0x08066BF0 : {
        asm/matchings/sub_08066BF0.o(.text)
    } > ROM
    .rom_gap_0066C36 0x08066C36 : {
        asm/rom_gap_0066C36.o(.rodata)
    } > ROM
    .rom_sub_08066FB8 0x08066FB8 : {
        asm/matchings/sub_08066FB8.o(.text)
    } > ROM
    .rom_gap_00670E4 0x080670E4 : {
        asm/rom_gap_00670E4.o(.rodata)
    } > ROM
    .rom_sub_080674A0 0x080674A0 : {
        asm/matchings/sub_080674A0.o(.text)
    } > ROM
    .rom_sub_080674A4 0x080674A4 : {
        asm/matchings/sub_080674A4.o(.text)
    } > ROM
    .rom_gap_00674AA 0x080674AA : {
        asm/rom_gap_00674AA.o(.rodata)
    } > ROM
    .rom_sub_080674AC 0x080674AC : {
        asm/matchings/sub_080674AC.o(.text)
    } > ROM
    .rom_sub_080674B0 0x080674B0 : {
        asm/matchings/sub_080674B0.o(.text)
    } > ROM
    .rom_sub_080674B4 0x080674B4 : {
        asm/matchings/sub_080674B4.o(.text)
    } > ROM
    .rom_gap_00674BA 0x080674BA : {
        asm/rom_gap_00674BA.o(.rodata)
    } > ROM
    .rom_sub_080674BC 0x080674BC : {
        asm/matchings/sub_080674BC.o(.text)
    } > ROM
    .rom_sub_08067504 0x08067504 : {
        asm/matchings/sub_08067504.o(.text)
    } > ROM
    .rom_sub_08067584 0x08067584 : {
        asm/matchings/sub_08067584.o(.text)
    } > ROM
    .rom_sub_08067634 0x08067634 : {
        asm/matchings/sub_08067634.o(.text)
    } > ROM
    .rom_sub_08067648 0x08067648 : {
        asm/matchings/sub_08067648.o(.text)
    } > ROM
    .rom_sub_080677A8 0x080677A8 : {
        asm/matchings/sub_080677A8.o(.text)
    } > ROM
    .rom_gap_00677FE 0x080677FE : {
        asm/rom_gap_00677FE.o(.rodata)
    } > ROM
    .rom_sub_08067890 0x08067890 : {
        asm/matchings/sub_08067890.o(.text)
    } > ROM
    .rom_gap_00678A4 0x080678A4 : {
        asm/rom_gap_00678A4.o(.rodata)
    } > ROM
    .rom_sub_080679A4 0x080679A4 : {
        asm/matchings/sub_080679A4.o(.text)
    } > ROM
    .rom_sub_080679C0 0x080679C0 : {
        asm/matchings/sub_080679C0.o(.text)
    } > ROM
    .rom_gap_00679DC 0x080679DC : {
        asm/rom_gap_00679DC.o(.rodata)
    } > ROM
    .rom_sub_08067A9C 0x08067A9C : {
        asm/matchings/sub_08067A9C.o(.text)
    } > ROM
    .rom_gap_0067A9E 0x08067A9E : {
        asm/rom_gap_0067A9E.o(.rodata)
    } > ROM
    .rom_sub_08067B98 0x08067B98 : {
        asm/matchings/sub_08067B98.o(.text)
    } > ROM
    .rom_gap_0067B9E 0x08067B9E : {
        asm/rom_gap_0067B9E.o(.rodata)
    } > ROM
    .rom_sub_08067BB8 0x08067BB8 : {
        asm/matchings/sub_08067BB8.o(.text)
    } > ROM
    .rom_sub_08067CE8 0x08067CE8 : {
        asm/matchings/sub_08067CE8.o(.text)
    } > ROM
    .rom_gap_0067F0C 0x08067F0C : {
        asm/rom_gap_0067F0C.o(.rodata)
    } > ROM
    .rom_sub_08067F3C 0x08067F3C : {
        asm/matchings/sub_08067F3C.o(.text)
    } > ROM
    .rom_sub_08067F98 0x08067F98 : {
        asm/matchings/sub_08067F98.o(.text)
    } > ROM
    .rom_sub_08067FC8 0x08067FC8 : {
        asm/matchings/sub_08067FC8.o(.text)
    } > ROM
    .rom_gap_0068012 0x08068012 : {
        asm/rom_gap_0068012.o(.rodata)
    } > ROM
    .rom_sub_08068014 0x08068014 : {
        asm/matchings/sub_08068014.o(.text)
    } > ROM
    .rom_gap_006801E 0x0806801E : {
        asm/rom_gap_006801E.o(.rodata)
    } > ROM
    .rom_sub_08068020 0x08068020 : {
        asm/matchings/sub_08068020.o(.text)
    } > ROM
    .rom_gap_006806E 0x0806806E : {
        asm/rom_gap_006806E.o(.rodata)
    } > ROM
    .rom_sub_080680CC 0x080680CC : {
        asm/matchings/sub_080680CC.o(.text)
    } > ROM
    .rom_sub_08068118 0x08068118 : {
        asm/matchings/sub_08068118.o(.text)
    } > ROM
    .rom_gap_006817E 0x0806817E : {
        asm/rom_gap_006817E.o(.rodata)
    } > ROM
    .rom_sub_08068180 0x08068180 : {
        asm/matchings/sub_08068180.o(.text)
    } > ROM
    .rom_gap_006822E 0x0806822E : {
        asm/rom_gap_006822E.o(.rodata)
    } > ROM
    .rom_sub_0806833C 0x0806833C : {
        asm/matchings/sub_0806833C.o(.text)
    } > ROM
    .rom_gap_00683D8 0x080683D8 : {
        asm/rom_gap_00683D8.o(.rodata)
    } > ROM
    .rom_sub_08068418 0x08068418 : {
        asm/matchings/sub_08068418.o(.text)
    } > ROM
    .rom_gap_0068528 0x08068528 : {
        asm/rom_gap_0068528.o(.rodata)
    } > ROM
    .rom_sub_08068558 0x08068558 : {
        asm/matchings/sub_08068558.o(.text)
    } > ROM
    .rom_sub_08068574 0x08068574 : {
        asm/matchings/sub_08068574.o(.text)
    } > ROM
    .rom_sub_08068584 0x08068584 : {
        asm/matchings/sub_08068584.o(.text)
    } > ROM
    .rom_gap_0068590 0x08068590 : {
        asm/rom_gap_0068590.o(.rodata)
    } > ROM
    .rom_sub_08068598 0x08068598 : {
        asm/matchings/sub_08068598.o(.text)
    } > ROM
    .rom_sub_080686B4 0x080686B4 : {
        asm/matchings/sub_080686B4.o(.text)
    } > ROM
    .rom_sub_080686D8 0x080686D8 : {
        asm/matchings/sub_080686D8.o(.text)
    } > ROM
    .rom_gap_00686E4 0x080686E4 : {
        asm/rom_gap_00686E4.o(.rodata)
    } > ROM
    .rom_sub_080686F4 0x080686F4 : {
        asm/matchings/sub_080686F4.o(.text)
    } > ROM
    .rom_sub_08068798 0x08068798 : {
        asm/matchings/sub_08068798.o(.text)
    } > ROM
    .rom_gap_0068806 0x08068806 : {
        asm/rom_gap_0068806.o(.rodata)
    } > ROM
    .rom_sub_08068808 0x08068808 : {
        asm/matchings/sub_08068808.o(.text)
    } > ROM
    .rom_gap_006883A 0x0806883A : {
        asm/rom_gap_006883A.o(.rodata)
    } > ROM
    .rom_sub_08068884 0x08068884 : {
        asm/matchings/sub_08068884.o(.text)
    } > ROM
    .rom_gap_006889C 0x0806889C : {
        asm/rom_gap_006889C.o(.rodata)
    } > ROM
    .rom_sub_080688C8 0x080688C8 : {
        asm/matchings/sub_080688C8.o(.text)
    } > ROM
    .rom_gap_0068986 0x08068986 : {
        asm/rom_gap_0068986.o(.rodata)
    } > ROM
    .rom_sub_08068988 0x08068988 : {
        asm/matchings/sub_08068988.o(.text)
    } > ROM
    .rom_gap_0068A06 0x08068A06 : {
        asm/rom_gap_0068A06.o(.rodata)
    } > ROM
    .rom_sub_08068A08 0x08068A08 : {
        asm/matchings/sub_08068A08.o(.text)
    } > ROM
    .rom_sub_08068BD4 0x08068BD4 : {
        asm/matchings/sub_08068BD4.o(.text)
    } > ROM
    .rom_gap_0068D78 0x08068D78 : {
        asm/rom_gap_0068D78.o(.rodata)
    } > ROM
    .rom_sub_08068E54 0x08068E54 : {
        asm/matchings/sub_08068E54.o(.text)
    } > ROM
    .rom_sub_08068EC0 0x08068EC0 : {
        asm/matchings/sub_08068EC0.o(.text)
    } > ROM
    .rom_gap_0068FB8 0x08068FB8 : {
        asm/rom_gap_0068FB8.o(.rodata)
    } > ROM
    .rom_sub_080691E4 0x080691E4 : {
        asm/matchings/sub_080691E4.o(.text)
    } > ROM
    .rom_gap_006926E 0x0806926E : {
        asm/rom_gap_006926E.o(.rodata)
    } > ROM
    .rom_sub_08069270 0x08069270 : {
        asm/matchings/sub_08069270.o(.text)
    } > ROM
    .rom_gap_0069364 0x08069364 : {
        asm/rom_gap_0069364.o(.rodata)
    } > ROM
    .rom_sub_0806960C 0x0806960C : {
        asm/matchings/sub_0806960C.o(.text)
    } > ROM
    .rom_gap_0069864 0x08069864 : {
        asm/rom_gap_0069864.o(.rodata)
    } > ROM
    .rom_sub_08069894 0x08069894 : {
        asm/matchings/sub_08069894.o(.text)
    } > ROM
    .rom_gap_00698F4 0x080698F4 : {
        asm/rom_gap_00698F4.o(.rodata)
    } > ROM
    .rom_sub_08069908 0x08069908 : {
        asm/matchings/sub_08069908.o(.text)
    } > ROM
    .rom_sub_08069948 0x08069948 : {
        asm/matchings/sub_08069948.o(.text)
    } > ROM
    .rom_sub_08069988 0x08069988 : {
        asm/matchings/sub_08069988.o(.text)
    } > ROM
    .rom_sub_080699C8 0x080699C8 : {
        asm/matchings/sub_080699C8.o(.text)
    } > ROM
    .rom_sub_08069A18 0x08069A18 : {
        asm/matchings/sub_08069A18.o(.text)
    } > ROM
    .rom_sub_08069A60 0x08069A60 : {
        asm/matchings/sub_08069A60.o(.text)
    } > ROM
    .rom_sub_08069B78 0x08069B78 : {
        asm/matchings/sub_08069B78.o(.text)
    } > ROM
    .rom_gap_0069C12 0x08069C12 : {
        asm/rom_gap_0069C12.o(.rodata)
    } > ROM
    .rom_sub_08069C14 0x08069C14 : {
        asm/matchings/sub_08069C14.o(.text)
    } > ROM
    .rom_gap_0069C28 0x08069C28 : {
        asm/rom_gap_0069C28.o(.rodata)
    } > ROM
    .rom_sub_08069DBC 0x08069DBC : {
        asm/matchings/sub_08069DBC.o(.text)
    } > ROM
    .rom_gap_0069E1C 0x08069E1C : {
        asm/rom_gap_0069E1C.o(.rodata)
    } > ROM
    .rom_sub_08069F00 0x08069F00 : {
        asm/matchings/sub_08069F00.o(.text)
    } > ROM
    .rom_gap_0069F18 0x08069F18 : {
        asm/rom_gap_0069F18.o(.rodata)
    } > ROM
    .rom_sub_0806A314 0x0806A314 : {
        asm/matchings/sub_0806A314.o(.text)
    } > ROM
    .rom_sub_0806A3A4 0x0806A3A4 : {
        asm/matchings/sub_0806A3A4.o(.text)
    } > ROM
    .rom_sub_0806A434 0x0806A434 : {
        asm/matchings/sub_0806A434.o(.text)
    } > ROM
    .rom_sub_0806A4D8 0x0806A4D8 : {
        asm/matchings/sub_0806A4D8.o(.text)
    } > ROM
    .rom_sub_0806A580 0x0806A580 : {
        asm/matchings/sub_0806A580.o(.text)
    } > ROM
    .rom_gap_006A5B0 0x0806A5B0 : {
        asm/rom_gap_006A5B0.o(.rodata)
    } > ROM
    .rom_sub_0806A6F8 0x0806A6F8 : {
        asm/matchings/sub_0806A6F8.o(.text)
    } > ROM
    .rom_gap_006A8AC 0x0806A8AC : {
        asm/rom_gap_006A8AC.o(.rodata)
    } > ROM
    .rom_sub_0806A954 0x0806A954 : {
        asm/matchings/sub_0806A954.o(.text)
    } > ROM
    .rom_gap_006A970 0x0806A970 : {
        asm/rom_gap_006A970.o(.rodata)
    } > ROM
    .rom_sub_0806AC68 0x0806AC68 : {
        asm/matchings/sub_0806AC68.o(.text)
    } > ROM
    .rom_gap_006AC7E 0x0806AC7E : {
        asm/rom_gap_006AC7E.o(.rodata)
    } > ROM
    .rom_sub_0806B064 0x0806B064 : {
        asm/matchings/sub_0806B064.o(.text)
    } > ROM
    .rom_gap_006B0DE 0x0806B0DE : {
        asm/rom_gap_006B0DE.o(.rodata)
    } > ROM
    .rom_sub_0806B2F0 0x0806B2F0 : {
        asm/matchings/sub_0806B2F0.o(.text)
    } > ROM
    .rom_sub_0806B3E8 0x0806B3E8 : {
        asm/matchings/sub_0806B3E8.o(.text)
    } > ROM
    .rom_gap_006B43C 0x0806B43C : {
        asm/rom_gap_006B43C.o(.rodata)
    } > ROM
    .rom_sub_0806B5B8 0x0806B5B8 : {
        asm/matchings/sub_0806B5B8.o(.text)
    } > ROM
    .rom_sub_0806B5C8 0x0806B5C8 : {
        asm/matchings/sub_0806B5C8.o(.text)
    } > ROM
    .rom_gap_006B6DA 0x0806B6DA : {
        asm/rom_gap_006B6DA.o(.rodata)
    } > ROM
    .rom_sub_0806B724 0x0806B724 : {
        asm/matchings/sub_0806B724.o(.text)
    } > ROM
    .rom_sub_0806B764 0x0806B764 : {
        asm/matchings/sub_0806B764.o(.text)
    } > ROM
    .rom_gap_006B9B0 0x0806B9B0 : {
        asm/rom_gap_006B9B0.o(.rodata)
    } > ROM
    .rom_sub_0806BB38 0x0806BB38 : {
        asm/matchings/sub_0806BB38.o(.text)
    } > ROM
    .rom_gap_006BB48 0x0806BB48 : {
        asm/rom_gap_006BB48.o(.rodata)
    } > ROM
    .rom_sub_0806BC0C 0x0806BC0C : {
        asm/matchings/sub_0806BC0C.o(.text)
    } > ROM
    .rom_gap_006BC80 0x0806BC80 : {
        asm/rom_gap_006BC80.o(.rodata)
    } > ROM
    .rom_sub_0806BDA8 0x0806BDA8 : {
        asm/matchings/sub_0806BDA8.o(.text)
    } > ROM
    .rom_gap_006BDC2 0x0806BDC2 : {
        asm/rom_gap_006BDC2.o(.rodata)
    } > ROM
    .rom_sub_0806BE08 0x0806BE08 : {
        asm/matchings/sub_0806BE08.o(.text)
    } > ROM
    .rom_sub_0806BE20 0x0806BE20 : {
        asm/matchings/sub_0806BE20.o(.text)
    } > ROM
    .rom_gap_006BE44 0x0806BE44 : {
        asm/rom_gap_006BE44.o(.rodata)
    } > ROM
    .rom_sub_0806C388 0x0806C388 : {
        asm/matchings/sub_0806C388.o(.text)
    } > ROM
    .rom_gap_006C64E 0x0806C64E : {
        asm/rom_gap_006C64E.o(.rodata)
    } > ROM
    .rom_sub_0806C704 0x0806C704 : {
        asm/matchings/sub_0806C704.o(.text)
    } > ROM
    .rom_sub_0806C78C 0x0806C78C : {
        asm/matchings/sub_0806C78C.o(.text)
    } > ROM
    .rom_gap_006C7D2 0x0806C7D2 : {
        asm/rom_gap_006C7D2.o(.rodata)
    } > ROM
    .rom_sub_0806C7D4 0x0806C7D4 : {
        asm/matchings/sub_0806C7D4.o(.text)
    } > ROM
    .rom_gap_006CCEA 0x0806CCEA : {
        asm/rom_gap_006CCEA.o(.rodata)
    } > ROM
    .rom_sub_0806D748 0x0806D748 : {
        asm/matchings/sub_0806D748.o(.text)
    } > ROM
    .rom_gap_006D776 0x0806D776 : {
        asm/rom_gap_006D776.o(.rodata)
    } > ROM
    .rom_sub_0806D958 0x0806D958 : {
        asm/matchings/sub_0806D958.o(.text)
    } > ROM
    .rom_gap_006D998 0x0806D998 : {
        asm/rom_gap_006D998.o(.rodata)
    } > ROM
    .rom_sub_0806DEC8 0x0806DEC8 : {
        asm/matchings/sub_0806DEC8.o(.text)
    } > ROM
    .rom_sub_0806DEF4 0x0806DEF4 : {
        asm/matchings/sub_0806DEF4.o(.text)
    } > ROM
    .rom_gap_006DF08 0x0806DF08 : {
        asm/rom_gap_006DF08.o(.rodata)
    } > ROM
    .rom_sub_0806DF38 0x0806DF38 : {
        asm/matchings/sub_0806DF38.o(.text)
    } > ROM
    .rom_gap_006E01C 0x0806E01C : {
        asm/rom_gap_006E01C.o(.rodata)
    } > ROM
    .rom_sub_0806E060 0x0806E060 : {
        asm/matchings/sub_0806E060.o(.text)
    } > ROM
    .rom_gap_006E24C 0x0806E24C : {
        asm/rom_gap_006E24C.o(.rodata)
    } > ROM
    .rom_sub_0806E31C 0x0806E31C : {
        asm/matchings/sub_0806E31C.o(.text)
    } > ROM
    .rom_gap_006E3B0 0x0806E3B0 : {
        asm/rom_gap_006E3B0.o(.rodata)
    } > ROM
    .rom_sub_0806E420 0x0806E420 : {
        asm/matchings/sub_0806E420.o(.text)
    } > ROM
    .rom_gap_006E4D2 0x0806E4D2 : {
        asm/rom_gap_006E4D2.o(.rodata)
    } > ROM
    .rom_sub_0806E7BC 0x0806E7BC : {
        asm/matchings/sub_0806E7BC.o(.text)
    } > ROM
    .rom_gap_006E854 0x0806E854 : {
        asm/rom_gap_006E854.o(.rodata)
    } > ROM
    .rom_sub_0806EBF8 0x0806EBF8 : {
        asm/matchings/sub_0806EBF8.o(.text)
    } > ROM
    .rom_sub_0806EC20 0x0806EC20 : {
        asm/matchings/sub_0806EC20.o(.text)
    } > ROM
    .rom_sub_0806EE24 0x0806EE24 : {
        asm/matchings/sub_0806EE24.o(.text)
    } > ROM
    .rom_sub_0806EE48 0x0806EE48 : {
        asm/matchings/sub_0806EE48.o(.text)
    } > ROM
    .rom_sub_0806EEC4 0x0806EEC4 : {
        asm/matchings/sub_0806EEC4.o(.text)
    } > ROM
    .rom_gap_006EEC6 0x0806EEC6 : {
        asm/rom_gap_006EEC6.o(.rodata)
    } > ROM
    .rom_sub_0806EEC8 0x0806EEC8 : {
        asm/matchings/sub_0806EEC8.o(.text)
    } > ROM
    .rom_sub_0806F05C 0x0806F05C : {
        asm/matchings/sub_0806F05C.o(.text)
    } > ROM
    .rom_sub_0806F174 0x0806F174 : {
        asm/matchings/sub_0806F174.o(.text)
    } > ROM
    .rom_sub_0806F1A0 0x0806F1A0 : {
        asm/matchings/sub_0806F1A0.o(.text)
    } > ROM
    .rom_gap_006F1DA 0x0806F1DA : {
        asm/rom_gap_006F1DA.o(.rodata)
    } > ROM
    .rom_sub_0806F430 0x0806F430 : {
        asm/matchings/sub_0806F430.o(.text)
    } > ROM
    .rom_gap_006F460 0x0806F460 : {
        asm/rom_gap_006F460.o(.rodata)
    } > ROM
    .rom_sub_0806F8C4 0x0806F8C4 : {
        asm/matchings/sub_0806F8C4.o(.text)
    } > ROM
    .rom_sub_0806F910 0x0806F910 : {
        asm/matchings/sub_0806F910.o(.text)
    } > ROM
    .rom_gap_006FB80 0x0806FB80 : {
        asm/rom_gap_006FB80.o(.rodata)
    } > ROM
    .rom_sub_0806FBF8 0x0806FBF8 : {
        asm/matchings/sub_0806FBF8.o(.text)
    } > ROM
    .rom_gap_006FCBC 0x0806FCBC : {
        asm/rom_gap_006FCBC.o(.rodata)
    } > ROM
    .rom_sub_0806FDB4 0x0806FDB4 : {
        asm/matchings/sub_0806FDB4.o(.text)
    } > ROM
    .rom_sub_0806FDD0 0x0806FDD0 : {
        asm/matchings/sub_0806FDD0.o(.text)
    } > ROM
    .rom_gap_006FE50 0x0806FE50 : {
        asm/rom_gap_006FE50.o(.rodata)
    } > ROM
    .rom_sub_0806FE84 0x0806FE84 : {
        asm/matchings/sub_0806FE84.o(.text)
    } > ROM
    .rom_sub_0806FEFC 0x0806FEFC : {
        asm/matchings/sub_0806FEFC.o(.text)
    } > ROM
    .rom_sub_0806FF28 0x0806FF28 : {
        asm/matchings/sub_0806FF28.o(.text)
    } > ROM
    .rom_sub_0806FF58 0x0806FF58 : {
        asm/matchings/sub_0806FF58.o(.text)
    } > ROM
    .rom_sub_0807000C 0x0807000C : {
        asm/matchings/sub_0807000C.o(.text)
    } > ROM
    .rom_sub_080700CC 0x080700CC : {
        asm/matchings/sub_080700CC.o(.text)
    } > ROM
    .rom_sub_08070188 0x08070188 : {
        asm/matchings/sub_08070188.o(.text)
    } > ROM
    .rom_sub_0807027C 0x0807027C : {
        asm/matchings/sub_0807027C.o(.text)
    } > ROM
    .rom_sub_08070354 0x08070354 : {
        asm/matchings/sub_08070354.o(.text)
    } > ROM
    .rom_sub_080703FC 0x080703FC : {
        asm/matchings/sub_080703FC.o(.text)
    } > ROM
    .rom_gap_007041E 0x0807041E : {
        asm/rom_gap_007041E.o(.rodata)
    } > ROM
    .rom_sub_08070468 0x08070468 : {
        asm/matchings/sub_08070468.o(.text)
    } > ROM
    .rom_gap_00704DA 0x080704DA : {
        asm/rom_gap_00704DA.o(.rodata)
    } > ROM
    .rom_sub_080705A4 0x080705A4 : {
        asm/matchings/sub_080705A4.o(.text)
    } > ROM
    .rom_gap_00705C0 0x080705C0 : {
        asm/rom_gap_00705C0.o(.rodata)
    } > ROM
    .rom_sub_080705CC 0x080705CC : {
        asm/matchings/sub_080705CC.o(.text)
    } > ROM
    .rom_gap_00705D2 0x080705D2 : {
        asm/rom_gap_00705D2.o(.rodata)
    } > ROM
    .rom_sub_080705D4 0x080705D4 : {
        asm/matchings/sub_080705D4.o(.text)
    } > ROM
    .rom_gap_00705DA 0x080705DA : {
        asm/rom_gap_00705DA.o(.rodata)
    } > ROM
    .rom_sub_080705DC 0x080705DC : {
        asm/matchings/sub_080705DC.o(.text)
    } > ROM
    .rom_gap_00705F8 0x080705F8 : {
        asm/rom_gap_00705F8.o(.rodata)
    } > ROM
    .rom_sub_08070604 0x08070604 : {
        asm/matchings/sub_08070604.o(.text)
    } > ROM
    .rom_gap_0070660 0x08070660 : {
        asm/rom_gap_0070660.o(.rodata)
    } > ROM
    .rom_sub_08070678 0x08070678 : {
        asm/matchings/sub_08070678.o(.text)
    } > ROM
    .rom_sub_0807069C 0x0807069C : {
        asm/matchings/sub_0807069C.o(.text)
    } > ROM
    .rom_sub_080706B0 0x080706B0 : {
        asm/matchings/sub_080706B0.o(.text)
    } > ROM
    .rom_gap_0070922 0x08070922 : {
        asm/rom_gap_0070922.o(.rodata)
    } > ROM
    .rom_sub_08070930 0x08070930 : {
        asm/matchings/sub_08070930.o(.text)
    } > ROM
    .rom_sub_08070AD4 0x08070AD4 : {
        asm/matchings/sub_08070AD4.o(.text)
    } > ROM
    .rom_gap_0070AF6 0x08070AF6 : {
        asm/rom_gap_0070AF6.o(.rodata)
    } > ROM
    .rom_sub_08070AF8 0x08070AF8 : {
        asm/matchings/sub_08070AF8.o(.text)
    } > ROM
    .rom_sub_08070C98 0x08070C98 : {
        asm/matchings/sub_08070C98.o(.text)
    } > ROM
    .rom_gap_0070CB6 0x08070CB6 : {
        asm/rom_gap_0070CB6.o(.rodata)
    } > ROM
    .rom_sub_08070D44 0x08070D44 : {
        asm/matchings/sub_08070D44.o(.text)
    } > ROM
    .rom_sub_08070DF4 0x08070DF4 : {
        asm/matchings/sub_08070DF4.o(.text)
    } > ROM
    .rom_gap_0070E16 0x08070E16 : {
        asm/rom_gap_0070E16.o(.rodata)
    } > ROM
    .rom_sub_080712CC 0x080712CC : {
        asm/matchings/sub_080712CC.o(.text)
    } > ROM
    .rom_gap_0071304 0x08071304 : {
        asm/rom_gap_0071304.o(.rodata)
    } > ROM
    .rom_sub_0807179C 0x0807179C : {
        asm/matchings/sub_0807179C.o(.text)
    } > ROM
    .rom_gap_00717EE 0x080717EE : {
        asm/rom_gap_00717EE.o(.rodata)
    } > ROM
    .rom_sub_080717F0 0x080717F0 : {
        asm/matchings/sub_080717F0.o(.text)
    } > ROM
    .rom_sub_08071808 0x08071808 : {
        asm/matchings/sub_08071808.o(.text)
    } > ROM
    .rom_gap_0071814 0x08071814 : {
        asm/rom_gap_0071814.o(.rodata)
    } > ROM
    .rom_sub_08071B4C 0x08071B4C : {
        asm/matchings/sub_08071B4C.o(.text)
    } > ROM
    .rom_sub_08071BA0 0x08071BA0 : {
        asm/matchings/sub_08071BA0.o(.text)
    } > ROM
    .rom_gap_0071C34 0x08071C34 : {
        asm/rom_gap_0071C34.o(.rodata)
    } > ROM
    .rom_sub_08071E04 0x08071E04 : {
        asm/matchings/sub_08071E04.o(.text)
    } > ROM
    .rom_sub_08071E44 0x08071E44 : {
        asm/matchings/sub_08071E44.o(.text)
    } > ROM
    .rom_sub_08071E84 0x08071E84 : {
        asm/matchings/sub_08071E84.o(.text)
    } > ROM
    .rom_sub_08071EE4 0x08071EE4 : {
        asm/matchings/sub_08071EE4.o(.text)
    } > ROM
    .rom_sub_08071F44 0x08071F44 : {
        asm/matchings/sub_08071F44.o(.text)
    } > ROM
    .rom_sub_08071F84 0x08071F84 : {
        asm/matchings/sub_08071F84.o(.text)
    } > ROM
    .rom_sub_08071F98 0x08071F98 : {
        asm/matchings/sub_08071F98.o(.text)
    } > ROM
    .rom_sub_08071FAC 0x08071FAC : {
        asm/matchings/sub_08071FAC.o(.text)
    } > ROM
    .rom_gap_0071FC6 0x08071FC6 : {
        asm/rom_gap_0071FC6.o(.rodata)
    } > ROM
    .rom_sub_08071FC8 0x08071FC8 : {
        asm/matchings/sub_08071FC8.o(.text)
    } > ROM
    .rom_gap_0071FE6 0x08071FE6 : {
        asm/rom_gap_0071FE6.o(.rodata)
    } > ROM
    .rom_sub_080720F0 0x080720F0 : {
        asm/matchings/sub_080720F0.o(.text)
    } > ROM
    .rom_gap_0072118 0x08072118 : {
        asm/rom_gap_0072118.o(.rodata)
    } > ROM
    .rom_sub_080726A4 0x080726A4 : {
        asm/matchings/sub_080726A4.o(.text)
    } > ROM
    .rom_gap_00726DE 0x080726DE : {
        asm/rom_gap_00726DE.o(.rodata)
    } > ROM
    .rom_sub_080726E0 0x080726E0 : {
        asm/matchings/sub_080726E0.o(.text)
    } > ROM
    .rom_gap_0072714 0x08072714 : {
        asm/rom_gap_0072714.o(.rodata)
    } > ROM
    .rom_sub_08072A38 0x08072A38 : {
        asm/matchings/sub_08072A38.o(.text)
    } > ROM
    .rom_gap_0072B32 0x08072B32 : {
        asm/rom_gap_0072B32.o(.rodata)
    } > ROM
    .rom_sub_08072CC0 0x08072CC0 : {
        asm/matchings/sub_08072CC0.o(.text)
    } > ROM
    .rom_gap_0072CD8 0x08072CD8 : {
        asm/rom_gap_0072CD8.o(.rodata)
    } > ROM
    .rom_sub_08072F94 0x08072F94 : {
        asm/matchings/sub_08072F94.o(.text)
    } > ROM
    .rom_gap_0072FA8 0x08072FA8 : {
        asm/rom_gap_0072FA8.o(.rodata)
    } > ROM
    .rom_sub_08073078 0x08073078 : {
        asm/matchings/sub_08073078.o(.text)
    } > ROM
    .rom_gap_007309A 0x0807309A : {
        asm/rom_gap_007309A.o(.rodata)
    } > ROM
    .rom_sub_0807309C 0x0807309C : {
        asm/matchings/sub_0807309C.o(.text)
    } > ROM
    .rom_sub_08073114 0x08073114 : {
        asm/matchings/sub_08073114.o(.text)
    } > ROM
    .rom_sub_08073184 0x08073184 : {
        asm/matchings/sub_08073184.o(.text)
    } > ROM
    .rom_gap_00731A8 0x080731A8 : {
        asm/rom_gap_00731A8.o(.rodata)
    } > ROM
    .rom_sub_080731F4 0x080731F4 : {
        asm/matchings/sub_080731F4.o(.text)
    } > ROM
    .rom_sub_08073218 0x08073218 : {
        asm/matchings/sub_08073218.o(.text)
    } > ROM
    .rom_gap_007325A 0x0807325A : {
        asm/rom_gap_007325A.o(.rodata)
    } > ROM
    .rom_sub_0807339C 0x0807339C : {
        asm/matchings/sub_0807339C.o(.text)
    } > ROM
    .rom_gap_00733BA 0x080733BA : {
        asm/rom_gap_00733BA.o(.rodata)
    } > ROM
    .rom_sub_080733BC 0x080733BC : {
        asm/matchings/sub_080733BC.o(.text)
    } > ROM
    .rom_sub_080733E4 0x080733E4 : {
        asm/matchings/sub_080733E4.o(.text)
    } > ROM
    .rom_gap_007343E 0x0807343E : {
        asm/rom_gap_007343E.o(.rodata)
    } > ROM
    .rom_sub_08073440 0x08073440 : {
        asm/matchings/sub_08073440.o(.text)
    } > ROM
    .rom_gap_007348A 0x0807348A : {
        asm/rom_gap_007348A.o(.rodata)
    } > ROM
    .rom_sub_08073568 0x08073568 : {
        asm/matchings/sub_08073568.o(.text)
    } > ROM
    .rom_gap_00735AE 0x080735AE : {
        asm/rom_gap_00735AE.o(.rodata)
    } > ROM
    .rom_sub_080735B0 0x080735B0 : {
        asm/matchings/sub_080735B0.o(.text)
    } > ROM
    .rom_gap_00735DA 0x080735DA : {
        asm/rom_gap_00735DA.o(.rodata)
    } > ROM
    .rom_sub_080735DC 0x080735DC : {
        asm/matchings/sub_080735DC.o(.text)
    } > ROM
    .rom_gap_0073660 0x08073660 : {
        asm/rom_gap_0073660.o(.rodata)
    } > ROM
    .rom_sub_080737C0 0x080737C0 : {
        asm/matchings/sub_080737C0.o(.text)
    } > ROM
    .rom_sub_08073910 0x08073910 : {
        asm/matchings/sub_08073910.o(.text)
    } > ROM
    .rom_gap_0073986 0x08073986 : {
        asm/rom_gap_0073986.o(.rodata)
    } > ROM
    .rom_sub_08073988 0x08073988 : {
        asm/matchings/sub_08073988.o(.text)
    } > ROM
    .rom_sub_080739E8 0x080739E8 : {
        asm/matchings/sub_080739E8.o(.text)
    } > ROM
    .rom_gap_0073A0C 0x08073A0C : {
        asm/rom_gap_0073A0C.o(.rodata)
    } > ROM
    .rom_sub_08073A28 0x08073A28 : {
        asm/matchings/sub_08073A28.o(.text)
    } > ROM
    .rom_gap_0073A6A 0x08073A6A : {
        asm/rom_gap_0073A6A.o(.rodata)
    } > ROM
    .rom_sub_08073AEC 0x08073AEC : {
        asm/matchings/sub_08073AEC.o(.text)
    } > ROM
    .rom_gap_0073B8E 0x08073B8E : {
        asm/rom_gap_0073B8E.o(.rodata)
    } > ROM
    .rom_sub_08074144 0x08074144 : {
        asm/matchings/sub_08074144.o(.text)
    } > ROM
    .rom_tail 0x08074146 : {
        asm/rom_tail.o(.rodata)
    } > ROM
