#!/usr/bin/env python3
"""Turns the thought-bubble art into ROM data.

    gen_bubbles.py <mod dir> <build dir>

Reads <mod dir>/bubbles.txt and every assets/<name>.png it names and
writes, into <build dir>:

    <name>.4bpp    4096 bytes, the 128x64 picture as two 64x64 OBJ sprites
                     (left half first), 4bpp, 1D tile order
    <name>.pal     32 bytes, 16 BGR555 colours; index 0 is transparent
    bubble_data.s    gBubbleImages / gBubbleFlags, which src/bubbles.c reads

A PNG may be indexed (at most 16 colours, index 0 transparent) or any RGBA
image: transparent pixels (alpha < 128) become index 0 and the rest is
quantized to 15 colours.
"""

import os
import sys

from PIL import Image

WIDTH, HEIGHT = 128, 64


def to_indexed(path):
    """-> (pixels as a list of 0..15 per pixel, row-major; 16 (r, g, b) colours)."""
    img = Image.open(path)
    if img.size != (WIDTH, HEIGHT):
        sys.exit("%s: expected %dx%d, got %dx%d" % (path, WIDTH, HEIGHT, *img.size))
    if img.mode == "P" and max(img.tobytes()) < 16:
        pal = (img.getpalette() or []) + [0] * 48
        return list(img.tobytes()), [tuple(pal[i * 3:i * 3 + 3]) for i in range(16)]
    rgba = img.convert("RGBA")
    raw = rgba.tobytes()
    mask = [raw[i + 3] >= 128 for i in range(0, len(raw), 4)]
    pixels = [tuple(raw[i:i + 3]) for i in range(0, len(raw), 4)]
    # Transparent pixels must not pull colours into the palette: paint them
    # with the first opaque pixel before quantizing.
    opaque = next((p for p, m in zip(pixels, mask) if m), (0, 0, 0))
    flat = Image.new("RGB", (WIDTH, HEIGHT))
    flat.putdata([p if m else opaque for p, m in zip(pixels, mask)])
    q = flat.quantize(colors=15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    pal = (q.getpalette() or []) + [0] * 48
    colours = [(0, 0, 0)] + [tuple(pal[i * 3:i * 3 + 3]) for i in range(15)]
    px = [i + 1 if m else 0 for i, m in zip(q.tobytes(), mask)]
    return px, colours


def tiles_4bpp(px):
    """Two 64x64 sprites, left then right; each is 8x8 tiles in row-major order."""
    out = bytearray()
    for half in range(2):
        for ty in range(8):
            for tx in range(8):
                for row in range(8):
                    y = ty * 8 + row
                    for col in range(0, 8, 2):
                        x = half * 64 + tx * 8 + col
                        out.append(px[y * WIDTH + x] | (px[y * WIDTH + x + 1] << 4))
    return bytes(out)


def bgr555(c):
    r, g, b = c
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def parse(path):
    images, flags = [], []
    for n, line in enumerate(open(path), 1):
        line = line.split("#")[0].split()
        if not line:
            continue
        if line[0] == "image" and len(line) == 3:
            images.append((line[1], line[2]))
        elif line[0] == "flag" and len(line) == 3:
            flags.append((int(line[1], 0), line[2], n))
        else:
            sys.exit("%s:%d: expected 'image <ID> <name>' or 'flag <number> <ID>'" % (path, n))
    return images, flags


def main():
    mod, out = sys.argv[1:3]
    images, flags = parse(os.path.join(mod, "bubbles.txt"))
    if not images or images[0][0] != "DEFAULT":
        sys.exit("bubbles.txt: the first image must be DEFAULT (shown when no flag matches)")
    ids = [i for i, _ in images]
    if len(set(ids)) != len(ids):
        sys.exit("bubbles.txt: duplicate image ID")
    seen = set()
    for flag, ident, n in flags:
        if not 0 <= flag <= 255:
            sys.exit("bubbles.txt:%d: event flags are 0..255" % n)
        if flag in seen:
            sys.exit("bubbles.txt:%d: flag %d is listed twice" % (n, flag))
        if ident not in ids:
            sys.exit("bubbles.txt:%d: unknown image %s" % (n, ident))
        seen.add(flag)

    os.makedirs(out, exist_ok=True)
    lines = ['@ Generated by mods/thought_bubbles/tools/gen_bubbles.py. Do not edit.',
             '\t.section .rodata', '\t.align 2', '\t.global gBubbleImages', 'gBubbleImages:']
    for i in range(len(images)):
        lines.append('\t.4byte gBubbleTiles%d, gBubblePal%d' % (i, i))
    lines += ['', '\t.global gBubbleFlags', 'gBubbleFlags:']
    for flag, ident, _ in flags:
        lines.append('\t.2byte %d, %d' % (flag, ids.index(ident)))
    lines += ['\t.2byte 0xFFFF, 0', '']
    for i, (ident, name) in enumerate(images):
        png = os.path.join(mod, "assets", name + ".png")
        px, colours = to_indexed(png)
        base = os.path.join(out, name)
        open(base + ".4bpp", "wb").write(tiles_4bpp(px))
        pal = b"".join(bgr555(c).to_bytes(2, "little") for c in colours)
        open(base + ".pal", "wb").write(pal)
        lines += ['\t.align 2', 'gBubbleTiles%d:' % i, '\t.incbin "%s.4bpp"' % base,
                  '\t.align 2', 'gBubblePal%d:' % i, '\t.incbin "%s.pal"' % base]
    open(os.path.join(out, "bubble_data.s"), "w").write("\n".join(lines) + "\n")


main()
