#include "debug_menu.h"

/* What each menu entry does. Entries that hold a value (stats, credits, bit
 * beast experience, characters) are enforced every overworld frame and
 * restored when switched off. Entries that give things (beyblades, parts)
 * act once when switched on and take back only what they added when switched
 * off. Everything lives in gDebug. */

#define MAX_STRENGTH 99
#define MAX_EXP 0x3FFF /* retail cap, see BtlApplyClampedScore */
#define LEVEL_EXP 4000 /* first experience of the top level (16) */
#define MAX_CREDITS 99999
#define MAX_BITBEAST_EXP 0x3FFF
#define MAX_LAUNCH_RPM 32767 /* largest value the retail signed spin step takes */

#define BLADER_MET 0x01 /* BeybladeCollectionEntry row, byte +7 */

/* Inventory entries are {kind (item id), slot, value (wear), group (category)}.
 * Group 1 is beyblades, groups 2 and 3 are ripcords and launchers. */
#define GROUP_BEYBLADE 1
#define NEW_BEYBLADE_VALUE 0xFF /* "take the template", as the shop does */
#define NEW_PART_VALUE 100
#define PART_VALUE_SAFE 0x7F /* survives one wear step of kind + strength */

extern s32 CollectionAddItem(u8 kind, u8 group, u8 slot, u8 value);
extern s32 CollectionFindByGroupKind(s8 group, s8 kind, struct CollectionLookup *out);
extern s32 CollectionFindByGroupSlot(s8 group, u8 slot, struct CollectionLookup *out);
extern void CollectionFreeSlot(u16 kind, u8 group, s16 index);
extern s32 BattlePartsApplyWear(void);
extern s32 ExpBracketBase(s32 level);
extern s32 ExpBracketTop(s32 level);
extern s16 ScaleRatio(s32 a, s32 b, s32 c);
extern void _0803CECC(void);
extern void _08041E88(void *dir, s32 speed);
extern void _0805FED4(void *track);

/* ---- world map --------------------------------------------------------- */

/* The map's spots, in the order of the saved flag bytes (MapNodeMask below).
 * A spot's flag byte says which of its four paths are walkable (bit 0x10 << d
 * for link[d]: up, down, right, left) and, in the low nibble, whether the
 * spot can be entered with A. The game seeds the byte from `open` and sets
 * more bits as the story opens paths; link[d] is where the path leads, 0 if
 * the art has none. */
struct MapNode {
    u8 open;
    u8 index;
    u8 pad[2];
    const struct MapNode *link[4];
};

extern const struct MapNode *const gMapNodes[MAP_NODES];

/* ---- character --------------------------------------------------------- */

/* Character `n` (1..CHARACTER_COUNT) is gCharacterLooks[n - 1], generated by
 * tools/gen_looks.py: a walking sprite and palette plus the blader portrait
 * index (tables at 0x08091004 / 0x080910E8; 56 is the player's own). The
 * player becomes that person on four fronts: the walking sprite, the HUD
 * portrait, the HUD strength / experience / level (the blader's own row, as
 * the game shows them for a partner) and the dialogue portrait (script
 * opcode 29). */
#define HERO_SPRITE 0x083147C8
#define HERO_PALETTE 0x083002E0
#define HERO_PORTRAIT 56
#define HERO_DIALOGUE_TEMPLATE 0x08266DAC
/* The HUD draws its digits and bars with the portrait's palette (slot 2), so
 * another face needs a palette slot of its own. */
#define FACE_SLOT 13

extern u32 *_0805A304(u32 *script, u32 *enabled);

const char *CharacterName(u32 value)
{
    static char buf[12];
    u32 portrait = value == 0 ? HERO_PORTRAIT : gCharacterLooks[value - 1].portrait;
    u32 n;
    s32 len = 0;
    char tmp[4];
    char *p = buf;

    if (value != 0 && gCharacterLooks[value - 1].name != NULL)
        return gCharacterLooks[value - 1].name;
    if (portrait != HERO_PORTRAIT || value == 0)
        return (const char *)BeybladeGetName(portrait);
    *p++ = 'N';
    *p++ = 'P';
    *p++ = 'C';
    *p++ = ' ';
    n = gCharacterLooks[value - 1].npc;
    do {
        tmp[len++] = '0' + n % 10;
        n /= 10;
    } while (n != 0);
    while (len > 0)
        *p++ = tmp[--len];
    *p = 0;
    return buf;
}

/* The parts with a fixed catalogue: first and last id per inventory group.
 * Ripcords and launchers are numbered from 1; bit chips from 0 (Dragoon, the
 * starting chip, is group 7 id 0). Blade bases, attack rings and weight disks
 * (groups 4 to 6) are open-ended stat tables that the game hands out piece by
 * piece, so there is no complete set to give. */

struct PartRange {
    u8 group;
    u8 first;
    u8 last;
};

static const struct PartRange sParts[] = {
    {GROUP_RIPCORD, 1, 4},
    {GROUP_LAUNCHER, 1, 4},
    {GROUP_BITCHIP, 0, 6},
};

static u8 *Row(u32 i)
{
    return (u8 *)BeybladeCollectionEntry(i);
}

static s16 *RowExp(u32 i)
{
    return (s16 *)Row(i);
}

/* ---- values held while an entry is on ---------------------------------- */

static void HoldStrength(void)
{
    struct MainWork *w = gMainWorkPtr;

    if (gDebug.value[DBG_MAX_STR]) {
        if (!gDebug.hasStrength) {
            gDebug.strength = w->strength;
            gDebug.hasStrength = 1;
        }
        w->strength = MAX_STRENGTH;
    } else if (gDebug.hasStrength) {
        w->strength = gDebug.strength;
        gDebug.hasStrength = 0;
    }
}

static void HoldExp(void)
{
    struct MainWork *w = gMainWorkPtr;
    s32 want = -1;

    if (gDebug.value[DBG_MAX_LEVEL])
        want = LEVEL_EXP;
    if (gDebug.value[DBG_MAX_EXP])
        want = MAX_EXP;

    if (want >= 0) {
        if (!gDebug.hasExp) {
            gDebug.exp = w->expPoints;
            gDebug.hasExp = 1;
        }
        w->expPoints = want;
    } else if (gDebug.hasExp) {
        w->expPoints = gDebug.exp;
        gDebug.hasExp = 0;
    }
}

static void HoldCredits(void)
{
    struct MainWork *w = gMainWorkPtr;

    if (gDebug.value[DBG_MAX_CREDITS]) {
        if (!gDebug.hasCredits) {
            gDebug.credits = w->unk0870;
            gDebug.hasCredits = 1;
        }
        w->unk0870 = MAX_CREDITS;
    } else if (gDebug.hasCredits) {
        w->unk0870 = gDebug.credits;
        gDebug.hasCredits = 0;
    }
}

/* Every blader whose blade the player has collected (the rows "Meet bladers"
 * lists) gets full bit beast experience. */
static void HoldBitBeastExp(void)
{
    s32 i;

    for (i = 0; i < BLADER_ROWS; i++) {
        u8 *row = Row(i);
        bool32 want = gDebug.value[DBG_MAX_BITBEAST_EXP] && (row[7] & BLADER_MET);

        if (want) {
            if (!gDebug.touchedRow[i]) {
                gDebug.rowExp[i] = *RowExp(i);
                gDebug.touchedRow[i] = 1;
            }
            *RowExp(i) = MAX_BITBEAST_EXP;
        } else if (gDebug.touchedRow[i]) {
            *RowExp(i) = gDebug.rowExp[i];
            gDebug.touchedRow[i] = 0;
        }
    }
}

/* "Meet bladers" lists every row whose byte +7 has bit 0 set. */
static void HoldCharacters(void)
{
    s32 i;

    if (gDebug.value[DBG_ALL_CHARACTERS]) {
        if (!gDebug.charactersOn) {
            for (i = 0; i < BLADER_ROWS; i++) {
                u8 *row = Row(i);

                gDebug.rowFlags[i] = row[7] & BLADER_MET;
                row[7] |= BLADER_MET;
            }
            gDebug.charactersOn = 1;
        }
    } else if (gDebug.charactersOn) {
        for (i = 0; i < BLADER_ROWS; i++) {
            u8 *row = Row(i);

            row[7] = (row[7] & ~BLADER_MET) | gDebug.rowFlags[i];
        }
        gDebug.charactersOn = 0;
    }
}

/* Opens every path and spot of the world map. The map's flag bytes live in
 * the saved map block (gUnk_03000554, bytes 8..23): each spot gets its start
 * state plus every path the art draws. Only the bits the cheat adds are taken
 * back when it is switched off. */
static u8 MapNodeMask(s32 i)
{
    const struct MapNode *node = gMapNodes[i];
    u8 mask = node->open;
    s32 d;

    for (d = 0; d < 4; d++) {
        if (node->link[d] != NULL)
            mask |= 0x10 << d;
    }
    return mask;
}

static void HoldLocations(void)
{
    struct Unk0554 *map = gUnk_03000554;
    s32 i;

    if (map == NULL)
        return;
    if (gDebug.value[DBG_ALL_LOCATIONS]) {
        for (i = 0; i < MAP_NODES; i++) {
            u8 mask = MapNodeMask(i);

            if (!gDebug.locationsOn)
                gDebug.nodeAdded[i] = mask & ~map->unk08[i];
            map->unk08[i] |= mask;
        }
        gDebug.locationsOn = 1;
    } else if (gDebug.locationsOn) {
        for (i = 0; i < MAP_NODES; i++)
            map->unk08[i] &= ~gDebug.nodeAdded[i];
        gDebug.locationsOn = 0;
    }
}

/* Makes the player look like the chosen person. Rebuilt whenever the game has
 * put the originals back (a map change rebuilds the HUD and clears the palette
 * slots). Value 0 puts the originals back once; the HUD refresh that runs just
 * before this redraws the player's own numbers. */
/* The face template and palette of a character: its blader's portrait, or the
 * dialogue portrait of an NPC that has none. */
static void *FaceTemplate(u32 portrait, const struct CharacterLook *look)
{
    return look != NULL && look->faceTemplate != 0 ? (void *)look->faceTemplate : (void *)BeybladeGetActorSprite(portrait);
}

static void *FacePalette(u32 portrait, const struct CharacterLook *look)
{
    return look != NULL && look->faceTemplate != 0 ? (void *)look->facePalette : (void *)BeybladeGetActorPalette(portrait);
}

static void HoldCharacter(void)
{
    u32 value = gDebug.value[DBG_CHARACTER];
    struct AnimObj *hero = (struct AnimObj *)&gMainWorkPtr->unk036C;
    struct StatusHud *hud = gUnk_0300026C;
    u32 *slots = (u32 *)gUnk_030008D0;
    u32 sprite = value != 0 ? gCharacterLooks[value - 1].sprite : HERO_SPRITE;
    u32 palette = value != 0 ? gCharacterLooks[value - 1].palette : HERO_PALETTE;
    u32 portrait = HERO_PORTRAIT;
    bool32 any = value != 0;
    const struct CharacterLook *look = value != 0 ? &gCharacterLooks[value - 1] : NULL;
    struct Sprite *face;
    struct Unk42E78 *row;

    if (!any && !gDebug.characterOn)
        return;
    if (value != 0)
        portrait = gCharacterLooks[value - 1].portrait;
    gDebug.characterOn = any;

    if (hero->data != (void *)sprite) {
        SceneObjFreeResources((struct Actor *)hero);
        hero->data = (void *)sprite;
        SceneObjUpdate(hero);
        sub_08067CE8(hero, 0);
    }
    /* The game keeps the source of each loaded palette slot at
     * gUnk_030008D0[slot]; a map change clears it, so a mismatch means the
     * palette has to be loaded again. */
    if (slots != NULL && slots[0] != palette)
        ObjPalLoadSlot(0, (void *)palette);

    face = hud != NULL ? hud->unk0C : NULL;
    if (face == NULL)
        return;
    if (face->unk2C != FaceTemplate(portrait, look)) {
        SpriteInitFromTemplate(face, FaceTemplate(portrait, look), face->unk08, face->unk0C, 0, 1, 0, 0);
        TextEntrySetPaletteBank(face, FACE_SLOT);
    }
    if (slots != NULL && slots[FACE_SLOT] != (u32)FacePalette(portrait, look))
        ObjPalLoadSlot(FACE_SLOT, FacePalette(portrait, look));

    if (value != 0 && portrait != HERO_PORTRAIT) {
        row = BeybladeCollectionEntry(portrait);
        HudWriteDigits((struct Unk310F0b *)hud->playerStrengthTens, (struct Unk310F0b *)hud->playerStrengthOnes,
                       row->strength);
        HudWriteDigits((struct Unk310F0b *)hud->playerLevelTens, (struct Unk310F0b *)hud->playerLevelOnes,
                       ExpBracket(row->bitBeastExp));
        if (hud->playerExpBar != NULL)
            hud->playerExpBar->unk18 = ExpBarFill(row->bitBeastExp);
    }
}

/* ---- things given once ------------------------------------------------- */

static void GiveBeyblades(void)
{
    s32 id;

    if (gDebug.value[DBG_ALL_BEYBLADES]) {
        if (gDebug.bladesOn)
            return;
        for (id = 0; id < BEYBLADE_IDS; id++) {
            if (CollectionFindByGroupKind(GROUP_BEYBLADE, id, NULL))
                continue;
            if (CollectionAddItem(id, GROUP_BEYBLADE, 0, NEW_BEYBLADE_VALUE))
                gDebug.blades[id >> 3] |= 1 << (id & 7);
        }
        gDebug.bladesOn = 1;
    } else if (gDebug.bladesOn) {
        for (id = 0; id < BEYBLADE_IDS; id++) {
            struct CollectionLookup out;

            if (!(gDebug.blades[id >> 3] & (1 << (id & 7))))
                continue;
            if (CollectionFindByGroupKind(GROUP_BEYBLADE, id, &out))
                CollectionFreeSlot(out.kind, GROUP_BEYBLADE, out.index);
            gDebug.blades[id >> 3] &= ~(1 << (id & 7));
        }
        gDebug.bladesOn = 0;
    }
}

static void GiveParts(void)
{
    u32 r;
    s32 id;

    if (gDebug.value[DBG_ALL_PARTS]) {
        if (gDebug.partsOn)
            return;
        for (r = 0; r < sizeof(sParts) / sizeof(sParts[0]); r++) {
            for (id = sParts[r].first; id <= sParts[r].last; id++) {
                if (CollectionFindByGroupKind(sParts[r].group, id, NULL))
                    continue;
                if (CollectionAddItem(id, sParts[r].group, 0, NEW_PART_VALUE))
                    gDebug.parts[sParts[r].group] |= 1 << id;
            }
        }
        gDebug.partsOn = 1;
    } else if (gDebug.partsOn) {
        for (r = 0; r < sizeof(sParts) / sizeof(sParts[0]); r++) {
            for (id = sParts[r].first; id <= sParts[r].last; id++) {
                struct CollectionLookup out;

                if (!(gDebug.parts[sParts[r].group] & (1 << id)))
                    continue;
                if (CollectionFindByGroupKind(sParts[r].group, id, &out))
                    CollectionFreeSlot(out.kind, sParts[r].group, out.index);
                gDebug.parts[sParts[r].group] &= ~(1 << id);
            }
        }
        gDebug.partsOn = 0;
    }
}

/* ---- entry points ------------------------------------------------------ */

void CheatsTick(void)
{
    HoldStrength();
    HoldExp();
    HoldCredits();
    HoldCharacters();
    HoldLocations();
    HoldCharacter();
    HoldBitBeastExp();
    GiveBeyblades();
    GiveParts();
}

void CheatsOnToggle(u32 item)
{
    if (item == DBG_TURBINE)
        gDebug.turbine = 0;
    CheatsTick();
}

/* A value entry (speed, BGM, character) was changed with left/right. */
void CheatsOnChange(u32 item)
{
    if (item == DBG_BGM)
        _0805FED4((void *)(u32)gDebug.value[DBG_BGM]);
    else if (item == DBG_CHARACTER)
        HoldCharacter();
}

/* ---- hooks into retail code -------------------------------------------- */

/* Replaces the bl to EventFlagOp in sub_08043980 (map path art). */
void DebugMapFlag(u8 id, u32 op, u32 *out)
{
    EventFlagOp(id, op, out);
    if (gDebug.magic == DBG_MAGIC && gDebug.value[DBG_ALL_LOCATIONS] && op == 4)
        *out = 1;
}

/* Replaces the bls to ObjPalLoadSlot that load the player's palette (slot 0)
 * in MapLoadObjects. It runs before the first overworld frame, so gDebug may
 * not be initialised yet. */
void DebugObjPalLoad(u32 slot, void *src)
{
    if (gDebug.magic == DBG_MAGIC && gDebug.value[DBG_CHARACTER] != 0)
        src = (void *)gCharacterLooks[gDebug.value[DBG_CHARACTER] - 1].palette;
    ObjPalLoadSlot(slot, src);
}

/* Replaces opcode 29's entry in the script opcode table. The script names a
 * portrait template and palette; for the player's own, hand the handler the
 * chosen person's instead (a three-word copy: opcode, template, palette) and
 * map its returned script pointer back. */
u32 *DebugPortraitOp(u32 *script, u32 *enabled)
{
    u32 copy[3];
    u32 value;
    u32 *next;

    if (gDebug.magic != DBG_MAGIC || (value = gDebug.value[DBG_CHARACTER]) == 0
        || (gCharacterLooks[value - 1].portrait == HERO_PORTRAIT && gCharacterLooks[value - 1].faceTemplate == 0)
        || script[1] != HERO_DIALOGUE_TEMPLATE)
        return _0805A304(script, enabled);
    copy[0] = script[0];
    copy[1] = (u32)FaceTemplate(gCharacterLooks[value - 1].portrait, &gCharacterLooks[value - 1]);
    copy[2] = (u32)FacePalette(gCharacterLooks[value - 1].portrait, &gCharacterLooks[value - 1]);
    next = _0805A304(copy, enabled);
    return script + (next - copy);
}

/* Replaces the bl to sub_08041E88 in FieldUpdateFrame. */
void DebugMoveStep(void *dir, s32 speed)
{
    _08041E88(dir, speed * gDebug.value[DBG_MOVE_SPEED]);
}

/* Replaces both bls to BattlePartsApplyWear. Retail subtracts the part id plus
 * strength from the equipped launcher and ripcord and frees a part that drops
 * to 0. Pre-loading the health keeps that from happening. */
static void KeepPart(u32 item, s8 group)
{
    struct CollectionLookup out;

    if (gDebug.value[item] && CollectionFindByGroupSlot(group, 1, &out))
        out.entry->value = PART_VALUE_SAFE;
}

static void FullPart(u32 item, s8 group)
{
    struct CollectionLookup out;

    if (gDebug.value[item] && CollectionFindByGroupSlot(group, 1, &out))
        out.entry->value = NEW_PART_VALUE;
}

s32 DebugPartsApplyWear(void)
{
    s32 worn;

    KeepPart(DBG_INF_LAUNCHER, GROUP_LAUNCHER);
    KeepPart(DBG_INF_RIPCORD, GROUP_RIPCORD);
    worn = BattlePartsApplyWear();
    FullPart(DBG_INF_LAUNCHER, GROUP_LAUNCHER);
    FullPart(DBG_INF_RIPCORD, GROUP_RIPCORD);
    return worn;
}

/* Replaces the bl to _0803CECC (the launch RPM formula). Retail leaves the
 * player's launch RPM in the battle record and copies it to the live spin and
 * its cap; do the same with the maximum. The bit beast gauge also starts here:
 * BattleWork+0xBBC is player 0's gauge and +0xBC4 its capacity (0x2400 = 36
 * units of 256, three bars of 12); the fight adds 0x20 to it each tick. */
void DebugLaunch(void)
{
    u8 *battle;
    s32 rpm = MAX_LAUNCH_RPM;

    _0803CECC();
    AbilitiesBattleStart();
    battle = (u8 *)gBattleWork;
    if (gDebug.value[DBG_MAX_RPM]) {
        *(s32 *)(battle + 0xBB4) = rpm;
        *(s32 *)(battle + 0xBBC) = rpm;
        *(s32 *)(battle + 0xBC4) = rpm;
        *(s32 *)(battle + 0x13C) = rpm;
        *(s32 *)(battle + 0x144) = rpm;
        *(s32 *)(0x030002A0 + 12) = rpm;
    }
    if (gDebug.value[DBG_FULL_GAUGE])
        *(s32 *)(battle + 0xBBC) = *(s32 *)(battle + 0xBC4);
}

/* Replaces ExpBracket (sub_08042BE8). Identical, except that experience past
 * the last threshold gives the last level; retail returned -1 there, which
 * broke the HUD from 4000 experience on. */
s32 ExpBracketFixed(s32 points)
{
    s32 i;

    for (i = 0; gData_080908BC[i].level != -1; i++) {
        if (points >= gData_080908BC[i].minPoints
            && (gData_080908BC[i + 1].level == -1 || points < gData_080908BC[i + 1].minPoints))
            return gData_080908BC[i].level;
    }
    return -1;
}

/* Replaces ExpBarFill (sub_0802E1B4): a full bar on the last level, which has
 * no upper threshold. */
s8 ExpBarFillFixed(s32 points)
{
    s32 level = sub_08042BE8(points);
    s32 base = ExpBracketBase(level);
    s32 top = ExpBracketTop(level);

    if (top == -1)
        return 14;
    return 14 - ScaleRatio(top - points, top - base, 14);
}
