#!/usr/bin/env python3
"""Turns opponents.json into ROM data for the fixed_opponents mod.

    gen_opponents.py <mod dir> <build dir>     writes <build dir>/opponent_data.s
    gen_opponents.py <mod dir> --list          prints every opponent with the launch RPM range
    gen_opponents.py <mod dir> --init          rewrites opponents.json from the ROM's start values

opponents.json lists the 55 blader rows ("row" 0..54, the game's blader order).
Per entry:

    exp          character experience, 0..16383   (default: the ROM's start value)
    strength     0..127                           (default: the ROM's start value)
    beast_exp    blade bit beast experience, 0..16383
                 (default: not touched, so the value the save holds stays)

A row that is not listed, or a field that is left out, keeps the ROM's start
value. "name" is only a label for you.

The opponent's launch RPM follows the player's formula (docs/mechanics.md):
    base = exp + beast_exp, quot = (base << 16) / 25600
    rpm  = (quot * (power << 8) >> 16) + (quot * (boost << 8) >> 16) + strength * (power + boost)
    +25% when power and boost are both above 94
with power a random 80..99 and boost a random 75..99.
"""

import json
import os
import struct
import sys

ROWS = 55
ROM_TABLE = 0x909C4          # 8 bytes per row: s16 exp, u8, u8 strength, 4 more
NAME_TABLE = 0x90FF0         # pointer to the per-language name pointer tables
EXP_MAX = 0x3FFF


def rom(mod_dir):
    path = os.path.join(mod_dir, "..", "..", "baserom.gba")
    with open(path, "rb") as f:
        return f.read()


def word(r, addr):
    return struct.unpack_from("<I", r, addr - 0x08000000)[0]


def rom_defaults(r):
    out = []
    for i in range(ROWS):
        exp, = struct.unpack_from("<H", r, ROM_TABLE + i * 8)
        out.append((exp, r[ROM_TABLE + i * 8 + 3]))
    return out


def rom_names(r):
    table = word(r, 0x08000000 + NAME_TABLE)
    names = []
    for i in range(ROWS):
        p = word(r, table + 4 * i) - 0x08000000
        names.append(r[p:p + 24].split(b"\0")[0].decode("ascii", "replace"))
    return names


def launch_range(exp, strength, beast):
    quot = ((exp + beast) << 16) // 25600

    def rpm(power, boost):
        v = (quot * (power << 8) >> 16) + (quot * (boost << 8) >> 16) + strength * (power + boost)
        return v + (v >> 2) if power > 94 and boost > 94 else v

    return rpm(80, 75), rpm(99, 99)


def load(mod_dir):
    r = rom(mod_dir)
    defaults = rom_defaults(r)
    names = rom_names(r)
    with open(os.path.join(mod_dir, "opponents.json")) as f:
        entries = json.load(f)["opponents"]
    rows = [{"exp": e, "strength": s, "beast_exp": None, "name": names[i]} for i, (e, s) in enumerate(defaults)]
    seen = set()
    for e in entries:
        row = e.get("row")
        if not isinstance(row, int) or not 0 <= row < ROWS:
            sys.exit("opponents.json: 'row' must be 0..%d, got %r" % (ROWS - 1, row))
        if row in seen:
            sys.exit("opponents.json: row %d is listed twice" % row)
        seen.add(row)
        for key, hi in (("exp", EXP_MAX), ("strength", 127), ("beast_exp", EXP_MAX)):
            if e.get(key) is None:
                continue
            if not isinstance(e[key], int) or not 0 <= e[key] <= hi:
                sys.exit("opponents.json: row %d: %s must be an integer 0..%d, got %r" % (row, key, hi, e[key]))
            rows[row][key] = e[key]
    return rows


def main():
    mod_dir, arg = sys.argv[1], sys.argv[2]
    if arg == "--init":
        r = rom(mod_dir)
        names = rom_names(r)
        rows = ['    {"row": %d, "name": "%s", "exp": %d, "strength": %d}' % (i, names[i], e, st)
                for i, (e, st) in enumerate(rom_defaults(r))]
        with open(os.path.join(mod_dir, "opponents.json"), "w") as f:
            f.write('{\n  "opponents": [\n' + ",\n".join(rows) + "\n  ]\n}\n")
        return
    rows = load(mod_dir)
    if arg == "--list":
        print("row  name        exp  str  beast   launch RPM")
        for i, o in enumerate(rows):
            lo, hi = launch_range(o["exp"], o["strength"], o["beast_exp"] or 0)
            beast = "-" if o["beast_exp"] is None else o["beast_exp"]
            print("%3d  %-9s %5d %4d %6s   %d - %d" % (i, o["name"], o["exp"], o["strength"], beast, lo, hi))
        return
    # Per row, 8 bytes: u16 exp, u8 strength, u8 has_beast, u16 beast_exp, u16 pad.
    lines = ["@ Generated by mods/fixed_opponents/tools/gen_opponents.py from opponents.json; do not edit.",
             "\t.section .rodata", "\t.align 2", "\t.global gOpponentRows", "gOpponentRows:"]
    for i, o in enumerate(rows):
        b = o["beast_exp"]
        lines.append("\t.2byte %d\n\t.byte %d, %d\n\t.2byte %d, 0 @ %d %s" %
                     (o["exp"], o["strength"], 0 if b is None else 1, b or 0, i, o["name"]))
    os.makedirs(arg, exist_ok=True)
    with open(os.path.join(arg, "opponent_data.s"), "w") as f:
        f.write("\n".join(lines) + "\n")


main()
