#!/usr/bin/env python3
"""Narrative documentation generated from the analysis database.

The scoreboard in `docs/decomp-functions.md` answers "how much is done". These
pages answer "what is this". They are generated views of `analysis/*.json` and
`analysis/symbols.json`, so they always use the current readable names and are
never hand-edited.

  docs/systems/index.md      subsystem overview
  docs/systems/<system>.md   member functions, grouped and named
  docs/functions/index.md    every function, searchable by name and address
  docs/functions/<Name>.md   one page per *named* function

Unnamed functions get no page: there is nothing readable to title it with. They
still appear in the index and on their subsystem page, so nothing is hidden.

  python3 tools/decomp/document.py
  python3 tools/decomp/document.py --all      # a page per function, not just named
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
ANALYSIS = ROOT / "analysis"
DOCS = ROOT / "docs"
SYSTEMS_DIR = DOCS / "systems"
FUNCTIONS_DIR = DOCS / "functions"

_BANNER = (
    "<!-- AUTO-GENERATED by tools/decomp/document.py - do not edit. -->\n"
    "<!-- Regenerate with `make document`. -->\n"
)


def _load(name: str) -> dict[str, Any]:
    path = ANALYSIS / name
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def display_name(row: dict[str, Any], symbols: dict[str, Any]) -> str:
    entry = symbols.get(row.get("addr", "")) or {}
    return str(entry.get("symbol") or row.get("name") or "")


def _link(
    row: dict[str, Any],
    symbols: dict[str, Any],
    *,
    all_pages: bool,
    prefix: str = "",
) -> str:
    """Markdown link to the function page when one exists, else plain code."""
    name = row["name"]
    display = display_name(row, symbols)
    entry = symbols.get(row.get("addr", "")) or {}
    has_page = bool(entry.get("symbol")) or all_pages
    if has_page and display:
        return f"[`{display}`]({prefix}{display}.md)"
    return f"`{display or name}`"


def render_system(
    system: str,
    members: list[str],
    by_name: dict[str, dict[str, Any]],
    symbols: dict[str, Any],
    membership: dict[str, Any],
    *,
    all_pages: bool,
) -> str:
    rows = [by_name[m] for m in members if m in by_name]
    rows.sort(key=lambda r: (-len(r.get("callers") or []), r["addr"]))

    named = sum(1 for r in rows if symbols.get(r.get("addr")))
    tiers: dict[str, int] = {}
    for row in rows:
        tiers[row.get("tier", "UNKNOWN")] = tiers.get(row.get("tier", "UNKNOWN"), 0) + 1

    lines = [
        _BANNER,
        f"# {system} subsystem",
        "",
        f"{len(rows)} functions — {named} named.",
        "",
        "| Tier | Functions |",
        "|------|----------:|",
    ]
    for tier in ("MATCHING", "UNDERSTOOD", "DECOMPILED", "UNKNOWN"):
        if tiers.get(tier):
            lines.append(f"| {tier} | {tiers[tier]} |")

    lines += [
        "",
        "## Functions",
        "",
        "| Function | Address | Tier | Size | Callers | Callees | RAM |",
        "|----------|---------|------|-----:|--------:|--------:|-----|",
    ]
    for row in rows:
        ram = ", ".join((row.get("ram_names") or [])[:2]) or ""
        lines.append(
            f"| {_link(row, symbols, all_pages=all_pages, prefix='../functions/')} "
            f"| `{row['addr']}` "
            f"| {row.get('tier', '')} "
            f"| {row.get('size', 0)} "
            f"| {len(row.get('callers') or [])} "
            f"| {len(row.get('callees') or [])} "
            f"| {ram} |"
        )

    evidence = [
        (name, membership[name]["evidence"])
        for name in members
        if name in membership and membership[name].get("evidence")
    ]
    if evidence:
        lines += ["", "## Why these functions are grouped here", ""]
        for name, why in evidence[:25]:
            lines.append(f"- `{name}` — {'; '.join(why)}")
        if len(evidence) > 25:
            lines.append(f"- … and {len(evidence) - 25} more with recorded evidence")
    lines.append("")
    return "\n".join(lines)


def render_function(
    row: dict[str, Any],
    symbols: dict[str, Any],
    by_name: dict[str, dict[str, Any]],
    *,
    all_pages: bool = False,
) -> str:
    display = display_name(row, symbols)
    entry = symbols.get(row.get("addr", "")) or {}
    lines = [
        _BANNER,
        f"# `{display}`",
        "",
        "| | |",
        "|--|--|",
        f"| ROM | `{row['addr']}` |",
        f"| Size | {row.get('size', 0)} bytes ({row.get('insn_count', 0)} instructions) |",
        f"| Tier | {row.get('tier', '')} |",
        f"| Status | {row.get('status', '')} |",
        f"| Subsystem | {row.get('system') or '_unassigned_'} |",
        f"| Link label | `{row['name']}` |",
    ]
    if entry:
        lines += [
            f"| Confidence | {entry.get('confidence', '')} |",
            f"| Provenance | {entry.get('source', '')} |",
        ]
    if row.get("note"):
        lines.append(f"| Note | {row['note']} |")

    if entry.get("evidence"):
        lines += ["", "## Why this name", ""]
        lines += [f"- {item}" for item in entry["evidence"]]

    if row.get("ram_names"):
        lines += ["", "## RAM referenced", ""]
        lines += [f"- `{name}`" for name in row["ram_names"]]

    if row.get("offsets"):
        lines += [
            "",
            "## Struct offsets touched",
            "",
            ", ".join(f"`{o}`" for o in row["offsets"]),
        ]

    for title, key in (("Callees", "callees"), ("Callers", "callers")):
        names = row.get(key) or []
        if not names:
            continue
        lines += ["", f"## {title}", ""]
        for name in names:
            target = by_name.get(name)
            if target is not None:
                lines.append(
                    f"- {_link(target, symbols, all_pages=all_pages)}"
                )
            else:
                lines.append(f"- `{name}` _(not one of the 633 functions)_")

    if row.get("data_refs"):
        lines += ["", "## ROM data referenced", ""]
        lines += [f"- `{addr}`" for addr in row["data_refs"]]

    lines.append("")
    return "\n".join(lines)


def render_index(
    functions: list[dict[str, Any]], symbols: dict[str, Any], *, all_pages: bool
) -> str:
    lines = [
        _BANNER,
        "# Function index",
        "",
        f"{len(functions)} functions. "
        "Names come from `analysis/symbols.json`; unnamed entries show their link label.",
        "",
        "| Function | Address | Subsystem | Tier | Size | Callers |",
        "|----------|---------|-----------|------|-----:|--------:|",
    ]
    for row in sorted(functions, key=lambda r: r["addr"]):
        lines.append(
            f"| {_link(row, symbols, all_pages=all_pages)} "
            f"| `{row['addr']}` "
            f"| {row.get('system') or ''} "
            f"| {row.get('tier', '')} "
            f"| {row.get('size', 0)} "
            f"| {len(row.get('callers') or [])} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_systems_index(
    systems: dict[str, Any],
    by_name: dict[str, dict[str, Any]],
    symbols: dict[str, Any],
    *,
    all_pages: bool,
) -> str:
    lines = [
        _BANNER,
        "# Subsystems",
        "",
        "Grouped deterministically by hardware address ranges, named RAM symbols, "
        "and hand-written notes. Membership is evidence-backed; see",
        "`analysis/systems.json`.",
        "",
        "| Subsystem | Functions | Named |",
        "|-----------|----------:|------:|",
    ]
    for system, row in sorted(systems.items()):
        members = row.get("functions") or []
        named = sum(
            1
            for m in members
            if (by_name.get(m) or {}).get("addr")
            and symbols.get((by_name.get(m) or {}).get("addr"))
        )
        lines.append(f"| [{system}]({system}.md) | {len(members)} | {named} |")
    lines.append("")
    return "\n".join(lines)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


BANNER = "<!-- AUTO-GENERATED by tools/decomp/document.py - do not edit. -->"


def _prune(directory: Path, wanted: set[Path], *, preserve_names: bool = True) -> int:
    """Delete generated pages whose names are no longer produced.

    Renaming a symbol changes its page filename, so without this the old page
    lingers and the generated tree is no longer a faithful view of
    `analysis/symbols.json`. Only files carrying our banner are considered, so
    hand-written markdown in the same directory is never removed.
    """
    if not directory.is_dir():
        return 0
    removed = 0
    for path in sorted(directory.glob("*.md")):
        if path in wanted:
            continue
        try:
            head = path.read_text(errors="replace")[:200]
        except OSError:
            continue
        if BANNER not in head:
            continue
        path.unlink()
        removed += 1
    return removed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--all",
        action="store_true",
        help="emit a page for every function, not only named ones",
    )
    args = ap.parse_args()

    data = _load("functions.json")
    functions = data.get("functions") or []
    if not functions:
        print("no analysis/functions.json — run: python3 tools/decomp/analyze.py")
        return 1

    symbols = (_load("symbols.json").get("symbols") or {})
    systems = (_load("systems.json").get("systems") or {})
    membership = (_load("systems.json").get("membership") or {})
    by_name = {r["name"]: r for r in functions}

    _write(SYSTEMS_DIR / "index.md", render_systems_index(systems, by_name, symbols, all_pages=args.all))
    for system, row in sorted(systems.items()):
        _write(
            SYSTEMS_DIR / f"{system}.md",
            render_system(
                system,
                row.get("functions") or [],
                by_name,
                symbols,
                membership,
                all_pages=args.all,
            ),
        )

    _write(FUNCTIONS_DIR / "index.md", render_index(functions, symbols, all_pages=args.all))

    # A rename changes the page's filename, so the previous one must go or the
    # generated tree stops being a faithful view of symbols.json. Only files
    # carrying our banner are removed, so hand-written notes are never touched.
    wanted: set[Path] = {FUNCTIONS_DIR / "index.md"}
    pages = 0
    for row in functions:
        entry = symbols.get(row.get("addr", "")) or {}
        if not entry.get("symbol") and not args.all:
            continue
        display = display_name(row, symbols)
        if not display:
            continue
        path = FUNCTIONS_DIR / f"{display}.md"
        wanted.add(path)
        _write(path, render_function(row, symbols, by_name, all_pages=args.all))
        pages += 1

    pruned = _prune(FUNCTIONS_DIR, wanted, preserve_names=False)

    print("=== documentation ===")
    print(f"  systems/index.md      {len(systems)} subsystem page(s)")
    print(f"  functions/index.md    {len(functions)} functions indexed")
    print(f"  functions/*.md        {pages} page(s)")
    if pruned:
        print(f"  pruned stale          {pruned} page(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
