#!/usr/bin/env python3
"""Generate asm/nonmatchings from baserom.gba via Luvdis.

Assembly is regenerated — do not edit asm/nonmatchings/*.s by hand.
Rename functions in beyblade_g_revolution.toml [renames].
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASEROM = ROOT / "baserom.gba"
Luvdis = ROOT / "tools" / "luvdis"
OUT_DIR = ROOT / "asm" / "nonmatchings"
MATCH_DIR = ROOT / "asm" / "matchings"
MONOLITH = ROOT / "build" / "luvdis_monolith.s"
CONFIG_OUT = ROOT / "build" / "functions.cfg"

FUNC_START_RE = re.compile(r"^(?:thumb_func_start\s+)?(sub_[0-9A-F]+)\s*$")
FUNC_LABEL_RE = re.compile(r"^(sub_[0-9A-F]+):\s*$")
BYTE_RE = re.compile(r"0x[0-9A-Fa-f]{2}")


def trim_trailing_gap_bytes(body: list[str]) -> list[str]:
    """Drop raw .byte runs after the last insn / literal pool (next func gap)."""
    last_sig = -1
    for i, line in enumerate(body):
        s = line.strip()
        if not s or s.startswith("@"):
            continue
        if ".4byte" in s:
            last_sig = i
            continue
        if s.endswith(":"):
            continue
        if s.startswith(".byte"):
            if BYTE_RE.findall(s) and len(BYTE_RE.findall(s)) <= 2 and last_sig >= 0:
                last_sig = i
            continue
        if not s.startswith(".") and ":" not in s:
            last_sig = i
    if last_sig < 0:
        return body
    body = body[: last_sig + 1]
    # Drop inter-function alignment padding (not literal pools).
    while body and body[-1].strip().startswith(".byte"):
        body.pop()
    return body


def run_luvdis() -> None:
    if not BASEROM.is_file():
        sys.exit("missing baserom.gba")

    MONOLITH.parent.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MATCH_DIR.mkdir(parents=True, exist_ok=True)

    luvdis_main = Luvdis / "luvdis" / "__main__.py"
    if not luvdis_main.is_file():
        print(
            "warning: tools/luvdis not present — run build_tools.sh first.\n"
            "         Leaving asm/rom.s incbin scaffold in place.",
            file=sys.stderr,
        )
        return

    cmd = [
        sys.executable,
        "-m",
        "luvdis",
        str(BASEROM),
        "-o",
        str(MONOLITH),
        "-co",
        str(CONFIG_OUT),
        "--guess",
        "--macros",
        str(ROOT / "asm" / "macros.inc"),
    ]
    env = {**os.environ, "PYTHONPATH": str(Luvdis)}
    subprocess.run(cmd, check=True, cwd=str(Luvdis), env=env)
    split_monolith(MONOLITH)


def split_monolith(path: Path) -> None:
    """Split Luvdis monolith into one .s per sub_* function."""
    if not path.is_file():
        return

    header = [
        "@ Generated by tools/decomp/generate_asm.py — do not edit\n",
        ".syntax unified\n",
        ".thumb\n",
        ".text\n",
    ]

    lines = path.read_text().splitlines()
    chunks: dict[str, list[str]] = {}
    current: str | None = None

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("thumb_func_start "):
            current = stripped.split()[-1]
            chunks.setdefault(current, [f"{current}:"])
            continue
        m = FUNC_LABEL_RE.match(stripped)
        if m:
            name = m.group(1)
            if current != name:
                current = name
                chunks.setdefault(current, [f"{current}:"])
            continue
        if current is not None:
            chunks[current].append(line)

    for name, body in chunks.items():
        body = trim_trailing_gap_bytes(body)
        text = "".join(header) + "\n".join(body) + "\n"
        (OUT_DIR / f"{name}.s").write_text(text)

    print(f"generate_asm: wrote {len(chunks)} sub_* functions to {OUT_DIR}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="Regenerate even if output exists")
    args = parser.parse_args()

    if OUT_DIR.exists() and any(OUT_DIR.glob("sub_*.s")) and not args.force:
        print(f"generate_asm: {OUT_DIR} already populated (use --force)")
        return 0

    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    MATCH_DIR.mkdir(parents=True, exist_ok=True)

    macros = ROOT / "asm" / "macros.inc"
    if not macros.is_file():
        macros.write_text(
            "@ Luvdis / matching asm macros\n"
            ".syntax unified\n"
            ".arm\n"
            ".thumb\n"
        )

    run_luvdis()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
