#!/usr/bin/env python3
"""Generate src/weather_gfx.c: the particle art of the weather entry.

Nine 8x8 4bpp OBJ tiles and one 16-colour palette, drawn here as text. Each
character is a palette index ('.' is transparent, 0-9/a-f are the colours
below); a tile row is read left to right.

usage: gen_weather_gfx.py <out.c>
"""
import sys

def rgb(r, g, b):
    return r | (g << 5) | (b << 10)

# index: colour (5 bits per channel)
PALETTE = {
    0: (0, 0, 0),        # transparent
    1: (31, 31, 31),     # snow
    2: (22, 27, 31),     # snow edge / rain highlight
    3: (9, 17, 29),      # rain
    4: (5, 11, 24),      # rain head
    5: (31, 31, 31),     # wind streak, light
    6: (11, 15, 22),     # wind streak, slate
    7: (31, 29, 10),     # ember core
    8: (31, 18, 3),      # ember
    9: (26, 8, 2),       # ember rim
}

TILES = {
    # 0, 1: rain drop, the two halves of an 8x16 sprite; falls down and a
    # little to the left
    0: [
        ".....23.",
        ".....23.",
        ".....23.",
        ".....23.",
        "....23..",
        "....23..",
        "....23..",
        "....23..",
    ],
    1: [
        "...23...",
        "...23...",
        "...23...",
        "...23...",
        "..23....",
        "..23....",
        "..34....",
        "..4.....",
    ],
    # 2: big snow flake
    2: [
        "........",
        "...22...",
        "..2112..",
        ".211112.",
        ".211112.",
        "..2112..",
        "...22...",
        "........",
    ],
    # 3: small snow flake
    3: [
        "........",
        "........",
        "...22...",
        "..2112..",
        "..2112..",
        "...22...",
        "........",
        "........",
    ],
    # 4, 5: wind streaks, the two halves of a 16x8 sprite
    4: [
        "......55",
        "......66",
        "........",
        "..555555",
        "..666666",
        "........",
        "....5555",
        "....6666",
    ],
    5: [
        "55555...",
        "66666...",
        "........",
        "55555555",
        "66666666",
        "........",
        "55555...",
        "66666...",
    ],
    # 6: ember, bright
    6: [
        "........",
        "...88...",
        "..8778..",
        "..8778..",
        "...88...",
        "........",
        "........",
        "........",
    ],
    # 7: ember, dim
    7: [
        "........",
        "........",
        "...99...",
        "..9889..",
        "..9889..",
        "...99...",
        "........",
        "........",
    ],
    # 8: spark
    8: [
        "........",
        "........",
        "........",
        "...77...",
        "...77...",
        "........",
        "........",
        "........",
    ],
}

def tile_words(rows):
    words = []
    for row in rows:
        assert len(row) == 8, row
        w = 0
        for x, ch in enumerate(row):
            if ch != ".":
                w |= int(ch, 16) << (4 * x)
        words.append(w)
    return words

def main():
    out = sys.argv[1]
    lines = [
        "/* Generated by gen_weather_gfx.py. */",
        '#include "debug_menu.h"',
        "",
        "const u32 gWeatherTiles[WEATHER_TILES][8] = {",
    ]
    for n in range(len(TILES)):
        words = ", ".join("0x%08X" % w for w in tile_words(TILES[n]))
        lines.append("    { %s }," % words)
    lines += ["};", "", "const u16 gWeatherPalette[16] = {"]
    cols = [rgb(*PALETTE.get(i, (0, 0, 0))) for i in range(16)]
    lines.append("    " + ", ".join("0x%04X" % c for c in cols))
    lines += ["};", ""]
    open(out, "w").write("\n".join(lines))

main()
