#!/usr/bin/env python3
"""Generate src/character_looks.c: every distinct person sprite in the game.

The game draws each scene NPC (table at 0x0807BE04, one row per NPC id) with
the template in the row and the palette gData_080775CC[id] (0x080775CC); this
lists every distinct (template, palette) pair of the 15- to 31-frame person
sprites, in id order, with the NPC ids that use it.

Names: the ROM does not say who an NPC is. Kai, Kenny, Max and Daichi are
picked by eye (MAIN below), a few more come from NAMES; everything else is "NPC <id>" with Tyson's
portrait. Add an entry to MAIN (name/portrait index -> NPC id) to name another.

usage: gen_looks.py <rom.gba> <ow.state> <out.c> [preview.png]
"""
import os, shutil, struct, sys, tempfile, colorsys
sys.path.insert(0, "tools/mod/emu")
from emu import Emu
from PIL import Image

rom_path, state, out = sys.argv[1:4]
preview = sys.argv[4] if len(sys.argv) > 4 else None
rom = open("baserom.gba", "rb").read()
def rw(a): return struct.unpack_from("<I", rom, a - 0x08000000)[0]
def pal(a): return [struct.unpack_from("<H", rom, a - 0x08000000 + 2 * i)[0] for i in range(16)]
def to8(c): return tuple(((v & 31) << 3) | ((v & 31) >> 2) for v in (c, c >> 5, c >> 10))
def hsv(c): return colorsys.rgb_to_hsv(*(x / 255 for x in c))
def is_skin(c):
    h, s, v = hsv(c); return 0.0 <= h <= 0.12 and 0.2 <= s <= 0.65 and v >= 0.5
def is_neutral(c):
    h, s, v = hsv(c); return s < 0.18 or v < 0.2
def dist(a, b): return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5

MAIN = {31: 26, 30: 99, 13: 58, 20: 34}   # name/portrait index -> NPC id (by eye)
# NPC id -> name for sprites with no blader portrait (from the player's own knowledge of the game)
NAMES = {0: "Grandpa", 13: "Bonz", 33: "Jin of the Gale"}
HUMANS = list(range(28))
FRAMES = (12, 15, 17, 29, 31)
HERO = (0x083147C8, 0x083002E0)

_sav = tempfile.mktemp(suffix=".sav"); shutil.copy("beyblade_g_revolution.sav", _sav)
e = Emu(rom_path, _sav)
OBJ = 0x02000804 + 0x36C

def hide_bg():
    e.w16(0x04000000, e.r16(0x04000000) & ~0x0F00); e.w16(0x05000000, 0x7C1F)

def _unused(im, lookup=None):
    px = [(x, y, im.getpixel((x, y))) for y in range(im.height) for x in range(im.width)
          if im.getpixel((x, y)) != (255, 0, 255)]
    px = [q for q in px if lookup is None or q[2] in lookup]
    if not px: return None
    ys = [q[1] for q in px]; y0, y1 = min(ys), max(ys); h = max(1, y1 - y0)
    def dom(sel):
        cnt = {}
        for x, y, c in px:
            if sel(y, c): cnt[c] = cnt.get(c, 0) + 1
        return max(cnt, key=cnt.get) if cnt else None
    hair = dom(lambda y, c: y < y0 + 0.4 * h and not is_skin(c) and not is_neutral(c))
    outfit = dom(lambda y, c: y > y0 + 0.5 * h and not is_skin(c) and not is_neutral(c))
    return hair or (80, 60, 40), outfit or (120, 60, 60)

# 1. distinct person sprites
pairs = {}
for i in range(246):
    t = rw(0x0807BE04 + 0x1c * i + 0x10); p = rw(0x080775CC + 4 * i)
    if 0x08200000 <= t < 0x08320000 and rw(t + 4) == 0x9a082010 and 0x08000000 <= p < 0x08400000 \
            and rw(t) in FRAMES and (t, p) != HERO:
        pairs.setdefault((t, p), []).append(i)
order = sorted(pairs, key=lambda k: pairs[k][0])
print(len(order), "distinct person sprites")

# 2. names
name_of = {}                       # (t, p) -> name index
for idx, npc in MAIN.items():
    t = rw(0x0807BE04 + 0x1c * npc + 0x10); p = rw(0x080775CC + 4 * npc)
    name_of[(t, p)] = idx
named = sorted((k for k in order if k in name_of), key=lambda k: name_of[k])
rest = [k for k in order if k not in name_of]
final = named + rest

with open(out, "w") as f:
    f.write("/* Generated by mods/debug_menu/tools/gen_looks.py; do not edit. Every person\n"
            " * sprite the game draws: walking sprite template, its palette, the blader\n"
            " * portrait / name index (56 = none, the player's), and the lowest NPC id that\n"
            " * uses it (shown as \"NPC <id>\" when there is no name). */\n"
            "#include \"debug_menu.h\"\n\n"
            "const struct CharacterLook gCharacterLooks[CHARACTER_COUNT] = {\n")
    for k in final:
        nm = next((NAMES[i] for i in pairs[k] if i in NAMES), None)
        f.write("    {0x%08X, 0x%08X, %d, %d, %s},\n" % (k[0], k[1], name_of.get(k, 56), pairs[k][0],
                                                       '"%s"' % nm if nm else "0"))
    f.write("};\n")
# every person sprite template and every OBJ palette, for the Sprite / Palette settings
templates = sorted(set(t for t in (rw(0x0807BE04 + 0x1c * i + 0x10) for i in range(246))
                       if 0x08200000 <= t < 0x08330000 and rw(t + 4) == 0x9a082010) | {0x0831805C})
palettes = set(0x082FAAE0 + 0x200 * k for k in range(51)) | set(0x080D2DCC + 0x200 * k for k in range(26))
palettes |= set(rw(0x080775CC + 4 * i) for i in range(246) if 0x08000000 <= rw(0x080775CC + 4 * i) < 0x08400000)
palettes = sorted(p for p in palettes if p % 4 == 0)
with open(out, "a") as f:
    f.write("\n/* Every person walking-sprite template in the ROM. */\n"
            "const u32 gSpriteTemplates[SPRITE_COUNT] = {\n")
    for t in templates: f.write("    0x%08X,\n" % t)
    f.write("};\n\n/* Every OBJ palette the game uses for them. */\nconst u32 gSpritePalettes[PALETTE_COUNT] = {\n")
    for p in palettes: f.write("    0x%08X,\n" % p)
    f.write("};\n")
with open(os.path.join(os.path.dirname(out), "..", "include", "character_count.h"), "w") as f:
    f.write("/* Generated by gen_looks.py. */\n#define CHARACTER_COUNT %d\n#define SPRITE_COUNT %d\n#define PALETTE_COUNT %d\n"
            % (len(final), len(templates), len(palettes)))
for k in final: print(hex(k[0]), hex(k[1]), name_of.get(k, "-"), pairs[k])

if preview:
    tiles = []
    for k in final:
        e.load(state); e.frames(2)
        e.call(0x08068809, OBJ); e.w32(OBJ, k[0]); e.call(0x08068419, OBJ); e.call(0x08067CE9, OBJ, 0)
        for j, v in enumerate(pal(k[1])): e.w16(0x05000200 + 2 * j, v)
        e.frames(2, "DOWN"); e.frames(8); e.shot("/tmp/_p.png", scale=1)
        tiles.append(Image.open("/tmp/_p.png").convert("RGB").crop((108, 126, 140, 166)).resize((64, 80), Image.NEAREST))
    cols = 14
    sheet = Image.new("RGB", (64 * cols, 80 * ((len(tiles) + cols - 1) // cols)))
    for n, t_ in enumerate(tiles): sheet.paste(t_, ((n % cols) * 64, (n // cols) * 80))
    sheet.save(preview)
