#ifndef GUARD_SYMBOLS_H
#define GUARD_SYMBOLS_H

/*
 * AUTO-GENERATED by tools/decomp/symbols.py - do not edit.
 *
 * Readable names for named functions. Each alias expands to the real link
 * label, so the preprocessor emits `sub_XXXXXXXX` exactly as before and
 * `make compare` is unaffected by naming.
 *
 * Names live in analysis/symbols.json. Regenerate with `make symbols`.
 */

#define GetIndexedRecordWord sub_0802B8BC

#endif // GUARD_SYMBOLS_H
