#ifndef GUARD_SYMBOLS_H
#define GUARD_SYMBOLS_H

/*
 * AUTO-GENERATED by tools/decomp/symbols.py - do not edit.
 *
 * Readable names for named functions. Each alias expands to the real link
 * label, so the preprocessor emits `sub_XXXXXXXX` exactly as before and
 * `make compare` is unaffected by naming.
 *
 * Names live in analysis/symbols.json. Regenerate with `make symbols`.
 */

#define GetIndexedRecordWord sub_0802B8BC
#define Unk75AB8Lookup sub_0802B930
#define BtlFreeUnk1694Obj sub_0802BA4C
#define BtlUnk1694FindAndMark sub_0802C5DC
#define BtlSetTimer118 sub_080314FC
#define BtlSetMode1F90 sub_080330F4
#define BtlClearState sub_08033878
#define BtlCaptureInput sub_08034894
#define Unk8D0FindActiveById sub_0803E258
#define BtlCountLiveSlots sub_0803E440
#define BtlClearUnk1834 sub_080433F4
#define BtlClearUnk1688Entry sub_08044EE8
#define BtlSetAllUnk1710 sub_080603E0
#define TextDraw sub_08061564
#define TextSetCursor sub_080615EC
#define TextSetPaletteBank sub_08061610
#define TextDrawAlign sub_0806171C
#define TextGetAreaWidth sub_08061784
#define TextSetActiveObject sub_080617C4
#define TextRowSetPaletteBank sub_08061D68
#define RandRange sub_080628B4
#define Div sub_080674A0
#define DivRemainder sub_080674A4
#define LZ77UnCompWram sub_080674AC
#define Sqrt sub_080674B0
#define VBlankIntrWait sub_080674B4
#define TimerAdvance sub_08067890
#define DebugMessage sub_08067A9C
#define DebugPrint sub_08067B98
#define Unk68020SelectByKey sub_08068020
#define Unk680CCSelectByKeyDefault sub_080680CC
#define BgGetHofsReg sub_08069908
#define BgGetVofsReg sub_08069948
#define BtlObjAlloc sub_0806A3A4
#define BtlObjFree sub_0806A434
#define Unk84FindIndexByKey sub_0806F1A0
#define BtlObjPoolAlloc sub_0806FDD0
#define BtlObjPoolFree sub_0806FE84
#define BtlObjListMoveHeadToTail sub_0806FEFC
#define BtlObjListMoveToHead sub_0806FF28
#define TextEntrySetPaletteBank sub_080705DC
#define BtlReleaseEntry sub_08070678
#define GetBtlLookupByte sub_08072F94
#define BtlObjTableAdd sub_0807309C
#define BtlObjTableRemove sub_08073114
#define MemClear sub_08073184
#define TextFormatInt sub_080735DC
#define TextMeasureWidth sub_08073988

#endif // GUARD_SYMBOLS_H
