#!/usr/bin/env python3
"""Classify every IWRAM / EWRAM byte and write docs/ram-coverage.md.

Per byte, highest priority first:
  region   reserved by the engine (heap / stack / bios), asm/ram_map_iwram.s / ram_map_ewram.s (kind-tagged SET_ARRAY)
  mapped   inside a named symbol or pool gUnk_* (SET_DATA = 4 bytes, SET_ARRAY = size)
  seen     written during build/ram_survey.json but no symbol covers it  <- to name
  hole     untouched gap shorter than MERGE_GAP between the above (padding / zero-valued vars)
  free     untouched run of MERGE_GAP+ bytes (candidate for mods; verify with a longer survey)

Usage:
  python3 tools/ram_survey.py          # gather the dynamic evidence (optional, additive)
  python3 tools/ram_coverage.py        # rewrite docs/ram-coverage.md
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASM = ROOT / "asm"
SURVEY = ROOT / "build" / "ram_survey.json"
OUT = ROOT / "docs" / "ram-coverage.md"

WINDOWS = {"IWRAM": (0x03000000, 0x8000), "EWRAM": (0x02000000, 0x40000),
           "EEPROM": (0x0, 0x2000)}  # EEPROM addresses are chip byte offsets
LINE = re.compile(
    r"SET_(DATA|ARRAY)\s+(\w+),\s+(0x[0-9A-Fa-f]+)(?:,\s+(0x[0-9A-Fa-f]+))?"
    r"(?:\s*@\s*(\w+):)?"
)
KINDS = ("heap", "stack", "bios", "io", "mod")  # engine-reserved
SAVE_KIND = "eeprom"                      # save data, counts as mapped
MERGE_GAP = 0x40
FREE_POOLS = ("FreeRam", "FreeEwram", "FreeFlash", "UsedFree")


def parse(path: Path):
    for raw in path.read_text().splitlines():
        if raw.lstrip().startswith("@"):
            continue
        m = LINE.search(raw)
        if not m:
            continue
        form, name, addr, size, kind = m.groups()
        if name.startswith(FREE_POOLS):
            continue
        yield name, int(addr, 16), int(size, 16) if size else 4, kind


def main() -> None:
    syms = []
    for f in ("ram_map_iwram.s", "ram_map_ewram.s", "ram_map_iwram_pool.inc",
              "ram_map_ewram_pool.inc"):
        syms += [(n, a, s, None) for n, a, s, k in parse(ASM / f) if k not in KINDS]
    syms += [(n, a, s, None) for n, a, s, k in parse(ASM / "ram_map_sram.s") if k == SAVE_KIND]
    regions = [r for f in ("ram_map_iwram.s", "ram_map_ewram.s")
               for r in parse(ASM / f) if r[3] in KINDS]
    seen = json.loads(SURVEY.read_text()) if SURVEY.is_file() else {}

    out = ["# RAM coverage", "",
           "Generated by `tools/ram_coverage.py` from `asm/ram_map_*.s` and the dynamic "
           "survey `build/ram_survey.json` (`tools/ram_survey.py`). Do not edit.", ""]
    summary, detail = [], []
    for region, (base, size) in WINDOWS.items():
        cls = ["free"] * size
        for lo, hi in seen.get(region.lower(), []):
            for i in range(lo - base, min(hi - base, size)):
                cls[i] = "seen"
        mapped_by = {}
        for n, a, s, _ in syms:
            for i in range(max(a - base, 0), min(a - base + s, size)):
                cls[i] = "mapped"
                mapped_by[i] = n
        for n, a, s, kind in regions:
            for i in range(max(a - base, 0), min(a - base + s, size)):
                cls[i] = "region"
        i = 0
        while i < size:
            if cls[i] != "free":
                i += 1
                continue
            j = i
            while j < size and cls[j] == "free":
                j += 1
            if j - i < MERGE_GAP:
                cls[i:j] = ["hole"] * (j - i)
            i = j
        counts = {k: cls.count(k) for k in ("region", "mapped", "seen", "hole", "free")}
        summary.append(f"| {region} | " + " | ".join(
            f"{counts[k]:#x} ({counts[k] * 100 / size:.1f}%)"
            for k in ("region", "mapped", "seen", "hole", "free")) + f" | {size:#x} |")

        detail += [f"## {region}", "", "### Engine regions", "",
                   "| Start | End | Size | Kind | Name |", "|---|---|---:|---|---|"]
        for n, a, s, kind in sorted(regions, key=lambda r: r[1]):
            if base <= a < base + size:
                detail.append(f"| `{a:#010x}` | `{a + s:#010x}` | `{s:#x}` | {kind} | `{n}` |")
        detail.append("")
        for label, key, note in (
            ("Written but unmapped", "seen", "name these next"),
            ("Free", "free", f"runs of {MERGE_GAP:#x}+ bytes never written, no symbol, no region"),
        ):
            detail += [f"### {label} ({note})", "", "| Start | End | Size |", "|---|---|---:|"]
            spans, i = [], 0
            while i < size:
                if cls[i] != key:
                    i += 1
                    continue
                j = i
                while j < size and cls[j] == key:
                    j += 1
                spans.append([i, j])
                i = j
            if key == "seen":
                # Join writes separated only by untouched bytes (<= MERGE_GAP).
                merged = []
                for lo, hi in spans:
                    if merged and all(c in ("free", "hole") for c in cls[merged[-1][1]:lo]) \
                            and lo - merged[-1][1] <= MERGE_GAP:
                        merged[-1][1] = hi
                    else:
                        merged.append([lo, hi])
                spans = merged
            rows = len(spans)
            for lo, hi in spans:
                detail.append(f"| `{base + lo:#010x}` | `{base + hi:#010x}` | `{hi - lo:#x}` |")
            if not rows:
                detail.append("| — | — | — |")
            detail.append("")

    out += ["| Region | Engine-reserved | Mapped | Written, unmapped | Holes | Free | Window |",
            "|---|---:|---:|---:|---:|---:|---:|", *summary, ""]
    out += detail
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")
    for s in summary:
        print(s)


if __name__ == "__main__":
    main()
